/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Jubeat-Structs.h"


__attribute__((visibility("hidden")))
@interface Sequence : NSObject {
	XXStruct_Im0aFD* events;
	unsigned numEvent;
	unsigned numPlayEvent;
	unsigned endSector;
	BOOL musicBar[60];
	unsigned currentIndex;
	unsigned judgedIndex;
	unsigned currentTempo;
	unsigned oldTempo;
	unsigned lastHakuSector;
	unsigned nextHakuSector;
	unsigned lastMeasureSector;
	unsigned nextMeasureSector;
	short lastJudge[16];
	unsigned lastJudgeSector[16];
	XXStruct_VnRMnA gameScore;
	unsigned replaceTable[16];
	unsigned short _firstMarker;
	unsigned _currentSector;
	unsigned _firstMarkerSector;
	double _currentTime;
}
@property(readonly, assign, nonatomic) float playPosition;
@property(readonly, assign, nonatomic) float measurePhase;
@property(readonly, assign, nonatomic) float hakuPhase;
@property(readonly, assign, nonatomic) unsigned firstMarkerSector;
@property(readonly, assign, nonatomic) unsigned short firstMarker;
@property(readonly, assign, nonatomic) unsigned currentSector;
@property(readonly, assign, nonatomic) double currentTime;
+(short)rankOfPoint:(unsigned)point;
+(void)getMusicBarData:(char*)data raw:(id)raw;
-(void)dealloc;
-(void)judge:(int)judge;
-(void)addJudge:(short)judge;
-(const char*)getMusicBar;
-(short)rank;
-(BOOL)isExcellent;
-(BOOL)isFullcombo;
-(const XXStruct_VnRMnA*)getScore;
-(void)getMarkerState:(int*)state;
-(void)seekToTime:(double)time;
-(void)reset;
-(id)initWithCustomData:(id)customData tableData:(id)data;
-(id)initWithData:(id)data;
-(void)replaceFirstMarker;
-(void)createRandomTable;
@end

