//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel, UITextField, UITextView;

@interface ConsoleView : UIView
{
    UITextView *pTextView;
    UITextField *pTextField;
    UIButton *pOkButton;
    UIButton *pCancelButton;
    UILabel *pLimitLength;
}

@property(retain, nonatomic) UILabel *pLimitLength; // @synthesize pLimitLength;
@property(retain, nonatomic) UIButton *pCancelButton; // @synthesize pCancelButton;
@property(retain, nonatomic) UIButton *pOkButton; // @synthesize pOkButton;
@property(retain, nonatomic) UITextField *pTextField; // @synthesize pTextField;
@property(retain, nonatomic) UITextView *pTextView; // @synthesize pTextView;

@end

