//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GKGameCenterControllerDelegate-Protocol.h"
#import "GKMatchmakerViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString;

@interface DefaultUIHandler : NSObject <GKMatchmakerViewControllerDelegate, GKGameCenterControllerDelegate, UINavigationControllerDelegate>
{
    _Bool mIsShow;
}

@property(readonly, nonatomic) _Bool mIsShow; // @synthesize mIsShow;
- (void)execShowUI:(id)arg1;
- (void)switchMainThread:(id)arg1;
- (_Bool)showAchievementUI;
- (_Bool)showLeaderboardUI;
- (_Bool)showMatchmakeInviteUI:(id)arg1;
- (_Bool)showMatchmakeUI:(int)arg1:(int)arg2:(int)arg3;
- (void)matchmakerViewController:(id)arg1 didFindPlayers:(id)arg2;
- (void)matchmakerViewController:(id)arg1 didFindMatch:(id)arg2;
- (void)matchmakerViewController:(id)arg1 didFailWithError:(id)arg2;
- (void)matchmakerViewControllerWasCancelled:(id)arg1;
- (void)gameCenterViewControllerDidFinish:(id)arg1;
- (void)didFailWithError:(int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

