//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface DFileTagObj : NSObject
{
    char tagstr[5];
    NSMutableArray *m_DFileHObjArray;
    char *save_infodata;
    int save_size;
}

- (void).cxx_destruct;
- (id)GetFileObjArray;
- (id)GetFileObj:(char *)arg1;
- (void)AddDFileObj:(id)arg1;
- (char *)GetTag;
- (void)SetTag:(char *)arg1;
- (int)GetObjNum;
- (int)GetSaveInfoDataSize;
- (void)DeleteInfoDataS;
- (char *)GetInfoDataS;
- (void)dealloc;
- (id)init;

@end

