//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface DFileHObj : NSObject
{
    BOOL hedstr;
    NSMutableArray *m_DFileObjArray;
    char *save_infodata;
}

- (void).cxx_destruct;
- (id)GetFileObjAll;
- (id)GetFileObj:(char *)arg1;
- (void)AddDFileObj:(id)arg1;
- (BOOL)GetHedstr;
- (void)SetHedstr:(BOOL)arg1;
- (int)GetObjNum;
- (void)DeleteInfoDataS;
- (char *)GetInfoDataS;
- (void)dealloc;
- (id)init;

@end

