//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DownloadUtility : NSObject
{
}

+ (id)sha1_d:(id)arg1:(unsigned long long)arg2;
+ (id)sha1Digest:(id)arg1;
+ (id)base64forDataURL:(id)arg1;
+ (id)dataFromBase64String:(id)arg1;
+ (id)base64forData:(id)arg1;
+ (id)GetHomePash:(id)arg1;
+ (id)GetCachesDirectyPash:(id)arg1;
+ (id)GetDirectyPash:(id)arg1;
+ (id)gzipInflate:(id)arg1;
- (void)dealloc;
- (id)init;

@end

