//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface DownloadListManageObj : NSObject
{
    NSMutableArray *m_DFileTagObjArray;
    char *save_infodata;
}

- (void).cxx_destruct;
- (id)GetFileObj_TagArray:(char *)arg1;
- (id)GetFileObj_Name:(char *)arg1;
- (id)GetFileObj:(char *)arg1:(char *)arg2;
- (void)SetDFileDataInfo:(CDStruct_7bb32e46 *)arg1;
- (void)SetDFileDataXMLNode:(id)arg1;
- (void)SetDFileData:(id)arg1;
- (void)DeleteInfoDataS;
- (void)LoadInfoDataS;
- (void)SaveInfoDataS;
- (void)DeleteList;
- (void)dealloc;
- (id)init;

@end

