//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, UIAlertView, UIProgressView;

@interface DownloadProgressBarWindow : NSObject
{
    UIAlertView *m_alert;
    UIProgressView *m_pv;
    int count;
    int max;
    _Bool isview;
    NSDate *m_date;
    _Bool isshow;
}

- (_Bool)isView;
- (void)ProgressBarWindowClose;
- (void)ProgressBarWindowShow;
- (int)GetMax;
- (void)SetMax:(int)arg1;
- (void)SetCount:(int)arg1;
- (void)Update;
- (void)dealloc;
- (id)init;

@end

