//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UtilityMcrypt;

@interface FileDownload : NSObject
{
    NSString *m_FileName;
    NSString *m_DirectyName;
    NSString *m_key;
    _Bool m_base64;
    _Bool m_gzip;
    NSString *m_hash;
    long long m_size;
    long long m_dataSize;
    NSString *m_tag;
    NSString *m_url;
    UtilityMcrypt *m_mcrypt;
    struct cPrtcl_Download_File *mpPrtcl_download_file;
}

- (void).cxx_destruct;
- (void)setExcludedAttributes:(const char *)arg1;
- (long long)GetDownloadSize;
- (struct cPrtcl_Download_File *)GetFileDownloadPrtclClass;
- (id)GetTagName;
- (id)GetFileName;
- (void)SetBase64Mode:(_Bool)arg1;
- (void)SetGZipMode:(_Bool)arg1;
- (void)SetTagName:(id)arg1;
- (void)SetDirectyName:(id)arg1;
- (void)SetSize:(long long)arg1;
- (void)SetHash:(id)arg1;
- (void)SetKey:(id)arg1;
- (void)SetFileName:(id)arg1;
- (_Bool)isFile:(id)arg1;
- (_Bool)FileCreation:(id)arg1;
- (void)ConnectComplet:(id)arg1;
- (void)ConnectEnd;
- (void)ConnectStart;
- (void)SetURL:(id)arg1;
- (void)dealloc;
- (id)init;

@end

