//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FileDownloadListObj : NSObject
{
    CDStruct_7bb32e46 m_info;
    char m_hash[64];
}

- (id).cxx_construct;
- (_Bool)GetBase64;
- (_Bool)GetGZip;
- (long long)GetSize;
- (id)GetDirectory;
- (id)GetHash;
- (id)GetTag;
- (id)GetKey;
- (int)GetVer;
- (id)GetFileName;
- (void)SetHash:(id)arg1;
- (void)SetDataFromXMLNode:(id)arg1;
- (void)SetDataFromFileListInfo:(CDStruct_7bb32e46 *)arg1;
- (void)SetData:(id)arg1:(int)arg2:(id)arg3;
- (void)dealloc;
- (id)init;

@end

