//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GKMatch, GKMatchmakerViewController, GKPlayer, NSArray, NSError, NSString;

@protocol GKMatchmakerViewControllerDelegate <NSObject>
- (void)matchmakerViewController:(GKMatchmakerViewController *)arg1 didFailWithError:(NSError *)arg2;
- (void)matchmakerViewControllerWasCancelled:(GKMatchmakerViewController *)arg1;

@optional
- (void)matchmakerViewController:(GKMatchmakerViewController *)arg1 didReceiveAcceptFromHostedPlayer:(NSString *)arg2;
- (void)matchmakerViewController:(GKMatchmakerViewController *)arg1 hostedPlayerDidAccept:(GKPlayer *)arg2;
- (void)matchmakerViewController:(GKMatchmakerViewController *)arg1 didFindPlayers:(NSArray *)arg2;
- (void)matchmakerViewController:(GKMatchmakerViewController *)arg1 didFindHostedPlayers:(NSArray *)arg2;
- (void)matchmakerViewController:(GKMatchmakerViewController *)arg1 didFindMatch:(GKMatch *)arg2;
@end

