//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "iOSAppDelegate.h"

@interface iOSAppDelegate (Private)
- (void)removeAudioRouteChangeObserver;
- (void)registerAudioRouteChangeObserver;
- (void)activateAVAudioSession;
- (void)deleteDeviceOrientation;
- (void)createDeviceOrientation;
- (void)showMainWindow;
- (void)deleteMainWindow;
- (void)createMainWindow;
- (void)deleteGameApp;
- (void)createGameApp;
@end

