//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSFileVersion, NSString, iOSCloudDocument;

@interface iOSCloudEntry : NSObject
{
    int _entryState;
    NSString *_key;
    iOSCloudDocument *_document;
    NSFileVersion *_currentVersion;
    NSArray *_conflictVersions;
}

@property(retain) NSArray *conflictVersions; // @synthesize conflictVersions=_conflictVersions;
@property(retain) NSFileVersion *currentVersion; // @synthesize currentVersion=_currentVersion;
@property(retain) iOSCloudDocument *document; // @synthesize document=_document;
@property(retain) NSString *key; // @synthesize key=_key;
@property int entryState; // @synthesize entryState=_entryState;
- (void).cxx_destruct;
- (id)initWithFileURL:(id)arg1 withKey:(id)arg2;
- (id)initWithDocument:(id)arg1 withKey:(id)arg2;
- (id)initWithKey:(id)arg1;

@end

