//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIGestureRecognizer;

@interface iOSGestureHandle : NSObject
{
    struct NativeGesture *object;
    struct Info mInfo;
    struct Touch mTouches[10];
    UIGestureRecognizer *recognizer;
}

@property(readonly, nonatomic) UIGestureRecognizer *recognizer; // @synthesize recognizer;
@property(readonly, nonatomic) struct NativeGesture *object; // @synthesize object;
- (id).cxx_construct;
- (void)create:(struct Info *)arg1 withTouches:(id)arg2 inView:(id)arg3;
- (void)adjustSwipeGestureDeviceOrientation:(int)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2 inView:(id)arg3;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2 inView:(id)arg3;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2 inView:(id)arg3;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2 inView:(id)arg3;
- (void)unregisterHandle:(id)arg1;
- (void)registerHandle:(id)arg1;
- (void)handlePinchGesture:(id)arg1;
- (void)handleRotateGesture:(id)arg1;
- (void)handleSwipeGesture:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (void)dealloc;
- (void)terminate;
- (id)initWithGesture:(struct NativeGesture *)arg1 dependOn:(struct NativeGesture *)arg2;

@end

