//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SKPaymentTransactionObserver-Protocol.h"
#import "SKProductsRequestDelegate-Protocol.h"

@class NSMutableArray, NSString, SKPaymentTransaction, SKProductsRequest, UIAlertView;

@interface iOSStoreKit : NSObject <SKProductsRequestDelegate, SKPaymentTransactionObserver>
{
    SKProductsRequest *mpProductsRequest;
    SKPaymentTransaction *mpRequestTransaction;
    NSMutableArray *mProductSuccess;
    NSMutableArray *mProductFailed;
    UIAlertView *mpAlertViewIndicator;
    UIAlertView *mpAlertView;
    _Bool mIsSetObserver;
    int mState;
    int mBuyState;
    _Bool mIsPopupON;
    _Bool mIsPopupOFF;
    int mPopupType;
    const char *mPopupText;
    char *mpReceipt;
    int mReceiptSize;
    NSString *mpPurchasedProductID;
    CDUnknownBlockType _onTransactionStateChange;
}

@property(copy, nonatomic) CDUnknownBlockType onTransactionStateChange; // @synthesize onTransactionStateChange=_onTransactionStateChange;
- (void).cxx_destruct;
- (int)StoreLogLoad;
- (void)StoreLogSave:(int)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertViewEnable:(char *)arg1;
- (void)alertViewIndicatorDisable;
- (void)alertViewIndicatorEnable:(char *)arg1;
- (id)base64forData:(id)arg1;
- (_Bool)IsPreviousTransactions:(id)arg1;
- (void)paymentQueue:(id)arg1 removedTransactions:(id)arg2;
- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
- (void)finishPurchasedTransaction;
- (void)requestRestoreTransactions;
- (void)failedTransaction:(id)arg1;
- (void)restoreTransaction:(id)arg1;
- (void)completeTransaction:(id)arg1;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)removeObserver;
- (void)createObserver;
- (_Bool)isExistUnattendedTransaction:(id)arg1;
- (_Bool)iscanMakePayments;
- (_Bool)networkConnectCheck;
- (_Bool)paymentCheck;
- (_Bool)isUntreatedTransaction;
- (void)paymentRequest:(id)arg1;
- (int)getShopItemPrice:(id)arg1;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (_Bool)requestStartArray:(id)arg1;
- (_Bool)requestStart:(id)arg1;
- (_Bool)isPurchasedProductIDByPaymentQueue:(id)arg1;
- (id)getPurchasedTransactionByPaymentQueue:(id)arg1;
- (id)getProductIdByTransaction:(id)arg1;
- (int)getReceiptsize;
- (char *)getReceipt;
- (const char *)getPopupText;
- (int)getPopupType;
- (void)IsPopupClose:(_Bool)arg1;
- (_Bool)IsPopupClose;
- (void)IsPopup:(_Bool)arg1;
- (_Bool)IsPopup;
- (int)getBuyState;
- (int)getState;
- (void)dealloc;
- (void)close;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

