//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface LocalViewController : UIViewController
{
    _Bool mIsAddSuperView;
    UIViewController *mPresentingViewController;
}

- (void)close;
- (void)open:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)didBecomeActive;
- (void)dealloc;
- (id)init;

@end

