//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AVPlayerLayer, CALayer;

@interface MovieView : UIView
{
    CALayer *contentLayer;
    AVPlayerLayer *previewLayer;
    CALayer *subtitleLayer;
}

@property(nonatomic) CALayer *subtitleLayer; // @synthesize subtitleLayer;
@property(nonatomic) AVPlayerLayer *previewLayer; // @synthesize previewLayer;
@property(nonatomic) CALayer *contentLayer; // @synthesize contentLayer;
- (void)handleSingleTapFrom:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)setup;

@end

