//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MovieWatcher : NSObject
{
    _Bool Error;
    _Bool ReadyToPlay;
    _Bool PlaybackDidFinished;
}

@property(readonly, nonatomic) _Bool PlaybackDidFinished; // @synthesize PlaybackDidFinished;
@property(readonly, nonatomic) _Bool ReadyToPlay; // @synthesize ReadyToPlay;
@property(readonly, nonatomic) _Bool Error; // @synthesize Error;
- (void)reset;
- (void)notifyErrorOccured;
- (void)notifyDidFinished;
- (void)notifyFullyBuffered;
- (void)moviePlaybackDidFinished:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

