//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NKNakamapViewController.h"

@interface MyNKViewCtrller : NKNakamapViewController
{
    struct cNkHandle *mpNK;
    id delegate;
    _Bool mShouldOpenPageType;
    int mOpenPageType;
}

@property(retain, nonatomic) id delegate; // @synthesize delegate;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)dismiss;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setNKHandle:(struct cNkHandle *)arg1;
- (void)chatPosted:(id)arg1;
- (_Bool)isOtherGroupInfo:(id)arg1;
- (void)processOpenPageType;
- (void)setOpenPageType:(int)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

@end

