//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, NakamapSBJsonStreamParserState, NakamapSBJsonTokeniser;
@protocol SBJsonStreamParserDelegate;

@interface NakamapSBJsonStreamParser : NSObject
{
    _Bool supportMultipleDocuments;
    id <SBJsonStreamParserDelegate> delegate;
    NakamapSBJsonTokeniser *tokeniser;
    NSMutableArray *stateStack;
    NakamapSBJsonStreamParserState *state;
    unsigned long long maxDepth;
    NSString *error;
}

@property(readonly, retain, nonatomic) NSMutableArray *stateStack; // @synthesize stateStack;
@property(nonatomic) NakamapSBJsonStreamParserState *state; // @synthesize state;
@property unsigned long long maxDepth; // @synthesize maxDepth;
@property id <SBJsonStreamParserDelegate> delegate; // @synthesize delegate;
@property(copy) NSString *error; // @synthesize error;
@property _Bool supportMultipleDocuments; // @synthesize supportMultipleDocuments;
- (int)parse:(id)arg1;
- (void)handleArrayStart;
- (void)handleObjectStart;
- (void)maxDepthError;
- (id)tokenName:(int)arg1;
- (void)dealloc;
- (id)init;

@end

