//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NakamapSBJsonStreamWriterDelegate-Protocol.h"

@class NSData, NSMutableData;

@interface NakamapSBJsonStreamWriterAccumulator : NSObject <NakamapSBJsonStreamWriterDelegate>
{
    NSMutableData *data;
}

@property(readonly, copy) NSData *data; // @synthesize data;
- (void)writer:(id)arg1 appendBytes:(const void *)arg2 length:(unsigned long long)arg3;
- (void)dealloc;
- (id)init;

@end

