//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NKAPI : NSObject
{
}

+ (void)askStampUnlocked:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)unlockStamp:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)makeGroupWithName:(id)arg1 externalIDs:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)removeFriendsWithExternalID:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)addFriendsWithExternalIDs:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)changeLeaderWithExternalID:(id)arg1 groupExternalID:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)kickUserWithExternalID:(id)arg1 groupExternalID:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)addGroupMembersWithExternalIDs:(id)arg1 groupExternalID:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)partGroupWithExternalID:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)joinGroupWithExternalID:(id)arg1 groupName:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)deleteGroupWithExternalID:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)updateGroupWithExternalID:(id)arg1 groupName:(id)arg2 description:(id)arg3 handler:(CDUnknownBlockType)arg4;
+ (void)createGroupWithExternalID:(id)arg1 groupName:(id)arg2 invitePermission:(int)arg3 addMembersPermission:(int)arg4 joinPermission:(int)arg5 handler:(CDUnknownBlockType)arg6;
+ (void)createGroupWithExternalID:(id)arg1 groupName:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)updateUserIcon:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)updateEncryptedExternalID:(id)arg1 IV:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)signupWithBaseName:(id)arg1 encryptedExternalID:(id)arg2 IV:(id)arg3 handler:(CDUnknownBlockType)arg4;
+ (void)signupWithBaseName:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)callAPI:(id)arg1 method:(int)arg2 params:(id)arg3 handler:(CDUnknownBlockType)arg4;

@end

