//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISNetworkOperation.h"

@interface NKAPIOperation : ISNetworkOperation
{
}

+ (void)callAPI:(id)arg1 method:(int)arg2 fullParams:(id)arg3 fullHandler:(CDUnknownBlockType)arg4;
+ (void)callAPI:(id)arg1 method:(int)arg2 params:(id)arg3 handler:(CDUnknownBlockType)arg4;
- (id)processData:(id)arg1;

@end

