//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIActivityIndicatorView;

@interface NKCloseButton : UIButton
{
    UIActivityIndicatorView *_indicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
- (void)hideIndicator;
- (void)showIndicator;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

