//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface NKEndpoints : NSObject
{
    long long _environmentIndex;
    NSString *_customDomain;
}

+ (id)OAuthCallbackPath;
+ (id)signinURLWithUserName:(id)arg1;
+ (id)groupURLWithParams:(id)arg1;
+ (id)openPageURL:(id)arg1;
+ (id)appURL;
+ (id)webURL;
+ (id)ASPURL;
+ (id)streamAPIURL;
+ (id)APIURL;
+ (id)parameters;
+ (id)currentEnvironmentName;
+ (void)setCustomDomain:(id)arg1;
+ (id)customDomain;
+ (void)setEnvironment:(long long)arg1;
+ (long long)environment;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *customDomain; // @synthesize customDomain=_customDomain;
@property(nonatomic) long long environmentIndex; // @synthesize environmentIndex=_environmentIndex;
- (void)saveValues;
- (void)loadValues;

@end

