//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface NKGroupManager : NSObject
{
    NSArray *_groups;
}

@property(retain, nonatomic) NSArray *groups; // @synthesize groups=_groups;
- (void)updateWithArrivedGroupUID:(id)arg1;
- (void)updateWithAPIResponse:(id)arg1;
- (unsigned long long)numberOfUnreadGroupsSinceDate:(id)arg1 ignoreOfficialGroups:(_Bool)arg2;
- (id)groupForUID:(id)arg1;
- (void)dealloc;
- (id)init;

@end

