//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NKUser, NSDate, NSString;

@interface NKProperty : NSObject <NSCoding>
{
    _Bool _sentEncryptedID;
    _Bool _bindedWithNative;
    NSString *_accessToken;
    NSString *_encryptedID;
    NSString *_encryptIV;
    NSString *_installID;
    NKUser *_me;
    NSDate *_lastSeenDate;
    NSDate *_lastRefreshedDate;
}

+ (id)sharedProperty;
@property(retain, nonatomic) NSDate *lastRefreshedDate; // @synthesize lastRefreshedDate=_lastRefreshedDate;
@property(retain, nonatomic) NSDate *lastSeenDate; // @synthesize lastSeenDate=_lastSeenDate;
@property(retain, nonatomic) NKUser *me; // @synthesize me=_me;
@property(retain, nonatomic) NSString *installID; // @synthesize installID=_installID;
@property(retain, nonatomic) NSString *encryptIV; // @synthesize encryptIV=_encryptIV;
@property(retain, nonatomic) NSString *encryptedID; // @synthesize encryptedID=_encryptedID;
@property(retain, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property _Bool bindedWithNative; // @synthesize bindedWithNative=_bindedWithNative;
@property _Bool sentEncryptedID; // @synthesize sentEncryptedID=_sentEncryptedID;
- (void)debugReset;
- (void)migrateIfNeeded;
- (void)updateWithDictionary:(id)arg1;
- (void)refreshTokenIfNeeded;
- (id)generateUUID;
- (void)clear;
- (void)save;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
@property(readonly) NSString *buildNumber;
@property(readonly) NSString *version;
@property(readonly) _Bool needsRefreshToken;
@property(readonly) _Bool canBindWithNative;
@property(readonly) _Bool nativeInstalled;
@property(readonly) _Bool isReady;

@end

