//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface SelectNetConnectManager : NSObject
{
    NSString *m_connecturl;
    NSMutableArray *m_SelectNetConnectObjArray;
    _Bool m_DataSetFlg;
}

- (_Bool)IsDataSet;
- (id)GetUrl;
- (id)GetNextUrl;
- (void)setupIPList;
- (void)dealloc;
- (id)init;

@end

