//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SelectNetConnectObj : NSObject
{
    NSString *m_url;
    _Bool m_checkconnect;
}

- (_Bool)IsConnect;
- (id)GetUrl;
- (void)SetConnectFlg:(_Bool)arg1;
- (void)SetUrl:(id)arg1;
- (void)dealloc;
- (id)init;

@end

