//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, UtilityMcrypt, XMLParser;

@interface ServerConnectBase : NSObject
{
    NSString *server_url;
    XMLParser *xml;
    NSString *param;
    NSString *base64param;
    NSMutableArray *j_son_param;
    UtilityMcrypt *m_mcrypt;
    int netState;
    struct cPrtcl_File_List *mpPrtcl_file_list;
}

- (void).cxx_destruct;
- (struct cPrtcl_File_List *)GetFileListPrtclClass;
- (id)Base64AesDecode:(id)arg1:(char *)arg2;
- (id)GetXml;
- (void)ConnectComplet:(id)arg1;
- (int)ConnectState;
- (void)ConnectEnd;
- (void)ConnectNoParam;
- (void)Connect;
- (void)JsonParamConvert;
- (void)SetJsonParam:(id)arg1:(id)arg2;
- (void)SetURL:(id)arg1;
- (void)dealloc;
- (id)init;

@end

