//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class ConsoleView, NSMutableString, NSString, UIView;

@interface TextConsoleObject : NSObject <UITextFieldDelegate, UITextViewDelegate>
{
    UIView *pBase;
    ConsoleView *pBackground;
    ConsoleView *pBackgroundIB;
    float BackgroundRed;
    float BackgroundGreen;
    float BackgroundBlue;
    int ConsoleHeight;
    NSMutableString *pString;
    struct Notification *pNotification;
    _Bool busy;
    _Bool active;
    _Bool mbTextOpen;
    _Bool mbAutoFullScreen;
    _Bool mbDeviceOrientationNotifier;
    char mFileName[256];
    char mSetMessage[1024];
    int mTextLimit;
    int mTextNowNumber;
    int mKeyboardType;
    long long mReturnKeyType;
}

@property(readonly, nonatomic) _Bool active; // @synthesize active;
@property(readonly, nonatomic) _Bool busy; // @synthesize busy;
- (void)keyboardWillShow:(id)arg1;
- (void)setTextLimit:(int)arg1;
- (void)executeUpdateLayout:(id)arg1;
- (void)setReturnKeyType:(long long)arg1;
- (void)setKeyboardType:(int)arg1;
- (void)setAutoFullScreenMode:(_Bool)arg1;
- (void)setAutoOpenKeyboard:(_Bool)arg1;
- (void)setConsoleHeight:(int)arg1;
- (void)setBackgroundColor:(float)arg1 green:(float)arg2 blue:(float)arg3;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)replaceBanString:(id)arg1;
- (void)clearText;
- (void)textFieldEditingChanged:(id)arg1;
- (void)setText:(const char *)arg1;
- (void)setTextOnMainThread:(id)arg1;
- (const char *)getText;
- (void)touchUpOutsideEvent:(id)arg1;
- (void)touchDownEvent:(id)arg1;
- (void)clickEvent:(id)arg1;
- (void)executeHide:(id)arg1;
- (void)executeShow:(id)arg1;
- (_Bool)isIOS7;
- (void)updateLayout;
- (id)hide;
- (void)show:(struct Notification *)arg1 xibFileName:(const char *)arg2;
- (void)dealloc;
- (id)initWithView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

