//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@interface UIDevice (Hardware)
- (id)_platformCode;
- (id)_macaddress;
- (id)_platformString;
- (unsigned long long)_platformType;
- (id)_freeDiskSpace;
- (id)_totalDiskSpace;
- (unsigned long long)_maxSocketBufferSize;
- (unsigned long long)_userMemory;
- (unsigned long long)_totalMemory;
- (unsigned long long)_busFrequency;
- (unsigned long long)_cpuFrequency;
- (unsigned long long)_getSysInfo:(unsigned int)arg1;
- (id)_hwmodel;
- (id)_platform;
- (id)_getSysInfoByName:(char *)arg1;
@end

