//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UtilityMcrypt : NSObject
{
}

- (char *)MtNETDecodeBase64Data:(char *)arg1:(int)arg2:(char *)arg3:(int *)arg4:(int)arg5:(char *)arg6;
- (char *)MtNETDecodeData:(char *)arg1:(int)arg2:(char *)arg3:(int *)arg4:(int)arg5:(char *)arg6;
- (char *)MtNETEncodeData:(char *)arg1:(int)arg2:(char *)arg3:(int *)arg4:(int)arg5:(char *)arg6;
- (char *)MtFormEncodeDataAnyKey:(char *)arg1:(int)arg2:(char *)arg3:(int *)arg4:(char *)arg5;
- (char *)MtFormEncodeDataAnyKeyAutoVI:(char *)arg1:(int)arg2:(char *)arg3:(int *)arg4;
- (char *)MtAesDecode:(char *)arg1:(int)arg2:(char *)arg3:(int *)arg4;
- (char *)MtBase64AesDecode:(char *)arg1:(int)arg2:(char *)arg3:(int *)arg4;
- (id)DecodeData:(id)arg1:(id)arg2;
- (id)EncodeData:(id)arg1:(id)arg2;
- (id)NETAesDecode:(id)arg1:(char *)arg2;
- (id)NETBase64AesDecode:(id)arg1:(char *)arg2;
- (id)NETDecodeData:(id)arg1;
- (id)FormEncodeDataAnyKey:(id)arg1:(id)arg2;
- (id)NETEncodeData:(id)arg1;
- (id)mcrypt_decode:(char *)arg1:(char *)arg2:(char *)arg3:(int)arg4;
- (id)mcrypt_encode:(char *)arg1:(char *)arg2:(char *)arg3:(int)arg4;
- (void)alt_mcrypt_create_vi:(char *)arg1:(int)arg2;
- (void)dealloc;
- (id)init;

@end

