//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableArray, NSString;

@interface XMLNode : NSObject
{
    XMLNode *parent;
    NSMutableArray *children;
    NSString *nodeName;
    NSString *value;
    NSDictionary *attributeDict;
}

@property(retain, nonatomic) NSDictionary *attributeDict; // @synthesize attributeDict;
@property(retain, nonatomic) NSString *value; // @synthesize value;
@property(retain, nonatomic) NSString *nodeName; // @synthesize nodeName;
@property(retain, nonatomic) NSMutableArray *children; // @synthesize children;
@property(retain, nonatomic) XMLNode *parent; // @synthesize parent;
- (void).cxx_destruct;
- (void)dealloc;
- (void)removeNodeObject;
- (id)findChildrenByName:(id)arg1;
- (id)findChildByName:(id)arg1;
- (void)addChild:(id)arg1;
- (id)init;

@end

