//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class MusicData, NSDictionary, NSMutableArray, NSString, NSURL, RBNavigationController, RBResourceDownloadViewController, RBViewController, Reachability, UIAlertView, neWindow;

@interface AppDelegate : NSObject
{
    _Bool _applilinkInitialized;
    _Bool _isShowedMap;
    _Bool _isStarting;
    int _unreadRecommendCount;
    neWindow *_window;
    RBViewController *_viewController;
    RBNavigationController *_navigationController;
    UIAlertView *_strageAlertView;
    MusicData *_musicData;
    NSString *_searchString;
    NSDictionary *_earlyBonusList;
    NSDictionary *_hotBonusList;
    RBResourceDownloadViewController *_resourceDownloadViewController;
    Reachability *_reachability;
    NSString *_urlString;
    NSString *_version;
    NSString *_serverTime;
    NSString *_mustUpdateFlag;
    NSURL *_urlBaseWebInfo;
    NSURL *_urlWebInfo;
    NSURL *_urlPreWebInfo;
    NSString *_infoLastUpdateTimeString;
    NSString *_packIDForOpenStore;
    NSString *_campaignIDForOpenStore;
    NSMutableArray *_pushList;
    NSURL *_outerUrl;
}

+ (id)saveDataKey;
+ (_Bool)setServerData:(id)arg1 andB:(id)arg2;
+ (id)getServerData;
+ (id)musicListKey;
+ (id)totalScoreLeaderboardCategory;
+ (_Bool)setNoBackupAttribute:(id)arg1;
+ (id)appDelegate;
+ (void)setRecommendUnreadCount;
+ (void)ApplilinkInitialize;
+ (void)setOuterURL:(id)arg1;
+ (id)getOuterURL;
+ (void)addPushNotificationData:(id)arg1;
+ (id)popPushNotificationData;
+ (id)getPushNotificationData;
+ (void)initialize;
@property(copy, nonatomic) NSURL *outerUrl; // @synthesize outerUrl=_outerUrl;
@property(retain, nonatomic) NSMutableArray *pushList; // @synthesize pushList=_pushList;
@property(copy, nonatomic) NSString *campaignIDForOpenStore; // @synthesize campaignIDForOpenStore=_campaignIDForOpenStore;
@property(copy, nonatomic) NSString *packIDForOpenStore; // @synthesize packIDForOpenStore=_packIDForOpenStore;
@property(copy, nonatomic) NSString *infoLastUpdateTimeString; // @synthesize infoLastUpdateTimeString=_infoLastUpdateTimeString;
@property(copy, nonatomic) NSURL *urlPreWebInfo; // @synthesize urlPreWebInfo=_urlPreWebInfo;
@property(copy, nonatomic) NSURL *urlWebInfo; // @synthesize urlWebInfo=_urlWebInfo;
@property(copy, nonatomic) NSURL *urlBaseWebInfo; // @synthesize urlBaseWebInfo=_urlBaseWebInfo;
@property(nonatomic) _Bool isStarting; // @synthesize isStarting=_isStarting;
@property(copy, nonatomic) NSString *mustUpdateFlag; // @synthesize mustUpdateFlag=_mustUpdateFlag;
@property(copy, nonatomic) NSString *serverTime; // @synthesize serverTime=_serverTime;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
@property(retain, nonatomic) RBResourceDownloadViewController *resourceDownloadViewController; // @synthesize resourceDownloadViewController=_resourceDownloadViewController;
@property(nonatomic) _Bool isShowedMap; // @synthesize isShowedMap=_isShowedMap;
@property(retain, nonatomic) NSDictionary *hotBonusList; // @synthesize hotBonusList=_hotBonusList;
@property(retain, nonatomic) NSDictionary *earlyBonusList; // @synthesize earlyBonusList=_earlyBonusList;
@property _Bool applilinkInitialized; // @synthesize applilinkInitialized=_applilinkInitialized;
@property int unreadRecommendCount; // @synthesize unreadRecommendCount=_unreadRecommendCount;
@property(retain, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(retain, nonatomic) MusicData *musicData; // @synthesize musicData=_musicData;
@property(retain, nonatomic) UIAlertView *strageAlertView; // @synthesize strageAlertView=_strageAlertView;
@property(retain, nonatomic) RBNavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) RBViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) neWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)audioSessionInterrupted:(id)arg1;
- (void)applicationProtectedDataDidBecomeAvailable:(id)arg1;
- (void)applicationProtectedDataWillBecomeUnavailable:(id)arg1;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)startRegisterForRemoteNotification;
- (void)application:(id)arg1 didChangeStatusBarFrame:(struct CGRect)arg2;
- (void)application:(id)arg1 willChangeStatusBarFrame:(struct CGRect)arg2;
- (void)application:(id)arg1 didChangeStatusBarOrientation:(long long)arg2;
- (void)application:(id)arg1 willChangeStatusBarOrientation:(long long)arg2 duration:(double)arg3;
- (void)applicationSignificantTimeChange:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)resetGame;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showDownload;
- (void)startupRequest;
- (void)showTitle;
- (_Bool)isEnableHotBonus;
- (_Bool)isEnableEarlyBonus;
- (id)getCampaignIDForOpenStore;
- (id)getPackIDForOpenStore;
- (id)getInfoLastUpdateTimeString;
- (id)getPreWebInfoURL;
- (void)setPreWebInfoURL:(id)arg1;
- (id)getWebInfoURL;
- (void)setWebInfoURL:(id)arg1;
- (id)getBaseWebInfoURL;
- (void)requestResourceInfo;
- (void)startApplication;

@end

