//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ApplilinkDebug : NSObject
{
}

+ (id)getDisplaySpec;
+ (id)getFrequencyStatus;
+ (void)allClearCacheBannerImage;
+ (id)getDebugMode;
+ (void)debugMode:(id)arg1;
+ (void)clearDAU;
+ (void)clearInitalize;
+ (void)clearAdStatus;
+ (void)clearSession;
+ (id)versionDev;
+ (void)clearAdUDID;
+ (void)clearKeyChainOldUDID;
+ (void)clearUDID;
+ (id)old_udid;
+ (id)ad_udid;
+ (id)udid;
+ (id)categoryId;
+ (id)countryCode;

@end

