//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ApplilinkCore : NSObject
{
}

+ (void)toDelegateFailLinkWithError:(id)arg1 appParam:(id)arg2 delegate:(id)arg3;
+ (void)toDelegateFailWithError:(id)arg1 appParam:(id)arg2 delegate:(id)arg3;
+ (void)toDelegateFailLoadWithError:(id)arg1 appParam:(id)arg2 delegate:(id)arg3;
+ (void)toDelegateFailOpenWithError:(id)arg1 appParam:(id)arg2 delegate:(id)arg3;
+ (void)toDelegateDidDisappear:(id)arg1 delegate:(id)arg2;
+ (void)toDelegateDidAppear:(id)arg1 delegate:(id)arg2;
+ (void)toDelegateDidStart:(id)arg1 delegate:(id)arg2;
+ (void)appAuthSessionRegenerateWithBlock:(CDUnknownBlockType)arg1;
+ (void)updatePasteBoard;
+ (void)closeAppStore;
+ (_Bool)showAppStoreId:(id)arg1 appParam:(id)arg2 delegate:(id)arg3;
+ (id)versionDev;
+ (id)signatureKey;
+ (void)clearInitialize;
+ (void)clearAdUDID;
+ (void)clearKeyChainOldUDID;
+ (void)setAdUdid:(id)arg1;
+ (void)clearUDID;
+ (_Bool)checkUdid;
+ (id)old_udid;
+ (id)ad_udid;
+ (id)pasteBoard_udid;
+ (id)udid;
+ (id)old_udid_cache;
+ (id)ad_udid_cache;
+ (id)udid_cache;
+ (id)currentUdid;
+ (id)appliId;
+ (_Bool)isInitializeStatusFlg;
+ (_Bool)isInitializingFlg;
+ (id)mainWindow;
+ (_Bool)isBuildXcode6;
+ (void)buildUnderXcode6;
+ (_Bool)isUsedInStore;
+ (void)unusedInStore;
+ (id)getIndicatorColor;
+ (void)setIndicatorColor:(id)arg1;
+ (_Bool)isPriorityDeviceLanguages;
+ (void)setPriorityDeviceLanguages:(_Bool)arg1;
+ (_Bool)isNavigationBarCommonAppearance;
+ (void)setNavigationBarCommonAppearance:(_Bool)arg1;
+ (void)resume;
+ (void)initializeWithAppliId:(id)arg1 env:(id)arg2 resume:(_Bool)arg3 callback:(CDUnknownBlockType)arg4;

@end

