//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ApplilinkPasteBoard;

@interface ApplilinkUdid : NSObject
{
    ApplilinkPasteBoard *_pasteBoard;
}

+ (void)debugLog;
+ (id)getAdUdid;
+ (_Bool)isPasteBoardStatus;
+ (void)setUdidKeychainFromPasteBoard;
+ (id)getServiceNameOld;
+ (id)getServiceName;
+ (_Bool)isUdidSDKPasteBoard;
+ (_Bool)isUdidThreeKinds;
+ (_Bool)setUdidParameters:(id)arg1;
+ (_Bool)setUdidParameters:(id)arg1 isUDIDPriorityType:(int)arg2;
+ (id)md5WithString:(id)arg1;
+ (_Bool)isAdvertisingTrackingOSVersion;
+ (_Bool)isAdvertisingTrackingEnabled;
+ (id)getAdvertisingUdid;
+ (id)getCFUUID;
+ (void)setService:(id)arg1 withStorageIndex:(id)arg2;
+ (id)getServiceIndex:(id)arg1;
+ (_Bool)validate:(id)arg1 error:(id *)arg2;
+ (_Bool)deleteKeyChainService:(id)arg1 error:(id *)arg2;
+ (id)searchWithService:(id)arg1;
+ (id)getUdidWithService:(id)arg1 storageIndex:(id)arg2 rewardNetworkUDIDType:(int)arg3 error:(id *)arg4;
+ (_Bool)setUdidWithService:(id)arg1 withUDID:(id)arg2;
+ (_Bool)setNewUdid:(id)arg1 error:(id *)arg2;
+ (_Bool)deleteOldUdidWithError:(id *)arg1;
+ (id)getOldUdidWithError:(id *)arg1;
+ (_Bool)setOldUdid:(id)arg1 error:(id *)arg2;
+ (void)deleteAllAdvertisingUDID;
+ (_Bool)deleteAdvertisingRewardUdidIndex:(int)arg1 error:(id *)arg2;
+ (id)createAdvertisingRewardUdidWithError:(id *)arg1;
+ (id)getAdvertisingRewardUdidWithError:(id *)arg1;
+ (void)deleteAllUDID;
+ (_Bool)deleteUDIDWithServiceName:(id)arg1 storageIndex:(int)arg2 error:(id *)arg3;
+ (id)udidOldForFirstInvalidDataWithError:(id *)arg1;
+ (id)udidForFirstInvalidDataWithError:(id *)arg1;
+ (id)udidWithServiceName:(id)arg1 storageIndex:(int)arg2 error:(id *)arg3;
+ (id)writeUDIDWithUdid:(id)arg1;
+ (id)writeUDIDForFirstEmptyLocationWithUdid:(id)arg1;
+ (id)writeUDIDForFirstEmptyLocationWithError:(id *)arg1;
+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) ApplilinkPasteBoard *pasteBoard; // @synthesize pasteBoard=_pasteBoard;
- (void).cxx_destruct;
- (void)dealloc;
- (id)bundleSeedID;
- (id)init;

@end

