//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ApplilinkParameters, NSError;

@protocol ApplilinkViewDelegate <NSObject>

@optional
- (void)appListFailLinkWithError:(NSError *)arg1 withApplilinkParameters:(ApplilinkParameters *)arg2;
- (void)appListFailWithError:(NSError *)arg1 withApplilinkParameters:(ApplilinkParameters *)arg2;
- (void)appListFailLoadWithError:(NSError *)arg1 withApplilinkParameters:(ApplilinkParameters *)arg2;
- (void)appListFailOpenWithError:(NSError *)arg1 withApplilinkParameters:(ApplilinkParameters *)arg2;
- (void)appListDidDisappear:(ApplilinkParameters *)arg1;
- (void)appListDidAppear:(ApplilinkParameters *)arg1;
- (void)appListDidStart:(ApplilinkParameters *)arg1;
- (void)appListFailLinkWithError:(NSError *)arg1;
- (void)appListFailWithError:(NSError *)arg1;
- (void)appListFailLoadWithError:(NSError *)arg1;
- (void)appListFailOpenWithError:(NSError *)arg1;
- (void)appListDidDisappear;
- (void)appListDidAppear;
- (void)appListDidStart;
@end

