//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AVAudioPlayerDelegate-Protocol.h"

@class AVAudioPlayer, NSMutableArray, NSMutableDictionary, NSString, NSTimer;

@interface AudioManager : NSObject <AVAudioPlayerDelegate>
{
    struct CAPlayer *sePlayer;
    struct SAVPlayer *seAVPlayer;
    struct _SE_MANAGE_ID_ seList[4];
    _Bool isSuspend;
    _Bool isInterruption[2];
    _Bool isPlaying[2];
    float unitVolume;
    _Bool isOnPause;
    _Bool isOnPauseVoice;
    struct _SE_MANAGE_ID_ seManageId[2][4];
    int seVolume[2];
    _Bool _isStart;
    NSMutableArray *_seNameList;
    NSMutableArray *_seRidList;
    AVAudioPlayer *_bgmPlayer;
    AVAudioPlayer *_voicePlayer;
    NSTimer *_fadeTimer;
    double _bgmPlayTime;
    double _voicePlayTime;
    AVAudioPlayer *_stackBgm;
    NSMutableDictionary *_seType;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *seType; // @synthesize seType=_seType;
@property(retain, nonatomic) AVAudioPlayer *stackBgm; // @synthesize stackBgm=_stackBgm;
@property(nonatomic) double voicePlayTime; // @synthesize voicePlayTime=_voicePlayTime;
@property(nonatomic) double bgmPlayTime; // @synthesize bgmPlayTime=_bgmPlayTime;
@property(retain, nonatomic) NSTimer *fadeTimer; // @synthesize fadeTimer=_fadeTimer;
@property(retain, nonatomic) AVAudioPlayer *voicePlayer; // @synthesize voicePlayer=_voicePlayer;
@property(retain, nonatomic) AVAudioPlayer *bgmPlayer; // @synthesize bgmPlayer=_bgmPlayer;
@property(retain, nonatomic) NSMutableArray *seRidList; // @synthesize seRidList=_seRidList;
@property(retain, nonatomic) NSMutableArray *seNameList; // @synthesize seNameList=_seNameList;
@property(readonly, nonatomic) _Bool isStart; // @synthesize isStart=_isStart;
- (void).cxx_destruct;
- (void)dealloc;
- (void)systemResume;
- (void)systemSuspend;
- (void)resumePlayer:(int)arg1;
- (void)suspendPlayer:(int)arg1;
- (void)audioPlayerEndInterruption:(id)arg1 withOptions:(unsigned long long)arg2;
- (void)audioPlayerEndInterruption:(id)arg1;
- (void)audioPlayerBeginInterruption:(id)arg1;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (_Bool)isPlayingVoice;
- (_Bool)onPauseVoice;
- (_Bool)stopVoice;
- (_Bool)playVoice;
- (void)seekBgmToTop;
- (void)popBgm;
- (void)pushBgm;
- (void)onFadeOutTimer:(id)arg1;
- (void)onFadeInTimer:(id)arg1;
- (_Bool)isPlayingBgm;
- (void)setBgmCurrentTime:(double)arg1;
- (double)bgmDeviceCurrentTime;
- (double)bgmCurrentTime;
- (_Bool)onPauseBgm:(double)arg1;
- (_Bool)stopBgm:(double)arg1;
- (_Bool)playBgm:(double)arg1;
- (void)createBgmFadeOutTimer:(double)arg1;
- (void)createBgmFadeInTimer:(double)arg1;
- (void)deleteFadeTimer;
- (void)setSeVolume:(int)arg1 groupId:(int)arg2;
- (void)addInstance:(unsigned int)arg1 group:(int)arg2;
- (void)stopOldInstance;
- (int)orderInstanceList:(int)arg1;
- (void)orderInstanceList;
- (_Bool)stopAll;
- (_Bool)stopSeAll;
- (_Bool)offPauseSeAll;
- (_Bool)onPauseSeAll;
- (_Bool)isPlayingSe:(unsigned int)arg1;
- (_Bool)offPauseSe:(unsigned int)arg1;
- (_Bool)onPauseSe:(unsigned int)arg1;
- (_Bool)stopSe:(unsigned int)arg1;
- (unsigned int)playSeSetGroup:(id)arg1 resourceId:(int)arg2 groupId:(int)arg3;
- (unsigned int)playSe:(id)arg1 resourceId:(int)arg2 Volume:(int)arg3;
- (unsigned int)playSe:(id)arg1 resourceId:(int)arg2;
- (unsigned int)prepareSetGroup:(id)arg1 resourceId:(int)arg2 groupId:(int)arg3;
- (unsigned int)prepare:(id)arg1 resourceId:(int)arg2 volume:(int)arg3;
- (void)releaseVoice;
- (void)releaseBgm;
- (void)releaseSeAll;
- (void)releaseSe:(id)arg1 resourceId:(int)arg2;
- (int)loadSe:(id)arg1 isLoop:(_Bool)arg2 callName:(id)arg3 group:(int)arg4;
- (int)getGroupID:(id)arg1 resourceId:(int)arg2;
- (_Bool)loadVoiceData:(id)arg1 isLoop:(_Bool)arg2;
- (_Bool)loadBgmDataWithBytesNoCopy:(void *)arg1 length:(int)arg2 freeWhenDone:(_Bool)arg3 isLoop:(_Bool)arg4;
- (_Bool)loadBgmDataWithBytesNoCopy:(void *)arg1 length:(int)arg2 isLoop:(_Bool)arg3;
- (_Bool)loadBgmDataWithBytes:(const void *)arg1 length:(int)arg2 isLoop:(_Bool)arg3;
- (_Bool)loadBgmData:(id)arg1 isLoop:(_Bool)arg2;
- (void)initBgm:(_Bool)arg1;
- (void)onStartPlayer:(id)arg1;
- (void)systemTerminate;
- (void)systemStartBlock;
- (void)systemStart;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

