//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSData, NSString, StorePackInfo, UIImageView;

@interface BannerView : UIView
{
    _Bool _isSamplePlaying;
    _Bool _isRemoveWaiting;
    UIImageView *_imageView;
    StorePackInfo *_packInfo;
    NSData *_sampleData;
    NSString *_musicName;
}

@property(nonatomic) _Bool isRemoveWaiting; // @synthesize isRemoveWaiting=_isRemoveWaiting;
@property(nonatomic) _Bool isSamplePlaying; // @synthesize isSamplePlaying=_isSamplePlaying;
@property(retain, nonatomic) NSString *musicName; // @synthesize musicName=_musicName;
@property(retain, nonatomic) NSData *sampleData; // @synthesize sampleData=_sampleData;
@property(retain, nonatomic) StorePackInfo *packInfo; // @synthesize packInfo=_packInfo;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (_Bool)getIsSamplePlaying;
- (void)stopSamplePlay;
- (void)startSamplePlay;
- (void)setCornerRadius:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

