//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BFCodec : NSObject
{
    unsigned char _iv[8];
    struct C_BLOWFISH *_blf;
}

- (void)dealloc;
- (_Bool)decipher:(id)arg1;
- (unsigned long long)encipher:(id)arg1;
- (void)cipherInit:(id)arg1;
- (void)cipherInit:(const char *)arg1 keyLength:(unsigned long long)arg2;
- (id)init;

@end

