//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct AVComponent;

struct AVSource {
    id _field1;
    id _field2;
    _Bool _field3;
};

struct AudioBuffer {
    unsigned int _field1;
    unsigned int _field2;
    void *_field3;
};

struct AudioBufferList {
    unsigned int _field1;
    struct AudioBuffer _field2[1];
};

struct AudioStreamBasicDescription {
    double mSampleRate;
    unsigned int mFormatID;
    unsigned int mFormatFlags;
    unsigned int mBytesPerPacket;
    unsigned int mFramesPerPacket;
    unsigned int mBytesPerFrame;
    unsigned int mChannelsPerFrame;
    unsigned int mBitsPerChannel;
    unsigned int mReserved;
};

struct CAComponent;

struct CAPlayer {
    struct CAComponent *_field1;
    id _field2;
    struct CASource **_field3;
    int _field4;
};

struct CASource;

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct C_BLOWFISH {
    unsigned long long _field1[18];
    unsigned long long _field2[4][256];
};

struct C_TEXTURE {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    struct C_TEXTURE *_field3;
    struct C_TEXTURE *_field4;
    char *_field5;
    char *_field6;
    unsigned int _field7;
    int _field8;
    int _field9;
    int _field10;
    int _field11;
    int _field12;
    int _field13[4];
    int _field14;
    float _field15;
    _Bool _field16;
};

struct C_TIME {
    double m_Time;
};

struct GIKPopoverExtents {
    double left;
    double right;
    double top;
    double bottom;
};

struct SAVPlayer {
    struct AVComponent *_field1;
    id _field2;
    struct AVSource **_field3;
    int _field4;
};

struct S_VECTOR2 {
    union {
        struct {
            float m_X;
            float m_Y;
        } ;
        float m[2];
    } ;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct _SE_MANAGE_ID_ {
    unsigned int instanceId;
    int busId;
    int group;
};

struct in_addr {
    unsigned int _field1;
};

struct neIGLES {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    int _field6;
    int _field7;
    int _field8;
    int _field9;
    int _field10;
    int _field11;
    int _field12;
    int _field13;
    float _field14;
    _Bool _field15;
    int _field16;
    int _field17;
    void *_field18;
    int _field19;
    int _field20;
    void *_field21;
    int _field22;
    int _field23;
    void *_field24;
    int _field25;
    int _field26;
    int _field27;
    int _field28;
    void *_field29[8];
    int _field30[8];
    int _field31[8];
    void *_field32;
    int _field33;
    int _field34;
    int _field35;
    void *_field36;
    int _field37;
    int _field38;
    int _field39;
    int _field40;
    int _field41;
    int _field42[8];
    int _field43[8][4];
    int _field44;
    int _field45;
    int _field46;
    int _field47;
    _Bool _field48[36];
    _Bool _field49[7];
    float _field50;
    float _field51;
    float _field52;
    float _field53;
    float _field54[4];
    int _field55[5];
    int _field56;
    int _field57;
    int _field58;
    _Bool _field59;
    int _field60;
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct tm_unz_s {
    unsigned int tm_sec;
    unsigned int tm_min;
    unsigned int tm_hour;
    unsigned int tm_mday;
    unsigned int tm_mon;
    unsigned int tm_year;
};

struct tm_zip_s {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
};

struct unz_file_info_s {
    unsigned long long version;
    unsigned long long version_needed;
    unsigned long long flag;
    unsigned long long compression_method;
    unsigned long long dosDate;
    unsigned long long crc;
    unsigned long long compressed_size;
    unsigned long long uncompressed_size;
    unsigned long long size_filename;
    unsigned long long size_file_extra;
    unsigned long long size_file_comment;
    unsigned long long disk_num_start;
    unsigned long long internal_fa;
    unsigned long long external_fa;
    struct tm_unz_s tmu_date;
};

struct unz_global_info_s {
    unsigned long long number_entry;
    unsigned long long size_comment;
};

#pragma mark Typedef'd Structures

typedef struct {
    long long _field1;
    void *_field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    CDUnknownFunctionPointerType _field5;
} CDStruct_e097db04;

typedef struct {
    CDStruct_2c43369c center;
    struct {
        double latitudeDelta;
        double longitudeDelta;
    } span;
} CDStruct_feeb6407;

typedef struct {
    struct tm_zip_s _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long _field4;
} CDStruct_192a48cb;

// Ambiguous groups
typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

typedef struct {
    double latitude;
    double longitude;
} CDStruct_2c43369c;

