//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class Downloader;

@protocol DownloaderDelegate <NSObject>

@optional
- (void)downloaderError:(Downloader *)arg1;
- (void)downloaderProceed:(Downloader *)arg1;
- (void)downloaderFinished:(Downloader *)arg1;
@end

