//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSDate, NSNumber;

@interface History : NSManagedObject
{
}

+ (_Bool)getFullCombo:(id)arg1;
+ (float)getAR:(id)arg1;
+ (_Bool)checkScore:(id)arg1;
+ (id)hashScore:(id)arg1;
+ (void)hashScoreforTune:(int)arg1 Difficulty:(int)arg2 Score:(int)arg3 Just:(int)arg4 Great:(int)arg5 Good:(int)arg6 Miss:(int)arg7 JR:(int)arg8 Combo:(int)arg9 Date:(double)arg10 Count:(long long)arg11 Hash:(char *)arg12;
+ (void)reset:(id)arg1;
+ (id)recordWithTuneID:(unsigned int)arg1 Difficulty:(unsigned int)arg2 inManagedObjectContext:(id)arg3;
+ (long long)count:(id)arg1;
+ (void)deleteObject:(id)arg1;
+ (id)getScoreDataWithStartDate:(id)arg1 andEndDate:(id)arg2 andLimit:(unsigned int)arg3 inManagedObjectContext:(id)arg4;
+ (id)getScoreData:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)getScoreData:(unsigned int)arg1 Difficulty:(unsigned int)arg2 inManagedObjectContext:(id)arg3;

// Remaining properties
@property(retain, nonatomic) NSData *chksco; // @dynamic chksco;
@property(retain, nonatomic) NSNumber *cntCom; // @dynamic cntCom;
@property(retain, nonatomic) NSNumber *cntGood; // @dynamic cntGood;
@property(retain, nonatomic) NSNumber *cntGreat; // @dynamic cntGreat;
@property(retain, nonatomic) NSNumber *cntJR; // @dynamic cntJR;
@property(retain, nonatomic) NSNumber *cntJust; // @dynamic cntJust;
@property(retain, nonatomic) NSNumber *cntMiss; // @dynamic cntMiss;
@property(retain, nonatomic) NSNumber *diff; // @dynamic diff;
@property(retain, nonatomic) NSNumber *pc; // @dynamic pc;
@property(retain, nonatomic) NSDate *playDate; // @dynamic playDate;
@property(retain, nonatomic) NSNumber *score; // @dynamic score;
@property(retain, nonatomic) NSNumber *tuneID; // @dynamic tuneID;

@end

