//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSDate, NSNumber;

@interface HistoryData : NSObject
{
    float _ar;
    NSData *_chksco;
    NSNumber *_score;
    NSNumber *_cntCom;
    NSNumber *_cntGood;
    NSNumber *_cntGreat;
    NSNumber *_cntJR;
    NSNumber *_cntJust;
    NSNumber *_cntMiss;
    NSNumber *_diff;
    NSDate *_playDate;
    NSNumber *_pc;
    NSNumber *_tuneID;
}

+ (id)convertLocalDate:(id)arg1;
@property(retain, nonatomic) NSNumber *tuneID; // @synthesize tuneID=_tuneID;
@property(retain, nonatomic) NSNumber *pc; // @synthesize pc=_pc;
@property(retain, nonatomic) NSDate *playDate; // @synthesize playDate=_playDate;
@property(retain, nonatomic) NSNumber *diff; // @synthesize diff=_diff;
@property(nonatomic) float ar; // @synthesize ar=_ar;
@property(retain, nonatomic) NSNumber *cntMiss; // @synthesize cntMiss=_cntMiss;
@property(retain, nonatomic) NSNumber *cntJust; // @synthesize cntJust=_cntJust;
@property(retain, nonatomic) NSNumber *cntJR; // @synthesize cntJR=_cntJR;
@property(retain, nonatomic) NSNumber *cntGreat; // @synthesize cntGreat=_cntGreat;
@property(retain, nonatomic) NSNumber *cntGood; // @synthesize cntGood=_cntGood;
@property(retain, nonatomic) NSNumber *cntCom; // @synthesize cntCom=_cntCom;
@property(retain, nonatomic) NSNumber *score; // @synthesize score=_score;
@property(retain, nonatomic) NSData *chksco; // @synthesize chksco=_chksco;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;

@end

