//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSIndexPath, NSMutableData, NSString, NSURLConnection, UIImage;
@protocol ImageDownloaderDelegate;

@interface ImageDownloader : NSObject
{
    _Bool _unUseRetina;
    NSString *_imageURL;
    NSIndexPath *_indexPathInTableView;
    id <ImageDownloaderDelegate> _delegate;
    NSMutableData *_activeDownload;
    NSURLConnection *_imageConnection;
    NSURLConnection *_imageConnectionRetina;
    UIImage *_downloadedImage;
}

@property(retain, nonatomic) UIImage *downloadedImage; // @synthesize downloadedImage=_downloadedImage;
@property(retain, nonatomic) NSURLConnection *imageConnectionRetina; // @synthesize imageConnectionRetina=_imageConnectionRetina;
@property(retain, nonatomic) NSURLConnection *imageConnection; // @synthesize imageConnection=_imageConnection;
@property(retain, nonatomic) NSMutableData *activeDownload; // @synthesize activeDownload=_activeDownload;
@property(nonatomic) __weak id <ImageDownloaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSIndexPath *indexPathInTableView; // @synthesize indexPathInTableView=_indexPathInTableView;
@property(retain, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
@property(nonatomic) _Bool unUseRetina; // @synthesize unUseRetina=_unUseRetina;
- (void).cxx_destruct;
- (void)dealloc;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)getImage;
- (void)cancelDownload;
- (void)startDownload;

@end

