//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSString, UIImage;

@interface MusicData : NSObject
{
    int _MusicID;
    int _difficultyBasic;
    int _difficultyMedium;
    int _difficultyHard;
    int _bpm_MIN;
    int _bpm_MAX;
    int _decodeType;
    NSString *_musicName;
    NSString *_musicNameHira;
    NSString *_musicNameRoman;
    NSString *_artistName;
    NSString *_artistNameHira;
    NSString *_artistNameRoman;
    NSString *_musicSortName;
    NSString *_artistSortName;
    NSString *_musicNameInitial;
    NSString *_artistNameInitial;
    UIImage *_artworkCache;
    NSString *_filePath;
}

+ (id)dataWithPath:(id)arg1 ID:(int)arg2;
+ (id)getZipData:(id)arg1 Path:(id)arg2 DecodeType:(int)arg3;
+ (id)decodeBF:(id)arg1 Key:(const char *)arg2 KeyLength:(int)arg3;
+ (id)GetYomiString:(int)arg1;
+ (int)GetYomiIndex:(id)arg1;
@property(nonatomic) int decodeType; // @synthesize decodeType=_decodeType;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain) UIImage *artworkCache; // @synthesize artworkCache=_artworkCache;
@property(retain, nonatomic) NSString *artistNameInitial; // @synthesize artistNameInitial=_artistNameInitial;
@property(retain, nonatomic) NSString *musicNameInitial; // @synthesize musicNameInitial=_musicNameInitial;
@property(retain, nonatomic) NSString *artistSortName; // @synthesize artistSortName=_artistSortName;
@property(retain, nonatomic) NSString *musicSortName; // @synthesize musicSortName=_musicSortName;
@property(retain, nonatomic) NSString *artistNameRoman; // @synthesize artistNameRoman=_artistNameRoman;
@property(retain, nonatomic) NSString *artistNameHira; // @synthesize artistNameHira=_artistNameHira;
@property(retain, nonatomic) NSString *artistName; // @synthesize artistName=_artistName;
@property(retain, nonatomic) NSString *musicNameRoman; // @synthesize musicNameRoman=_musicNameRoman;
@property(retain, nonatomic) NSString *musicNameHira; // @synthesize musicNameHira=_musicNameHira;
@property(retain, nonatomic) NSString *musicName; // @synthesize musicName=_musicName;
@property(nonatomic) int bpm_MAX; // @synthesize bpm_MAX=_bpm_MAX;
@property(nonatomic) int bpm_MIN; // @synthesize bpm_MIN=_bpm_MIN;
@property(nonatomic) int difficultyHard; // @synthesize difficultyHard=_difficultyHard;
@property(nonatomic) int difficultyMedium; // @synthesize difficultyMedium=_difficultyMedium;
@property(nonatomic) int difficultyBasic; // @synthesize difficultyBasic=_difficultyBasic;
@property(nonatomic) int MusicID; // @synthesize MusicID=_MusicID;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isArtworkCache;
- (long long)compareDifficultyHard:(id)arg1;
- (long long)compareDifficultyMedium:(id)arg1;
- (long long)compareDifficultyBasic:(id)arg1;
- (long long)compareArtistNameHira:(id)arg1;
- (long long)compareMusicNameHira:(id)arg1;
- (long long)compareArtistNameCustom:(id)arg1;
- (long long)compareMusicNameCustom:(id)arg1;
- (long long)compareMusicID:(id)arg1;
- (long long)compare:(id)arg1;
- (void)releaseChache;
- (void)createCache;
- (id)setColor:(id)arg1 withColor:(id)arg2;
@property(readonly, nonatomic) UIImage *artistNameImageBrown2x;
@property(readonly, nonatomic) UIImage *musicNameImageBrown2x;
@property(readonly, nonatomic) UIImage *artistNameImageBlack2x;
@property(readonly, nonatomic) UIImage *musicNameImageBlack2x;
@property(readonly, nonatomic) UIImage *artistNameImageWhite2x;
@property(readonly, nonatomic) UIImage *musicNameImageWhite2x;
@property(readonly, nonatomic) UIImage *artwork2x;
@property(readonly, nonatomic) UIImage *artistNameImageBrown;
@property(readonly, nonatomic) UIImage *musicNameImageBrown;
@property(readonly, nonatomic) UIImage *artistNameImageBlack;
@property(readonly, nonatomic) UIImage *musicNameImageBlack;
@property(readonly, nonatomic) UIImage *artistNameImageWhite;
@property(readonly, nonatomic) UIImage *musicNameImageWhite;
@property(readonly, nonatomic) UIImage *artwork;
- (id)artistNameImageBrown2xData;
- (id)musicNameImageBrown2xData;
@property(readonly, nonatomic) NSData *artistNameImageBlack2xData;
@property(readonly, nonatomic) NSData *musicNameImageBlack2xData;
@property(readonly, nonatomic) NSData *artistNameImageWhite2xData;
@property(readonly, nonatomic) NSData *musicNameImageWhite2xData;
@property(readonly, nonatomic) NSData *artwork2xData;
@property(readonly, nonatomic) NSData *artistNameImageBlackData;
@property(readonly, nonatomic) NSData *musicNameImageBlackData;
@property(readonly, nonatomic) NSData *artistNameImageWhiteData;
@property(readonly, nonatomic) NSData *musicNameImageWhiteData;
@property(readonly, nonatomic) NSData *artworkData;
@property(readonly, nonatomic) NSData *sheetHard;
@property(readonly, nonatomic) NSData *sheetMedium;
@property(readonly, nonatomic) NSData *sheetBasic;
@property(readonly, nonatomic) NSData *musicPre;
@property(readonly, nonatomic) NSData *music;
- (id)getZipData:(id)arg1;
- (void)dealloc;

@end

