//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MusicData.h"

@class NSString;

@interface MusicDataFromDoc : MusicData
{
    NSString *_plyName;
}

+ (id)dataWithPath:(id)arg1 PlyName:(id)arg2;
+ (id)getPathWithDocument:(id)arg1;
@property(retain, nonatomic) NSString *plyName; // @synthesize plyName=_plyName;
- (void).cxx_destruct;
- (id)artistNameImageDataWithScale:(float)arg1 Luminance:(float)arg2;
- (id)artistNameImageBlackData;
- (id)artistNameImageBlack2xData;
- (id)artistNameImageWhiteData;
- (id)artistNameImageWhite2xData;
- (id)musicNameImageDataWithScale:(float)arg1 Luminance:(float)arg2;
- (id)musicNameImageBlackData;
- (id)musicNameImageBlack2xData;
- (id)musicNameImageWhiteData;
- (id)musicNameImageWhite2xData;
- (id)artworkDataWithScale:(float)arg1 Luminance:(float)arg2;
- (id)artworkData;
- (id)artwork2xData;
- (id)sheetHard;
- (id)sheetMedium;
- (id)sheetBasic;
- (id)musicPre;
- (id)music;
- (id)artistNameRoman;
- (id)artistNameHira;
- (id)artistName;
- (id)musicNameRoman;
- (id)musicNameHira;
- (int)bpm_MAX;
- (int)bpm_MIN;
- (int)difficultyHard;
- (int)difficultyMedium;
- (int)difficultyBasic;
- (int)MusicID;
- (void)dealloc;
- (id)init;

@end

