//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (RB)
+ (id)resourcePath;
+ (id)temporaryDirectoryPath;
+ (id)cachesDirectoryPath;
+ (id)applicationSupportDirectoryPath;
+ (id)documentDirectoryPath;
+ (id)paddingDirName;
+ (_Bool)createDirectorysAtPath:(id)arg1;
+ (unsigned long long)freeFileSystemSize;
+ (_Bool)isFreeSystemSize;
+ (_Bool)createDirectory:(id)arg1;
+ (_Bool)isDirectoryExist:(id)arg1;
+ (_Bool)isFileExist:(id)arg1;
@end

