//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSDate, NSString;

@interface PurchaseTransactionCache : NSObject
{
    NSString *_productID;
    NSData *_receiptData;
    NSString *_transactionID;
    NSDate *_transactionDate;
    NSString *_digestString;
}

@property(retain, nonatomic) NSString *digestString; // @synthesize digestString=_digestString;
@property(retain, nonatomic) NSDate *transactionDate; // @synthesize transactionDate=_transactionDate;
@property(retain, nonatomic) NSString *transactionID; // @synthesize transactionID=_transactionID;
@property(retain, nonatomic) NSData *receiptData; // @synthesize receiptData=_receiptData;
@property(retain, nonatomic) NSString *productID; // @synthesize productID=_productID;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithTransaction:(id)arg1;

@end

