//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@interface RBBonusData : NSObject <NSCoding>
{
    float _clearBonus;
    float _fullComboBonus;
    float _miss1Bonus;
    float _miss2Bonus;
    float _rankAAAPBonus;
    float _rankAAABonus;
    float _rankAABonus;
    float _rankABonus;
    float _rankBBonus;
    float _firstPlayBonus;
    float _blackPastelBonus;
    float _pastelBonus;
    float _earlyPlayBonus;
    float _hotMusicBonus;
}

+ (id)sharedInstance;
@property(nonatomic) float hotMusicBonus; // @synthesize hotMusicBonus=_hotMusicBonus;
@property(nonatomic) float earlyPlayBonus; // @synthesize earlyPlayBonus=_earlyPlayBonus;
@property(nonatomic) float pastelBonus; // @synthesize pastelBonus=_pastelBonus;
@property(nonatomic) float blackPastelBonus; // @synthesize blackPastelBonus=_blackPastelBonus;
@property(nonatomic) float firstPlayBonus; // @synthesize firstPlayBonus=_firstPlayBonus;
@property(nonatomic) float rankBBonus; // @synthesize rankBBonus=_rankBBonus;
@property(nonatomic) float rankABonus; // @synthesize rankABonus=_rankABonus;
@property(nonatomic) float rankAABonus; // @synthesize rankAABonus=_rankAABonus;
@property(nonatomic) float rankAAABonus; // @synthesize rankAAABonus=_rankAAABonus;
@property(nonatomic) float rankAAAPBonus; // @synthesize rankAAAPBonus=_rankAAAPBonus;
@property(nonatomic) float miss2Bonus; // @synthesize miss2Bonus=_miss2Bonus;
@property(nonatomic) float miss1Bonus; // @synthesize miss1Bonus=_miss1Bonus;
@property(nonatomic) float fullComboBonus; // @synthesize fullComboBonus=_fullComboBonus;
@property(nonatomic) float clearBonus; // @synthesize clearBonus=_clearBonus;
- (void)save;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

