//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@protocol RBCollectionViewDelegate;

@interface RBCollectionView : UICollectionView
{
    id <RBCollectionViewDelegate> _customDelegate;
}

@property(nonatomic) __weak id <RBCollectionViewDelegate> customDelegate; // @synthesize customDelegate=_customDelegate;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;

@end

