//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator;

@interface RBCoreDataManager : NSObject
{
    NSManagedObjectContext *_managedObjectContext;
    NSManagedObjectModel *_managedObjectModel;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    NSManagedObjectContext *_historyContext;
    NSManagedObjectModel *_historyModel;
    NSPersistentStoreCoordinator *_historyCoordinator;
}

+ (id)scoreDataFileName;
+ (id)sharedInstance;
@property(retain, nonatomic) NSPersistentStoreCoordinator *historyCoordinator; // @synthesize historyCoordinator=_historyCoordinator;
@property(retain, nonatomic) NSManagedObjectModel *historyModel; // @synthesize historyModel=_historyModel;
@property(retain, nonatomic) NSManagedObjectContext *historyContext; // @synthesize historyContext=_historyContext;
@property(retain, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=_persistentStoreCoordinator;
@property(retain, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=_managedObjectModel;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
- (void).cxx_destruct;

@end

