//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBMusicMenuPopupView.h"

@class RBSettingView;

@interface RBCreditsView : RBMusicMenuPopupView
{
    RBSettingView *_settingView;
}

@property(nonatomic) __weak RBSettingView *settingView; // @synthesize settingView=_settingView;
- (void).cxx_destruct;
- (void)setupView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

