//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "RBCollectionViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSMutableArray, NSString, RBCollectionView, StyledPageControl, UIImageView;

@interface RBCustomSelectCollectionView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, RBCollectionViewDelegate>
{
    int _customizeType;
    UIImageView *_backgroundView;
    RBCollectionView *_collectionView;
    StyledPageControl *_pageControl;
    NSMutableArray *_items;
}

@property(nonatomic) int customizeType; // @synthesize customizeType=_customizeType;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) StyledPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) RBCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (void)didLayoutSubviews:(id)arg1;
- (void)reloadData;
- (void)sliderChanged:(id)arg1;
- (void)noteSizeTap:(id)arg1;
- (void)gaugeStyleTap:(id)arg1;
- (void)setupView;
- (id)initWithFrame:(struct CGRect)arg1 customizeType:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

