//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBMusicMenuPopupView.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, RBCustomSelectView, RBRewardListView, RBSettingView, RBUnlockView, UIButton, UIImageView;

@interface RBCustomView : RBMusicMenuPopupView <UIScrollViewDelegate>
{
    _Bool _firstInfo;
    RBSettingView *_settingView;
    RBCustomSelectView *_customizeItemView;
    RBUnlockView *_experienceItemView;
    UIButton *_experienceButton;
    UIButton *_experienceSetButton;
    UIButton *_experienceUnlockButton;
    UIImageView *_experienceButtonEffectView;
    UIImageView *_experienceButtonFrameView;
    RBRewardListView *_rewardListView;
}

@property(retain, nonatomic) RBRewardListView *rewardListView; // @synthesize rewardListView=_rewardListView;
@property(nonatomic) _Bool firstInfo; // @synthesize firstInfo=_firstInfo;
@property(retain, nonatomic) UIImageView *experienceButtonFrameView; // @synthesize experienceButtonFrameView=_experienceButtonFrameView;
@property(retain, nonatomic) UIImageView *experienceButtonEffectView; // @synthesize experienceButtonEffectView=_experienceButtonEffectView;
@property(retain, nonatomic) UIButton *experienceUnlockButton; // @synthesize experienceUnlockButton=_experienceUnlockButton;
@property(retain, nonatomic) UIButton *experienceSetButton; // @synthesize experienceSetButton=_experienceSetButton;
@property(retain, nonatomic) UIButton *experienceButton; // @synthesize experienceButton=_experienceButton;
@property(retain, nonatomic) RBUnlockView *experienceItemView; // @synthesize experienceItemView=_experienceItemView;
@property(retain, nonatomic) RBCustomSelectView *customizeItemView; // @synthesize customizeItemView=_customizeItemView;
@property(nonatomic) __weak RBSettingView *settingView; // @synthesize settingView=_settingView;
- (void).cxx_destruct;
- (id)getCustomizeItemView;
- (id)getCustomButtonView;
- (id)getUnlockButtonView;
- (void)hideAnimation;
- (void)hideRewardList;
- (void)toRewardList:(id)arg1;
- (void)toCustomize:(id)arg1;
- (void)toUnlock:(id)arg1;
- (void)showAnimation;
- (void)setupView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

