//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "MKAnnotation-Protocol.h"

@class NSString;

@interface RBMapAnnotation : NSObject <MKAnnotation>
{
    NSString *_modelName;
    NSString *_title;
    NSString *_subtitle;
    CDStruct_2c43369c _coordinate;
}

@property(nonatomic) CDStruct_c3b9c2ee coordinate; // @synthesize coordinate=_coordinate;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *modelName; // @synthesize modelName=_modelName;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithCoordinate:(CDStruct_c3b9c2ee)arg1 Title:(id)arg2 SubTitle:(id)arg3 Model:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

