//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UIImageView;

@interface RBMenuPastelkun : UIView
{
    _Bool _isAnimation;
    float _limitX;
    int _pastelType;
    float _speedX;
    float _speedY;
    float _accellY;
    float _baseY;
    float _pastelScale;
    NSMutableArray *_pastelImageArray;
    UIImageView *_pastelImage;
    struct S_VECTOR2 _m_screenSize;
}

@property(nonatomic) float pastelScale; // @synthesize pastelScale=_pastelScale;
@property(nonatomic) struct S_VECTOR2 m_screenSize; // @synthesize m_screenSize=_m_screenSize;
@property(nonatomic) _Bool isAnimation; // @synthesize isAnimation=_isAnimation;
@property(nonatomic) float baseY; // @synthesize baseY=_baseY;
@property(nonatomic) float accellY; // @synthesize accellY=_accellY;
@property(nonatomic) float speedY; // @synthesize speedY=_speedY;
@property(nonatomic) float speedX; // @synthesize speedX=_speedX;
@property(nonatomic) int pastelType; // @synthesize pastelType=_pastelType;
@property(retain, nonatomic) UIImageView *pastelImage; // @synthesize pastelImage=_pastelImage;
@property(retain, nonatomic) NSMutableArray *pastelImageArray; // @synthesize pastelImageArray=_pastelImageArray;
@property float limitX; // @synthesize limitX=_limitX;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CGPoint)getMovePoint;
- (void)onTapped:(id)arg1;
- (void)update;
- (void)stopAnimation;
- (void)startAnimation:(id)arg1;
- (void)setup:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

