//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImage, UIImageView;

@interface RBMenuBGEffectPartView : UIView
{
    _Bool _isAnimation;
    _Bool _isAnimationEnableLoop;
    NSString *_image1Path;
    NSString *_image2Path;
    NSString *_image3Path;
    UIImageView *_effect;
    UIImage *_image1;
    UIImage *_image2;
    UIImage *_image3;
    struct S_VECTOR2 _m_screenSize;
}

@property(nonatomic) struct S_VECTOR2 m_screenSize; // @synthesize m_screenSize=_m_screenSize;
@property(nonatomic) _Bool isAnimationEnableLoop; // @synthesize isAnimationEnableLoop=_isAnimationEnableLoop;
@property(nonatomic) _Bool isAnimation; // @synthesize isAnimation=_isAnimation;
@property(retain, nonatomic) UIImage *image3; // @synthesize image3=_image3;
@property(retain, nonatomic) UIImage *image2; // @synthesize image2=_image2;
@property(retain, nonatomic) UIImage *image1; // @synthesize image1=_image1;
@property(retain, nonatomic) UIImageView *effect; // @synthesize effect=_effect;
@property(retain, nonatomic) NSString *image3Path; // @synthesize image3Path=_image3Path;
@property(retain, nonatomic) NSString *image2Path; // @synthesize image2Path=_image2Path;
@property(retain, nonatomic) NSString *image1Path; // @synthesize image1Path=_image1Path;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)removeFromSuperview;
- (void)stopAnimation;
- (void)setAnimationLoopFlag:(_Bool)arg1;
- (void)startAnimation;
- (void)setupView;
- (id)init;

@end

