//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, NSString;

@interface RBMenuBGEffectView : UIView
{
    int _EFFECT_NUM;
    NSString *_rainbowImageBasePath;
    NSString *_ringImageBasePath;
    NSMutableArray *_effList;
    NSMutableArray *_animImageList;
}

@property(retain, nonatomic) NSMutableArray *animImageList; // @synthesize animImageList=_animImageList;
@property(retain, nonatomic) NSMutableArray *effList; // @synthesize effList=_effList;
@property(nonatomic) int EFFECT_NUM; // @synthesize EFFECT_NUM=_EFFECT_NUM;
@property(retain, nonatomic) NSString *ringImageBasePath; // @synthesize ringImageBasePath=_ringImageBasePath;
@property(retain, nonatomic) NSString *rainbowImageBasePath; // @synthesize rainbowImageBasePath=_rainbowImageBasePath;
- (void).cxx_destruct;
- (void)setupParticle;
- (void)setupRainbow;
- (void)removeFromSuperview;
- (void)stopAnimation;
- (void)startAnimation;
- (void)createAnimation:(id)arg1 type:(int)arg2;
- (void)setupView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

