//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class CALayer, MusicData, NSArray, RBMenuView, UIButton, UIImageView, UILabel;

@interface RBMusicCell : UICollectionViewCell
{
    int m_RankType[3];
    int m_ClearType[3];
    int _bgType;
    RBMenuView *_menuView;
    MusicData *_musicData;
    UIImageView *_artworkImageView;
    UILabel *_titleLabel;
    UILabel *_artistLabel;
    UIButton *_addButton;
    UIButton *_removeButton;
    CALayer *_bgImageLayer;
    NSArray *_rankBaseImageLayers;
    NSArray *_rankImageLayers;
    NSArray *_clearBaseImageLayers;
    NSArray *_clearImageLayers;
}

@property(nonatomic) int bgType; // @synthesize bgType=_bgType;
@property(retain, nonatomic) NSArray *clearImageLayers; // @synthesize clearImageLayers=_clearImageLayers;
@property(retain, nonatomic) NSArray *clearBaseImageLayers; // @synthesize clearBaseImageLayers=_clearBaseImageLayers;
@property(retain, nonatomic) NSArray *rankImageLayers; // @synthesize rankImageLayers=_rankImageLayers;
@property(retain, nonatomic) NSArray *rankBaseImageLayers; // @synthesize rankBaseImageLayers=_rankBaseImageLayers;
@property(retain, nonatomic) CALayer *bgImageLayer; // @synthesize bgImageLayer=_bgImageLayer;
@property(retain, nonatomic) UIButton *removeButton; // @synthesize removeButton=_removeButton;
@property(retain, nonatomic) UIButton *addButton; // @synthesize addButton=_addButton;
@property(retain, nonatomic) UILabel *artistLabel; // @synthesize artistLabel=_artistLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *artworkImageView; // @synthesize artworkImageView=_artworkImageView;
@property(retain, nonatomic) MusicData *musicData; // @synthesize musicData=_musicData;
@property(nonatomic) __weak RBMenuView *menuView; // @synthesize menuView=_menuView;
- (void).cxx_destruct;
- (void)updateScoreData:(id)arg1;
- (void)SetupView;
- (void)prepareForReuse;
- (void)removePlaylist:(id)arg1;
- (void)addPlaylist:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

