//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, RBMusicView;

@interface RBMusicDifficultyView : UIView
{
    int _difficulty;
    float _layoutOffset;
    RBMusicView *_musicSelectedBase;
    NSMutableArray *_difficultySelectedImages;
    NSMutableArray *_difficultyNumberImages;
    NSMutableArray *_difficultyButtons;
}

@property(nonatomic) float layoutOffset; // @synthesize layoutOffset=_layoutOffset;
@property(retain, nonatomic) NSMutableArray *difficultyButtons; // @synthesize difficultyButtons=_difficultyButtons;
@property(retain, nonatomic) NSMutableArray *difficultyNumberImages; // @synthesize difficultyNumberImages=_difficultyNumberImages;
@property(retain, nonatomic) NSMutableArray *difficultySelectedImages; // @synthesize difficultySelectedImages=_difficultySelectedImages;
@property(nonatomic) __weak RBMusicView *musicSelectedBase; // @synthesize musicSelectedBase=_musicSelectedBase;
@property(nonatomic) int difficulty; // @synthesize difficulty=_difficulty;
- (void).cxx_destruct;
- (id)getDifficultyButton:(int)arg1;
- (void)setEnableButton:(_Bool)arg1;
- (void)SelectDifficultyButton:(id)arg1;
- (void)SetFlashEffectDuration:(float)arg1 Start:(float)arg2 End:(float)arg3;
- (void)ShowSelectDifficulty;
- (void)CreateButton:(int)arg1 Position:(struct CGPoint)arg2 Number:(int)arg3;
- (void)SetupView;
- (id)initWithFrame:(struct CGRect)arg1 MusicSelectedBase:(id)arg2;

@end

