//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class MusicData, NSMutableArray, NSString, RBMenuView, RBMusicARView, RBMusicCPUView, RBMusicColorView, RBMusicDifficultyView, RBMusicHistoryView, RBMusicScoreView, StyledPageControl, UIButton, UIImage, UIImageView, UIScrollView;

@interface RBMusicView : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    int m_GameType;
    int m_SelectedSetting;
    int m_Score[3];
    float m_AR[3];
    int m_Rank[3];
    _Bool m_FullCombo[3];
    int m_PlayCount[3];
    _Bool m_Animating;
    _Bool m_FirstInfo;
    int _thema;
    _Bool _isRandom;
    RBMenuView *_musicMenuView;
    MusicData *_musicData;
    UIButton *_randomButton;
    UIButton *_historyButton;
    UIView *_baseView;
    UIImageView *_bgImageView;
    UIImageView *_firstInfoView;
    UIImage *_jacketImage;
    UIImageView *_musicNameImageView;
    UIImageView *_artistNameImageView;
    UIImageView *_jacketImageView;
    RBMusicScoreView *_scoreView;
    UIImageView *_fullComboView;
    UIImageView *_rankView;
    RBMusicARView *_arView;
    NSMutableArray *_settingButtons;
    NSMutableArray *_settingButtonEffects;
    NSMutableArray *_settingButtonCovers;
    RBMusicDifficultyView *_difficultyView;
    RBMusicColorView *_colorView;
    RBMusicCPUView *_cpuView;
    UIScrollView *_settingScroll;
    StyledPageControl *_settingPage;
    NSMutableArray *_settingTitleImages;
    NSString *_iTunesURL;
    UIView *_lineView;
    NSMutableArray *_lineAnimationLayers;
    UIImageView *_bpmImageView;
    UIButton *_decideButton;
    UIButton *_doubleButton;
    RBMusicHistoryView *_historyView;
    struct CGPoint _bpmOrigin;
}

@property(retain, nonatomic) RBMusicHistoryView *historyView; // @synthesize historyView=_historyView;
@property(retain, nonatomic) UIButton *doubleButton; // @synthesize doubleButton=_doubleButton;
@property(retain, nonatomic) UIButton *decideButton; // @synthesize decideButton=_decideButton;
@property(retain, nonatomic) UIImageView *bpmImageView; // @synthesize bpmImageView=_bpmImageView;
@property(nonatomic) struct CGPoint bpmOrigin; // @synthesize bpmOrigin=_bpmOrigin;
@property(retain, nonatomic) NSMutableArray *lineAnimationLayers; // @synthesize lineAnimationLayers=_lineAnimationLayers;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) NSString *iTunesURL; // @synthesize iTunesURL=_iTunesURL;
@property(retain, nonatomic) NSMutableArray *settingTitleImages; // @synthesize settingTitleImages=_settingTitleImages;
@property(retain, nonatomic) StyledPageControl *settingPage; // @synthesize settingPage=_settingPage;
@property(retain, nonatomic) UIScrollView *settingScroll; // @synthesize settingScroll=_settingScroll;
@property(retain, nonatomic) RBMusicCPUView *cpuView; // @synthesize cpuView=_cpuView;
@property(retain, nonatomic) RBMusicColorView *colorView; // @synthesize colorView=_colorView;
@property(retain, nonatomic) RBMusicDifficultyView *difficultyView; // @synthesize difficultyView=_difficultyView;
@property(retain, nonatomic) NSMutableArray *settingButtonCovers; // @synthesize settingButtonCovers=_settingButtonCovers;
@property(retain, nonatomic) NSMutableArray *settingButtonEffects; // @synthesize settingButtonEffects=_settingButtonEffects;
@property(retain, nonatomic) NSMutableArray *settingButtons; // @synthesize settingButtons=_settingButtons;
@property(retain, nonatomic) RBMusicARView *arView; // @synthesize arView=_arView;
@property(retain, nonatomic) UIImageView *rankView; // @synthesize rankView=_rankView;
@property(retain, nonatomic) UIImageView *fullComboView; // @synthesize fullComboView=_fullComboView;
@property(retain, nonatomic) RBMusicScoreView *scoreView; // @synthesize scoreView=_scoreView;
@property(retain, nonatomic) UIImageView *jacketImageView; // @synthesize jacketImageView=_jacketImageView;
@property(retain, nonatomic) UIImageView *artistNameImageView; // @synthesize artistNameImageView=_artistNameImageView;
@property(retain, nonatomic) UIImageView *musicNameImageView; // @synthesize musicNameImageView=_musicNameImageView;
@property(retain, nonatomic) UIImage *jacketImage; // @synthesize jacketImage=_jacketImage;
@property(retain, nonatomic) UIImageView *firstInfoView; // @synthesize firstInfoView=_firstInfoView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UIView *baseView; // @synthesize baseView=_baseView;
@property(retain, nonatomic) UIButton *historyButton; // @synthesize historyButton=_historyButton;
@property(retain, nonatomic) UIButton *randomButton; // @synthesize randomButton=_randomButton;
@property(nonatomic) _Bool isRandom; // @synthesize isRandom=_isRandom;
@property(retain, nonatomic) MusicData *musicData; // @synthesize musicData=_musicData;
@property(nonatomic) __weak RBMenuView *musicMenuView; // @synthesize musicMenuView=_musicMenuView;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)tapGesture:(id)arg1;
- (id)getDifficultyButton:(int)arg1;
- (id)getDoubleButton;
- (id)getDecideButton;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setEnableButton:(_Bool)arg1;
- (void)setScrollable:(_Bool)arg1;
- (void)setFirstScrollAnimation;
- (void)firstInfoScrollEnd;
- (void)selectPage:(id)arg1;
- (void)firstInfoAnimationCheck;
- (void)firstInfoAnimation;
- (void)ReplayMusic;
- (void)hideAnimation;
- (void)showAnimation:(_Bool)arg1;
- (void)SelectItunes;
- (void)playTutorialGame;
- (void)playGame;
- (void)SelectHistory;
- (void)SelectDecideButton;
- (void)SelectDoublePlayButton;
- (void)SetSettingButtonSelected:(int)arg1;
- (_Bool)ShowSettingView:(int)arg1;
- (void)ShowSelectDifficulty;
- (void)SetRankView:(int)arg1;
- (void)SetUpLineView;
- (void)SetupView;
- (void)setBpm:(int)arg1 Point:(struct CGPoint *)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 MusicData:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

