//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewLayout.h>

@class NSArray;

@interface RBMusicGridLayout : UICollectionViewLayout
{
    double _minimumLineSpacing;
    double _minimumInteritemSpacing;
    long long _rowCount;
    long long _colCount;
    long long _pageCount;
    long long _pageItemCount;
    long long _scrollDirection;
    NSArray *_pageRects;
    long long _itemCount;
    NSArray *_layouts;
    struct CGSize _itemSize;
    struct CGSize _pageSize;
    struct CGSize _contentSize;
    struct UIEdgeInsets _pageInset;
}

@property(retain, nonatomic) NSArray *layouts; // @synthesize layouts=_layouts;
@property(nonatomic) long long itemCount; // @synthesize itemCount=_itemCount;
@property(retain, nonatomic) NSArray *pageRects; // @synthesize pageRects=_pageRects;
@property(nonatomic) struct CGSize contentSize; // @synthesize contentSize=_contentSize;
@property(nonatomic) struct CGSize pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long scrollDirection; // @synthesize scrollDirection=_scrollDirection;
@property(nonatomic) long long pageItemCount; // @synthesize pageItemCount=_pageItemCount;
@property(nonatomic) long long pageCount; // @synthesize pageCount=_pageCount;
@property(nonatomic) long long colCount; // @synthesize colCount=_colCount;
@property(nonatomic) long long rowCount; // @synthesize rowCount=_rowCount;
@property(nonatomic) struct UIEdgeInsets pageInset; // @synthesize pageInset=_pageInset;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(nonatomic) double minimumInteritemSpacing; // @synthesize minimumInteritemSpacing=_minimumInteritemSpacing;
@property(nonatomic) double minimumLineSpacing; // @synthesize minimumLineSpacing=_minimumLineSpacing;
- (void).cxx_destruct;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (struct CGSize)collectionViewContentSize;
- (void)prepareLayout;
- (id)init;

@end

