//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@interface RBNumberLabel : UIControl
{
    float _number;
    long long _imageType;
}

@property(nonatomic) long long imageType; // @synthesize imageType=_imageType;
@property(nonatomic) float number; // @synthesize number=_number;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

