//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPopoverBackgroundView.h>

@class UIImageView;

@interface RBPopoverBackgroundView : UIPopoverBackgroundView
{
    double _arrowOffset;
    unsigned long long _arrowDirection;
    struct GIKPopoverExtents _popoverExtents;
    double _halfBase;
    double _arrowCenter;
    UIImageView *_popoverBackground;
}

+ (double)arrowBase;
+ (double)arrowHeight;
+ (struct UIEdgeInsets)contentViewInsets;
@property(retain, nonatomic) UIImageView *popoverBackground; // @synthesize popoverBackground=_popoverBackground;
@property(nonatomic) unsigned long long arrowDirection; // @synthesize arrowDirection=_arrowDirection;
@property(nonatomic) double arrowOffset; // @synthesize arrowOffset=_arrowOffset;
- (void).cxx_destruct;
- (id)imageFromImageContextWithSourceImage:(id)arg1 size:(struct CGSize)arg2;
- (struct UIEdgeInsets)mirroredInsets:(struct UIEdgeInsets)arg1;
- (id)mirroredImage:(id)arg1;
- (struct UIEdgeInsets)verticalInsetsForStretchedImage:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (struct UIEdgeInsets)horizontalInsetsForStretchedImage:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (struct UIEdgeInsets)secondHalfInsetsForStretchedImage:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (struct CGSize)contextSizeForFirstHalfImage:(id)arg1;
- (double)firstHalfStretchAmountForImage:(id)arg1;
- (id)twoPartStretchableImageNamed:(id)arg1 insets:(struct UIEdgeInsets)arg2;
- (id)stretchableImageNamed:(id)arg1 insets:(struct UIEdgeInsets)arg2 mirrored:(_Bool)arg3;
- (void)adjustCentersIfNecessary;
- (_Bool)isArrowAtBottomEdgeOfPopover;
- (_Bool)isArrowAtTopEdgeOfPopover;
- (_Bool)isArrowBetweenTopAndBottomEdgesOfPopover;
- (_Bool)isArrowAtRightEdgeOfPopover;
- (_Bool)isArrowAtLeftEdgeOfPopover;
- (_Bool)isArrowBetweenLeftAndRightEdgesOfPopover;
- (_Bool)wantsUpArrow;
- (_Bool)wantsUpOrDownArrow;
- (double)arrowCenter;
- (id)sideArrowImage;
- (id)upOrDownArrowImage;
- (struct CGPath *)shadowPath;
- (void)layoutSubviews;
- (void)addDropShadowIfNecessary;
- (void)addShadowPathAnimationIfNecessary:(struct CGPath *)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (double)halfArrowBase;

@end

