//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DownloaderDelegate-Protocol.h"
#import "SKPaymentTransactionObserver-Protocol.h"
#import "SKRequestDelegate-Protocol.h"

@class Downloader, NSMutableArray, NSString;
@protocol PurchaseManagerDelegate;

@interface RBPurchaseManager : NSObject <SKPaymentTransactionObserver, DownloaderDelegate, SKRequestDelegate>
{
    _Bool _transactioing;
    _Bool _isRestored;
    _Bool _iOS7Receipt;
    id <PurchaseManagerDelegate> _delegate;
    NSMutableArray *_purchasedProducts;
    NSMutableArray *_purchaseCheckTransactions;
    NSMutableArray *_purchaseCheckedProductsIn;
    NSMutableArray *_restoredTransactions;
    Downloader *_downloader;
    NSMutableArray *_productIds;
    NSString *_nonce;
}

+ (id)decodedStringWithBase64:(id)arg1;
+ (id)encodedStringWithBase64V2:(id)arg1;
+ (id)encodedStringWithBase64:(id)arg1;
+ (_Bool)isPurchasable;
+ (id)sharedManager;
@property(retain, nonatomic) NSString *nonce; // @synthesize nonce=_nonce;
@property(retain, nonatomic) NSMutableArray *productIds; // @synthesize productIds=_productIds;
@property(nonatomic) _Bool iOS7Receipt; // @synthesize iOS7Receipt=_iOS7Receipt;
@property(nonatomic) _Bool isRestored; // @synthesize isRestored=_isRestored;
@property(nonatomic) _Bool transactioing; // @synthesize transactioing=_transactioing;
@property(retain, nonatomic) Downloader *downloader; // @synthesize downloader=_downloader;
@property(retain, nonatomic) NSMutableArray *restoredTransactions; // @synthesize restoredTransactions=_restoredTransactions;
@property(retain, nonatomic) NSMutableArray *purchaseCheckedProductsIn; // @synthesize purchaseCheckedProductsIn=_purchaseCheckedProductsIn;
@property(retain, nonatomic) NSMutableArray *purchaseCheckTransactions; // @synthesize purchaseCheckTransactions=_purchaseCheckTransactions;
@property(retain, nonatomic) NSMutableArray *purchasedProducts; // @synthesize purchasedProducts=_purchasedProducts;
@property(nonatomic) __weak id <PurchaseManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)downloaderError:(id)arg1;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
- (void)paymentQueue:(id)arg1 removedTransactions:(id)arg2;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)requestDidFinish:(id)arg1;
- (_Bool)checkNextReceipt;
- (_Bool)addPurchaseCheckTransaction:(id)arg1;
- (void)addProductFromPurchaseCheckedProducts;
- (_Bool)addProductID:(id)arg1 Save:(_Bool)arg2;
- (void)clearPurchaseCheckedProducts;
- (void)removePurchaseCheckedProduct:(id)arg1;
- (id)purchaseCheckedProducts;
- (_Bool)beginRestore;
- (_Bool)beginPurchase:(id)arg1;
- (_Bool)isPurchased:(id)arg1;
- (void)loadProductList;
- (void)saveProductList;
- (void)end;
- (void)start;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

