//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ApplilinkViewDelegate-Protocol.h"

@class NSString, RBCustomView, UIActivityIndicatorView, UIButton;

@interface RBRewardListView : UIView <ApplilinkViewDelegate>
{
    _Bool _animating;
    _Bool _webTargetAnimating;
    RBCustomView *_parentCustomView;
    UIActivityIndicatorView *_indicatorView;
    UIView *_webTargetView;
    UIButton *_backButton;
}

@property(nonatomic) _Bool webTargetAnimating; // @synthesize webTargetAnimating=_webTargetAnimating;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIView *webTargetView; // @synthesize webTargetView=_webTargetView;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) __weak RBCustomView *parentCustomView; // @synthesize parentCustomView=_parentCustomView;
- (void).cxx_destruct;
- (void)appListFailLoadWithError:(id)arg1;
- (void)appListDidDisappear;
- (void)appListDidAppear;
- (void)pushCloseButton;
- (void)loadStart;
- (void)hideAnimation;
- (void)setupView;
- (void)setParentView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

