//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBBaseViewController.h"

#import "SSZipArchiveDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class AFDownloadRequestOperation, NSString, RBResoureDownloadBGEffectView, StyledPageControl, UIImageView, UIScrollView, UIView;

@interface RBResourceDownloadViewController : RBBaseViewController <SSZipArchiveDelegate, UIScrollViewDelegate>
{
    _Bool m_Animating;
    int m_PageNum;
    _Bool _forceCheck;
    _Bool _nextAnimation;
    int _progressMode;
    int _allFileCount;
    int _currentFileCount;
    NSString *_downloadPath;
    NSString *_version;
    AFDownloadRequestOperation *_operation;
    UIView *_helpView;
    UIImageView *_scrollBGView;
    UIScrollView *_scrollView;
    StyledPageControl *_pageControl;
    UIImageView *_gradView;
    UIView *_pastelView;
    UIImageView *_popImageView;
    UIImageView *_pastelImageView;
    UIImageView *_trackImageView;
    UIImageView *_progressImageView;
    UIImageView *_fadeImageView;
    RBResoureDownloadBGEffectView *_bgEffectView;
}

+ (_Bool)checkFile;
@property _Bool nextAnimation; // @synthesize nextAnimation=_nextAnimation;
@property int currentFileCount; // @synthesize currentFileCount=_currentFileCount;
@property int allFileCount; // @synthesize allFileCount=_allFileCount;
@property(nonatomic) int progressMode; // @synthesize progressMode=_progressMode;
@property(retain, nonatomic) RBResoureDownloadBGEffectView *bgEffectView; // @synthesize bgEffectView=_bgEffectView;
@property(retain, nonatomic) UIImageView *fadeImageView; // @synthesize fadeImageView=_fadeImageView;
@property(retain, nonatomic) UIImageView *progressImageView; // @synthesize progressImageView=_progressImageView;
@property(retain, nonatomic) UIImageView *trackImageView; // @synthesize trackImageView=_trackImageView;
@property(retain, nonatomic) UIImageView *pastelImageView; // @synthesize pastelImageView=_pastelImageView;
@property(retain, nonatomic) UIImageView *popImageView; // @synthesize popImageView=_popImageView;
@property(retain, nonatomic) UIView *pastelView; // @synthesize pastelView=_pastelView;
@property(retain, nonatomic) UIImageView *gradView; // @synthesize gradView=_gradView;
@property(retain, nonatomic) StyledPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIImageView *scrollBGView; // @synthesize scrollBGView=_scrollBGView;
@property(retain, nonatomic) UIView *helpView; // @synthesize helpView=_helpView;
@property(retain, nonatomic) AFDownloadRequestOperation *operation; // @synthesize operation=_operation;
@property(nonatomic) _Bool forceCheck; // @synthesize forceCheck=_forceCheck;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *downloadPath; // @synthesize downloadPath=_downloadPath;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)pageDidChangeValue:(id)arg1;
- (void)layoutScrollView;
- (void)updateLayout;
- (void)createViewSame:(int)arg1;
- (void)setupView;
- (void)zipArchiveDidUnzipFileAtIndex:(long long)arg1 totalFiles:(long long)arg2 archivePath:(id)arg3 fileInfo:(struct unz_file_info_s)arg4;
- (void)zipArchiveWillUnzipFileAtIndex:(long long)arg1 totalFiles:(long long)arg2 archivePath:(id)arg3 fileInfo:(struct unz_file_info_s)arg4;
- (void)zipArchiveDidUnzipArchiveAtPath:(id)arg1 zipInfo:(struct unz_global_info_s)arg2 unzippedPath:(id)arg3;
- (void)zipArchiveWillUnzipArchiveAtPath:(id)arg1 zipInfo:(struct unz_global_info_s)arg2;
- (void)updateProgress:(id)arg1;
- (void)success;
- (void)unzip:(id)arg1;
- (void)downloadWithURLString:(id)arg1;
- (void)request;
- (void)animation;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)pause;
- (void)resume;
- (void)download;
- (void)viewDidLoad;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

