//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView;

@interface RBSettingMenuButton : UIView
{
    UIButton *_button;
    UIImageView *_effectImageView;
    UIImageView *_effectTextImageView;
}

@property(retain, nonatomic) UIImageView *effectTextImageView; // @synthesize effectTextImageView=_effectTextImageView;
@property(retain, nonatomic) UIImageView *effectImageView; // @synthesize effectImageView=_effectImageView;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
- (void).cxx_destruct;
- (void)setEnabled:(_Bool)arg1;
- (void)removeFlashEffect;
- (void)setFlashEffect;
- (void)setupView:(long long)arg1;
- (id)initWithFilename:(long long)arg1;

@end

