//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface RBServerAPIManager : NSObject
{
}

+ (void)tutorialAPI;
+ (void)unlockedAPIWithType:(unsigned int)arg1 identity:(unsigned int)arg2 point:(float)arg3;
+ (void)playedV2APIWithMusicID:(unsigned int)arg1 dif:(unsigned int)arg2 note:(unsigned int)arg3 jr:(unsigned int)arg4 score:(unsigned int)arg5;
+ (void)playedAPIWithMusicID:(unsigned int)arg1 dif:(unsigned int)arg2;

@end

