//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBMusicMenuPopupView.h"

#import "SearchMapViewDelegate-Protocol.h"

@class NSString, RBSearchMapView, RBSettingView, UIButton;

@interface RBSearchView : RBMusicMenuPopupView <SearchMapViewDelegate>
{
    _Bool m_Animating;
    int _thema;
    RBSettingView *_settingView;
    RBSearchMapView *_map;
    UIButton *_currentPositionButton;
}

@property(retain, nonatomic) UIButton *currentPositionButton; // @synthesize currentPositionButton=_currentPositionButton;
@property(retain, nonatomic) RBSearchMapView *map; // @synthesize map=_map;
@property(nonatomic) __weak RBSettingView *settingView; // @synthesize settingView=_settingView;
- (void).cxx_destruct;
- (void)didChangeUserTracking:(_Bool)arg1;
- (void)hideAnimation;
- (void)selectCurrentPosition:(id)arg1;
- (void)setupView;
- (void)showAnimation;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

