//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBBaseViewController.h"

#import "DownloaderDelegate-Protocol.h"
#import "StoreDownloadManagerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class Downloader, NSString, RBStoreTabController, StoreDownloadManager, UIAlertView, UIImage, UILabel, UITableView;

@interface RBStoreManageViewController : RBBaseViewController <UITableViewDelegate, UITableViewDataSource, StoreDownloadManagerDelegate, DownloaderDelegate>
{
    long long working_index;
    _Bool isPad;
    RBStoreTabController *_parent;
    UITableView *_tableView;
    Downloader *_infoDownloader;
    StoreDownloadManager *_dlManager;
    UIAlertView *_deleteAlertView;
    UIAlertView *_downloadAlertView;
    UIImage *_imgDelete;
    UIImage *_imgDownload;
    UILabel *_labelName;
    UILabel *_labelArtist;
}

@property(retain, nonatomic) UILabel *labelArtist; // @synthesize labelArtist=_labelArtist;
@property(retain, nonatomic) UILabel *labelName; // @synthesize labelName=_labelName;
@property(retain, nonatomic) UIImage *imgDownload; // @synthesize imgDownload=_imgDownload;
@property(retain, nonatomic) UIImage *imgDelete; // @synthesize imgDelete=_imgDelete;
@property(retain, nonatomic) UIAlertView *downloadAlertView; // @synthesize downloadAlertView=_downloadAlertView;
@property(retain, nonatomic) UIAlertView *deleteAlertView; // @synthesize deleteAlertView=_deleteAlertView;
@property(retain, nonatomic) StoreDownloadManager *dlManager; // @synthesize dlManager=_dlManager;
@property(retain, nonatomic) Downloader *infoDownloader; // @synthesize infoDownloader=_infoDownloader;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak RBStoreTabController *parent; // @synthesize parent=_parent;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)downloadManagerProceed:(id)arg1;
- (void)downloadManagerFailed:(id)arg1;
- (void)downloadManagerCompleted:(id)arg1;
- (void)didPresentAlertView:(id)arg1;
- (void)alertViewCancel:(id)arg1;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)storeDialogCancel:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)startDownloadMusic;
- (void)pushCellButton:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)loadView;
- (id)initWithParent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

