//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBBaseViewController.h"

#import "ImageDownloaderDelegate-Protocol.h"
#import "PurchaseManagerDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "StoreDownloadManagerDelegate-Protocol.h"
#import "StorePackInfoDownloaderDelegate-Protocol.h"
#import "StorePackListDelegate-Protocol.h"
#import "StorePackViewDelegate-Protocol.h"
#import "StorePromotionViewDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, RBStoreGenreViewController, RBStorePackList, RBStoreTabController, SKStoreProductViewController, StoreDownloadManager, StorePackDetailViewPad, StorePackInfo, StorePackInfoDownloader, StorePackListGenre, StorePromotionView, UIActivityIndicatorView, UIAlertView, UIBarButtonItem, UIButton, UIImage, UIImageView, UILabel, UINavigationController, UIPopoverController, UIView;

@interface RBStorePageViewController : RBBaseViewController <UITableViewDataSource, UITableViewDelegate, SKStoreProductViewControllerDelegate, StorePackListDelegate, PurchaseManagerDelegate, ImageDownloaderDelegate, StoreDownloadManagerDelegate, StorePackViewDelegate, StorePackInfoDownloaderDelegate, StorePromotionViewDelegate, UIPopoverControllerDelegate>
{
    _Bool m_IsPad;
    _Bool m_IsLoadingMoreList;
    RBStoreTabController *_parent;
    RBStorePackList *_packListCtrl;
    NSMutableDictionary *_artworkDownloaders;
    StoreDownloadManager *_downloadManager;
    StorePackInfo *_purchasingPackInfo;
    StorePromotionView *_promotionView;
    UILabel *_packTableLabel;
    UIButton *_showMoreButton;
    UIActivityIndicatorView *_showMoreIndicator;
    UIView *_coverViewPad;
    StorePackDetailViewPad *_packDetailViewPad;
    NSMutableArray *_restoreProductID;
    NSMutableArray *_restorePackInfo;
    UIBarButtonItem *_restoreButton;
    StorePackInfoDownloader *_storePackInfoDownloader;
    UIImage *_packBgImage0;
    UIImage *_packBgImage1;
    UIAlertView *_purchaseLimitTypeSelectView;
    UIBarButtonItem *_genreButton;
    StorePackListGenre *_currentGenre;
    RBStoreGenreViewController *_genreViewCtrl;
    UIPopoverController *_genrePopoverCtrl;
    UINavigationController *_genreNavCtrl;
    UIImageView *_bannerBgView;
    UIButton *_samplePlayButton;
    UIImage *_playImage;
    UIImage *_stopImage;
    UILabel *_sampleMusicLabel;
    SKStoreProductViewController *_itunesViewCtrl;
}

@property(retain, nonatomic) SKStoreProductViewController *itunesViewCtrl; // @synthesize itunesViewCtrl=_itunesViewCtrl;
@property(retain, nonatomic) UILabel *sampleMusicLabel; // @synthesize sampleMusicLabel=_sampleMusicLabel;
@property(retain, nonatomic) UIImage *stopImage; // @synthesize stopImage=_stopImage;
@property(retain, nonatomic) UIImage *playImage; // @synthesize playImage=_playImage;
@property(retain, nonatomic) UIButton *samplePlayButton; // @synthesize samplePlayButton=_samplePlayButton;
@property(retain, nonatomic) UIImageView *bannerBgView; // @synthesize bannerBgView=_bannerBgView;
@property(retain, nonatomic) UINavigationController *genreNavCtrl; // @synthesize genreNavCtrl=_genreNavCtrl;
@property(retain, nonatomic) UIPopoverController *genrePopoverCtrl; // @synthesize genrePopoverCtrl=_genrePopoverCtrl;
@property(retain, nonatomic) RBStoreGenreViewController *genreViewCtrl; // @synthesize genreViewCtrl=_genreViewCtrl;
@property(retain, nonatomic) StorePackListGenre *currentGenre; // @synthesize currentGenre=_currentGenre;
@property(retain, nonatomic) UIBarButtonItem *genreButton; // @synthesize genreButton=_genreButton;
@property(retain, nonatomic) UIAlertView *purchaseLimitTypeSelectView; // @synthesize purchaseLimitTypeSelectView=_purchaseLimitTypeSelectView;
@property(retain, nonatomic) UIImage *packBgImage1; // @synthesize packBgImage1=_packBgImage1;
@property(retain, nonatomic) UIImage *packBgImage0; // @synthesize packBgImage0=_packBgImage0;
@property(retain, nonatomic) StorePackInfoDownloader *storePackInfoDownloader; // @synthesize storePackInfoDownloader=_storePackInfoDownloader;
@property(retain, nonatomic) UIBarButtonItem *restoreButton; // @synthesize restoreButton=_restoreButton;
@property(retain, nonatomic) NSMutableArray *restorePackInfo; // @synthesize restorePackInfo=_restorePackInfo;
@property(retain, nonatomic) NSMutableArray *restoreProductID; // @synthesize restoreProductID=_restoreProductID;
@property(retain, nonatomic) StorePackDetailViewPad *packDetailViewPad; // @synthesize packDetailViewPad=_packDetailViewPad;
@property(retain, nonatomic) UIView *coverViewPad; // @synthesize coverViewPad=_coverViewPad;
@property(retain, nonatomic) UIActivityIndicatorView *showMoreIndicator; // @synthesize showMoreIndicator=_showMoreIndicator;
@property(retain, nonatomic) UIButton *showMoreButton; // @synthesize showMoreButton=_showMoreButton;
@property(retain, nonatomic) UILabel *packTableLabel; // @synthesize packTableLabel=_packTableLabel;
@property(retain, nonatomic) StorePromotionView *promotionView; // @synthesize promotionView=_promotionView;
@property(retain, nonatomic) StorePackInfo *purchasingPackInfo; // @synthesize purchasingPackInfo=_purchasingPackInfo;
@property(retain, nonatomic) StoreDownloadManager *downloadManager; // @synthesize downloadManager=_downloadManager;
@property(retain, nonatomic) NSMutableDictionary *artworkDownloaders; // @synthesize artworkDownloaders=_artworkDownloaders;
@property(retain, nonatomic) RBStorePackList *packListCtrl; // @synthesize packListCtrl=_packListCtrl;
@property(nonatomic) __weak RBStoreTabController *parent; // @synthesize parent=_parent;
- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)closeItunesWithURL;
- (void)openItunesWithURL:(id)arg1;
- (void)storeDetailViewOpenItunesWithURL:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)stopPromotion;
- (void)setPlaySampleName:(id)arg1;
- (void)showLoadingView;
- (void)hideGenreSelect:(id)arg1;
- (void)presentGenreSelect:(id)arg1;
- (void)switchToGenre:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)stopDownloadArtworks;
- (void)scrollViewDidScroll:(id)arg1;
- (void)imageDownloaderDidFail:(id)arg1 didLoad:(id)arg2;
- (void)imageDownloader:(id)arg1 didLoad:(id)arg2;
- (void)selectShowMore;
- (void)showDetailViewForPhone:(int)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numPackRows;
- (void)downloadManagerProceed:(id)arg1;
- (void)downloadManagerFailed:(id)arg1;
- (void)downloadManagerCompleted:(id)arg1;
- (void)downloadManagerStartTask:(id)arg1;
- (void)storePackInfoDownloaderError:(id)arg1;
- (void)storePackInfoDownloaderFinished:(id)arg1;
- (void)restoreNothing;
- (void)restoreFailed:(id)arg1;
- (void)restoreSucceeded;
- (void)didPresentAlertView:(id)arg1;
- (void)alertViewCancel:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)restoreDownloadAllMusics;
- (void)askDownloadAllMusics;
- (_Bool)nextRestorePackInfo;
- (void)addRestorePackInfo:(id)arg1;
- (void)purchaseFailed:(id)arg1 error:(id)arg2;
- (void)purchaseSucceeded:(id)arg1;
- (void)reDownloadPackMusics:(id)arg1;
- (void)updatePurchasedTableCell:(id)arg1;
- (void)updateMusicInfo:(id)arg1 Save:(_Bool)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)storeDialogCancel:(id)arg1;
- (void)detailViewClose;
- (void)detailViewStartPurchase:(id)arg1;
- (_Bool)checkAttainLimitPurchase:(id)arg1;
- (void)startDownloadPackMusics:(id)arg1;
- (void)handleTapCoverView:(id)arg1;
- (void)openDetailAnimStopFromPromotion:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)pushSampleButton:(id)arg1;
- (void)storePromotionViewTaped:(id)arg1 PackID:(int)arg2;
- (void)openDetailAnimStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)openPackDetailViewWithPackId:(int)arg1;
- (void)packViewSelected:(id)arg1;
- (void)packListDownloadNothing:(id)arg1;
- (void)packListDownloadError:(id)arg1 errorMessage:(id)arg2;
- (void)forceOpenPackDetailView;
- (void)packListDownloadSuccess:(id)arg1;
- (void)pushBarBtnRestore:(id)arg1;
- (void)showError:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithParent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

