//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DownloaderDelegate-Protocol.h"
#import "SKProductsRequestDelegate-Protocol.h"

@class Downloader, NSArray, NSDictionary, NSMutableArray, NSString, SKProductsRequest, StorePackListGenre;
@protocol StorePackListDelegate;

@interface RBStorePackList : NSObject <SKProductsRequestDelegate, DownloaderDelegate>
{
    _Bool _packlistContinued;
    _Bool _isOptionalProductRequest;
    unsigned int _fetchedPackNum;
    id <StorePackListDelegate> _delegate;
    NSArray *_promotionList;
    NSMutableArray *_arrayPackInfo;
    Downloader *_packlistDownloader;
    NSDictionary *_tempPackList;
    SKProductsRequest *_productsRequest;
    NSMutableArray *_arrayGenre;
    StorePackListGenre *_genreFetching;
}

+ (id)storeCountry;
@property(retain, nonatomic) StorePackListGenre *genreFetching; // @synthesize genreFetching=_genreFetching;
@property(retain, nonatomic) NSMutableArray *arrayGenre; // @synthesize arrayGenre=_arrayGenre;
@property(nonatomic) _Bool isOptionalProductRequest; // @synthesize isOptionalProductRequest=_isOptionalProductRequest;
@property(nonatomic) unsigned int fetchedPackNum; // @synthesize fetchedPackNum=_fetchedPackNum;
@property(retain, nonatomic) SKProductsRequest *productsRequest; // @synthesize productsRequest=_productsRequest;
@property(retain, nonatomic) NSDictionary *tempPackList; // @synthesize tempPackList=_tempPackList;
@property(retain, nonatomic) Downloader *packlistDownloader; // @synthesize packlistDownloader=_packlistDownloader;
@property(retain, nonatomic) NSMutableArray *arrayPackInfo; // @synthesize arrayPackInfo=_arrayPackInfo;
@property(retain, nonatomic) NSArray *promotionList; // @synthesize promotionList=_promotionList;
@property(readonly, nonatomic) _Bool packlistContinued; // @synthesize packlistContinued=_packlistContinued;
@property(nonatomic) __weak id <StorePackListDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)optionalProductsRequest;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)updatePackInfo:(id)arg1 SKProductsResponse:(id)arg2;
- (id)addPackInfoFromID:(int)arg1;
- (id)getPackInfo:(int)arg1;
- (void)startFetchGenre:(id)arg1;
- (void)startFetchForGenreIndex:(unsigned long long)arg1;
- (id)packListForGenreIndex:(unsigned long long)arg1;
- (void)addGenres:(id)arg1;
- (id)genreNames;
- (unsigned long long)numGenres;
- (id)packInfos;
- (_Bool)isFetching;
- (void)cancelFetching;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

