//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBMusicMenuPopupView.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, RBSettingView, UIButton, UIImageView, UIScrollView;

@interface RBThemaView : RBMusicMenuPopupView <UIScrollViewDelegate>
{
    int _thema;
    int _unlockedThemaCount;
    RBSettingView *_settingView;
    UIScrollView *_scrollView;
    UIImageView *_classicView;
    UIImageView *_limelightView;
    UIImageView *_coletteView;
    UIButton *_okButton;
}

@property(nonatomic) int unlockedThemaCount; // @synthesize unlockedThemaCount=_unlockedThemaCount;
@property(nonatomic) int thema; // @synthesize thema=_thema;
@property(retain, nonatomic) UIButton *okButton; // @synthesize okButton=_okButton;
@property(retain, nonatomic) UIImageView *coletteView; // @synthesize coletteView=_coletteView;
@property(retain, nonatomic) UIImageView *limelightView; // @synthesize limelightView=_limelightView;
@property(retain, nonatomic) UIImageView *classicView; // @synthesize classicView=_classicView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak RBSettingView *settingView; // @synthesize settingView=_settingView;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)yesButtonTouch:(id)arg1;
- (void)setupView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

