//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, RBMenuTutorialView;

@interface RBTutorialManager : NSObject
{
    _Bool _isTutorial;
    _Bool _isInputable;
    unsigned int _currentStatus;
    RBMenuTutorialView *_tutorialView;
    NSMutableArray *_unlockItemInfo;
}

+ (void)resetUnlockedItemInfo;
+ (id)getUnlockedItemInfo;
+ (void)setUnlockedItemInfo:(int)arg1 itemId:(int)arg2;
+ (void)updateStatus:(unsigned int)arg1;
+ (unsigned int)getCurrentStatus;
+ (unsigned int)getStatus:(unsigned int)arg1;
+ (void)startTutorialStore;
+ (_Bool)needStartTutorialStore;
+ (_Bool)isTutorialCustomize;
+ (void)startTutorialCustomize;
+ (_Bool)needStartTutorialCustomize;
+ (_Bool)isTutorialPlay;
+ (_Bool)needStartTutorialPlay;
+ (_Bool)isTutorialMusicselect;
+ (void)startTutorialMusicselect;
+ (_Bool)needStartTutorialMusicselect;
+ (_Bool)isTutorial;
+ (id)getInstance;
@property(retain, nonatomic) NSMutableArray *unlockItemInfo; // @synthesize unlockItemInfo=_unlockItemInfo;
@property(nonatomic) __weak RBMenuTutorialView *tutorialView; // @synthesize tutorialView=_tutorialView;
@property(nonatomic) _Bool isInputable; // @synthesize isInputable=_isInputable;
@property(nonatomic) _Bool isTutorial; // @synthesize isTutorial=_isTutorial;
@property(nonatomic) unsigned int currentStatus; // @synthesize currentStatus=_currentStatus;
- (void).cxx_destruct;

@end

