//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "RBCollectionViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSString, RBCollectionView, RBUnlockPackageData, StyledPageControl, UIImageView, UILabel;
@protocol RBExperienceCollectionViewDelegate;

@interface RBUnlockCollectionView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, RBCollectionViewDelegate>
{
    id <RBExperienceCollectionViewDelegate> _delegate;
    UIImageView *_backgroundView;
    UILabel *_titleLabel;
    RBCollectionView *_collectionView;
    StyledPageControl *_pageControl;
    RBUnlockPackageData *_experiencePackageData;
    NSArray *_items;
}

@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) RBUnlockPackageData *experiencePackageData; // @synthesize experiencePackageData=_experiencePackageData;
@property(retain, nonatomic) StyledPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) RBCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) __weak id <RBExperienceCollectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)configureCell:(id)arg1;
- (void)didLayoutSubviews:(id)arg1;
- (void)reloadData;
- (void)setupView;
- (id)initWithFrame:(struct CGRect)arg1 experiencePackageData:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

