//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "RBUrlSchemeControllerProtocol-Protocol.h"

@class NSString;

@interface RBUrlSchemeStoreController : NSObject <RBUrlSchemeControllerProtocol>
{
}

- (_Bool)campaignRbAction:(id)arg1;
- (_Bool)packRbAction:(id)arg1;
- (_Bool)action:(id)arg1 query:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

