//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface RecommendWebAPI : NSObject
{
}

+ (id)appStartWithAdIdFrom:(id)arg1 adIdTo:(id)arg2 adType:(int)arg3;
+ (id)clickRegistWithAdIdFrom:(id)arg1 adIdTo:(id)arg2 adModel:(int)arg3;
+ (void)layoutIndexWithCallback:(CDUnknownBlockType)arg1;
+ (void)allAdDataWithCallBack:(CDUnknownBlockType)arg1;
+ (void)appStartWithAdIdFrom:(id)arg1 adIdTo:(id)arg2 adType:(int)arg3 callback:(CDUnknownBlockType)arg4;
+ (void)clickRegistWithAdIdFrom:(id)arg1 adIdTo:(id)arg2 adModel:(int)arg3 callback:(CDUnknownBlockType)arg4;
+ (id)getTemporaryCacheWithAdModel:(int)arg1;
+ (void)setTemporaryCacheWithAdModel:(int)arg1 value:(long long)arg2 expiration:(long long)arg3;
+ (void)getPreInfoWithAdModel:(int)arg1 adLocation:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)getUnreadCountWithAdModel:(int)arg1 adLocation:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)readRegistWithAdType:(int)arg1 adIdList:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)getBannerDetailWithAdModel:(int)arg1 callback:(CDUnknownBlockType)arg2;
+ (void)postApplicationInstallWithAdIdFrom:(id)arg1 categoryId:(id)arg2 adType:(id)arg3 priority:(int)arg4 callback:(CDUnknownBlockType)arg5;
+ (void)appliListWithParameters:(id)arg1 callBack:(CDUnknownBlockType)arg2;
+ (void)installAppliListWithCallBack:(CDUnknownBlockType)arg1;
+ (void)getAdDetailWithCallback:(CDUnknownBlockType)arg1;
+ (void)startLoginWithCallback:(CDUnknownBlockType)arg1;
+ (void)checkLoginWithCallback:(CDUnknownBlockType)arg1;

@end

