//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWebView.h>

#import "UIWebViewDelegate-Protocol.h"

@class NSString;
@protocol ApplilinkViewDelegate;

@interface RecommendAdWebView : UIWebView <UIWebViewDelegate>
{
    _Bool _loadComplete;
    _Bool _reloadFlg;
    _Bool _cancelFlg;
    _Bool _scrollFlg;
    int _webViewStatus;
    int _adModel;
    int _verticalAlign;
    id <ApplilinkViewDelegate> _applilinkDelegate;
    NSString *_adLocation;
    id _requestCode;
}

@property(nonatomic) id requestCode; // @synthesize requestCode=_requestCode;
@property(nonatomic) int verticalAlign; // @synthesize verticalAlign=_verticalAlign;
@property(retain, nonatomic) NSString *adLocation; // @synthesize adLocation=_adLocation;
@property(nonatomic) int adModel; // @synthesize adModel=_adModel;
@property(nonatomic) int webViewStatus; // @synthesize webViewStatus=_webViewStatus;
@property(nonatomic) _Bool scrollFlg; // @synthesize scrollFlg=_scrollFlg;
@property(nonatomic) _Bool cancelFlg; // @synthesize cancelFlg=_cancelFlg;
@property(nonatomic) _Bool reloadFlg; // @synthesize reloadFlg=_reloadFlg;
@property(nonatomic) _Bool loadComplete; // @synthesize loadComplete=_loadComplete;
@property(nonatomic) __weak id <ApplilinkViewDelegate> applilinkDelegate; // @synthesize applilinkDelegate=_applilinkDelegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)appListFailLinkWithError:(id)arg1;
- (void)appListFailLoadWithError:(id)arg1;
- (void)appListDidDisappear;
- (void)appListDidAppear;
- (void)appListDidStart;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)appliListClosed;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)unloadRecommendView;
- (void)setScrollBarEnabled:(_Bool)arg1;
- (void)setScrollBoundsEnabled:(_Bool)arg1;
- (void)setScrollEnabled:(_Bool)arg1;
- (void)closeAdArea;
- (void)loadRequestWithURL:(id)arg1 parameters:(id)arg2;
- (void)loadRequest;
- (void)loadRequestWithAdModel:(int)arg1 adLocation:(id)arg2 verticalAlign:(int)arg3 requestCode:(id)arg4 delegate:(id)arg5;
- (void)removeFromSuperview;
- (void)setInitParam;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

