//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface SoundData : NSObject
{
    unsigned int m_NumberOfChannels;
    long long m_TotalFrames;
    long long m_CurrentFrameCache;
    struct OpaqueExtAudioFile *m_ExtAudioFile;
    struct AudioStreamBasicDescription m_Format;
    char **m_PlayBuffer;
    NSString *m_FileName;
    _Bool m_Stream;
    unsigned int _channels;
    NSString *_fileName;
    long long _totalFrames;
}

@property(readonly) long long totalFrames; // @synthesize totalFrames=_totalFrames;
@property(readonly) unsigned int channels; // @synthesize channels=_channels;
@property(readonly) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;
- (struct AudioStreamBasicDescription *)format;
- (_Bool)getData:(long long)arg1 Frames:(long long)arg2 Loop:(_Bool)arg3 Buffer:(struct AudioBufferList *)arg4 Out:(long long *)arg5;
- (void)prepare:(id)arg1 Stream:(_Bool)arg2;
- (void)dealloc;
- (id)initWithContentsFileName:(id)arg1 Stream:(_Bool)arg2;

@end

