//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "DownloaderDelegate-Protocol.h"
#import "StorePackInfoDownloaderDelegate-Protocol.h"

@class Downloader, NSMutableArray, NSString, StoreImageView, StorePackInfo, StorePackInfoDownloader, UIActivityIndicatorView, UIButton, UILabel, UITextView;

@interface StorePackDetailViewPad : UIView <DownloaderDelegate, StorePackInfoDownloaderDelegate>
{
    int samplePlaying;
    _Bool isInfoLoaded;
    StorePackInfo *_packInfo;
    id _delegate;
    UIView *_packView;
    NSMutableArray *_musicViews;
    StoreImageView *_packArtworkView;
    UILabel *_labelPackName;
    UILabel *_labelComment;
    UITextView *_copyrightView;
    UIButton *_buttonPurchase;
    UIActivityIndicatorView *_indicator;
    UILabel *_labelLoading;
    StorePackInfoDownloader *_storePackInfoDownloader;
    Downloader *_sampleDownloader;
    UIButton *_artistSiteButton;
}

@property(retain, nonatomic) UIButton *artistSiteButton; // @synthesize artistSiteButton=_artistSiteButton;
@property(retain, nonatomic) Downloader *sampleDownloader; // @synthesize sampleDownloader=_sampleDownloader;
@property(retain, nonatomic) StorePackInfoDownloader *storePackInfoDownloader; // @synthesize storePackInfoDownloader=_storePackInfoDownloader;
@property(retain, nonatomic) UILabel *labelLoading; // @synthesize labelLoading=_labelLoading;
@property(retain, nonatomic) UIActivityIndicatorView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) UIButton *buttonPurchase; // @synthesize buttonPurchase=_buttonPurchase;
@property(retain, nonatomic) UITextView *copyrightView; // @synthesize copyrightView=_copyrightView;
@property(retain, nonatomic) UILabel *labelComment; // @synthesize labelComment=_labelComment;
@property(retain, nonatomic) UILabel *labelPackName; // @synthesize labelPackName=_labelPackName;
@property(retain, nonatomic) StoreImageView *packArtworkView; // @synthesize packArtworkView=_packArtworkView;
@property(retain, nonatomic) NSMutableArray *musicViews; // @synthesize musicViews=_musicViews;
@property(retain, nonatomic) UIView *packView; // @synthesize packView=_packView;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) StorePackInfo *packInfo; // @synthesize packInfo=_packInfo;
- (void).cxx_destruct;
- (void)didPresentAlertView:(id)arg1;
- (void)alertViewCancel:(id)arg1;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)storePackInfoDownloaderError:(id)arg1;
- (void)storePackInfoDownloaderFinished:(id)arg1;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)finishBgm:(id)arg1;
- (void)selectWebButton;
- (void)handleSample:(id)arg1;
- (void)handleLink:(id)arg1;
- (void)doPurchase:(id)arg1;
- (void)loadInfo;
- (void)showPackInfo;
- (void)setButtonTextInstalled;
- (void)setButtonTextInstalling;
- (void)setButtonTextInstall;
- (void)setButtonTextBuy;
- (void)selfCheckButtonText;
- (_Bool)allDownloaded;
- (void)stopSample;
- (void)cancelLoading;
- (void)removePackInfo;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

