//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, RBStorePackList;

@protocol StorePackListDelegate <NSObject>
- (void)packListDownloadNothing:(RBStorePackList *)arg1;
- (void)packListDownloadError:(RBStorePackList *)arg1 errorMessage:(NSString *)arg2;
- (void)packListDownloadSuccess:(RBStorePackList *)arg1;
@end

