//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface StoreDetailCopyrightCell : UITableViewCell
{
    UILabel *_labelCopyright;
}

@property(retain, nonatomic) UILabel *labelCopyright; // @synthesize labelCopyright=_labelCopyright;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

