//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class StoreDownloadManager;

@protocol StoreDownloadManagerDelegate <NSObject>

@optional
- (void)downloadManagerFailed:(StoreDownloadManager *)arg1;
- (void)downloadManagerProceed:(StoreDownloadManager *)arg1;
- (void)downloadManagerCompleted:(StoreDownloadManager *)arg1;
- (void)downloadManagerStartTask:(StoreDownloadManager *)arg1;
@end

