//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DownloaderDelegate-Protocol.h"

@class Downloader, NSArray, NSString;
@protocol StoreDownloadManagerDelegate;

@interface StoreDownloadManager : NSObject <DownloaderDelegate>
{
    _Bool m_IsStarted;
    unsigned int _currentIndex;
    NSArray *_tasks;
    id <StoreDownloadManagerDelegate> _delegate;
    Downloader *_fileDownloader;
}

@property(retain, nonatomic) Downloader *fileDownloader; // @synthesize fileDownloader=_fileDownloader;
@property(nonatomic) __weak id <StoreDownloadManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *tasks; // @synthesize tasks=_tasks;
@property(readonly, nonatomic) unsigned int currentIndex; // @synthesize currentIndex=_currentIndex;
- (void).cxx_destruct;
- (void)dealloc;
- (void)downloaderError:(id)arg1;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)cancel;
- (void)start;
@property(readonly, nonatomic) unsigned long long numTasks;
@property(readonly, nonatomic) float overallProgress;
@property(readonly, nonatomic) float currentProgress;
- (id)initWithTasks:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

