//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface StoreDetailHeaderView : UIView
{
    UILabel *_labelName;
    UILabel *_labelComment;
    UIButton *_buttonPurchase;
    UIImageView *_bgView;
    UIImageView *_artworkView;
    UIImageView *_reflectionArtworkView;
    UIImageView *_iconNewMarker;
}

@property(retain, nonatomic) UIImageView *iconNewMarker; // @synthesize iconNewMarker=_iconNewMarker;
@property(retain, nonatomic) UIImageView *reflectionArtworkView; // @synthesize reflectionArtworkView=_reflectionArtworkView;
@property(retain, nonatomic) UIImageView *artworkView; // @synthesize artworkView=_artworkView;
@property(retain, nonatomic) UIImageView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIButton *buttonPurchase; // @synthesize buttonPurchase=_buttonPurchase;
@property(retain, nonatomic) UILabel *labelComment; // @synthesize labelComment=_labelComment;
@property(retain, nonatomic) UILabel *labelName; // @synthesize labelName=_labelName;
- (void).cxx_destruct;
- (void)setArtwork:(id)arg1;
- (void)loadPackInfo:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

