//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TwitterImageCreaterScoreElement, UIImage;

@interface TwitterImageCreater : NSObject
{
    int m_Width;
    int m_Height;
    float m_Scale;
    char *m_Data;
    struct CGContext *m_Context;
    struct CGColorSpace *m_ColorSpace;
    TwitterImageCreaterScoreElement *m_Score[2];
    int _grade;
    int _level;
    int _gameType;
    int _noteNum;
    int _color;
    UIImage *_titleImage;
    UIImage *_artistImage;
}

@property(nonatomic) int color; // @synthesize color=_color;
@property(nonatomic) int noteNum; // @synthesize noteNum=_noteNum;
@property(nonatomic) int gameType; // @synthesize gameType=_gameType;
@property(nonatomic) int level; // @synthesize level=_level;
@property(nonatomic) int grade; // @synthesize grade=_grade;
@property(retain, nonatomic) UIImage *artistImage; // @synthesize artistImage=_artistImage;
@property(retain, nonatomic) UIImage *titleImage; // @synthesize titleImage=_titleImage;
- (void).cxx_destruct;
- (id)createImage;
- (void)drawScore:(int)arg1 Pos:(int)arg2 Dot:(_Bool)arg3;
- (int)getDigitNum:(int)arg1;
- (void)drawNumber:(int)arg1 Position:(const struct CGPoint *)arg2 Keta:(int)arg3 Dot:(_Bool)arg4;
- (void)drawText:(id)arg1 Position:(const struct CGPoint *)arg2 Font:(id)arg3 Color:(id)arg4;
- (void)drawImageFileName:(id)arg1 Position:(const struct CGPoint *)arg2;
- (void)drawImageFileName:(id)arg1 X:(int)arg2 Y:(int)arg3;
- (void)drawImage:(id)arg1 X:(int)arg2 Y:(int)arg3;
- (void)drawImage:(id)arg1 X:(int)arg2 Y:(int)arg3 Scale:(float)arg4;
- (void)createContext:(int)arg1:(int)arg2;
- (void)setName:(id)arg1 Side:(int)arg2;
- (void)setMaxComboNum:(int)arg1 Side:(int)arg2;
- (void)setJustReflecNum:(int)arg1 Side:(int)arg2;
- (void)setMissNum:(int)arg1 Side:(int)arg2;
- (void)setGoodNum:(int)arg1 Side:(int)arg2;
- (void)setGreatNum:(int)arg1 Side:(int)arg2;
- (void)setJustNum:(int)arg1 Side:(int)arg2;
- (void)setAR:(float)arg1 Side:(int)arg2;
- (void)setScore:(int)arg1 Side:(int)arg2;
- (void)dealloc;
- (void)reset;
- (id)init;

@end

