//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TwitterImageCreaterScoreElement : NSObject
{
    int _score;
    float _ar;
    int _justNum;
    int _greatNum;
    int _goodNum;
    int _missNum;
    int _justReflecNum;
    int _maxComboNum;
    NSString *_name;
}

@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) int maxComboNum; // @synthesize maxComboNum=_maxComboNum;
@property(nonatomic) int justReflecNum; // @synthesize justReflecNum=_justReflecNum;
@property(nonatomic) int missNum; // @synthesize missNum=_missNum;
@property(nonatomic) int goodNum; // @synthesize goodNum=_goodNum;
@property(nonatomic) int greatNum; // @synthesize greatNum=_greatNum;
@property(nonatomic) int justNum; // @synthesize justNum=_justNum;
@property(nonatomic) float ar; // @synthesize ar=_ar;
@property(nonatomic) int score; // @synthesize score=_score;
- (void).cxx_destruct;
- (void)dealloc;

@end

