//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (RB)
+ (id)imageWithName:(id)arg1 useCache:(_Bool)arg2;
+ (id)imageWithName:(id)arg1;
+ (id)imageNamedWithoutCache:(id)arg1;
+ (id)imageWithName:(id)arg1 imageDirectory:(id)arg2 themaDirectory:(id)arg3;
+ (id)imageWithName:(id)arg1 imageDirectory:(id)arg2 themaDirectory:(id)arg3 retina:(_Bool)arg4;
+ (void)clearImageCache;
- (id)clipImageWithRect:(struct CGRect)arg1;
- (id)reflectedImageWithHeight:(double)arg1;
@end

