//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (RB)
+ (void)removeFlashEffectView:(id)arg1;
+ (void)setFlashEffectView:(id)arg1 Duration:(float)arg2 Start:(float)arg3 End:(float)arg4 Rotate:(_Bool)arg5;
- (void)RemoveJumpEffect;
- (void)SetJumpEffectBaseX:(float)arg1 BaseY:(float)arg2;
- (void)RemoveAlphaAnimation;
- (void)SetAlphaAnimationDuration:(float)arg1 End:(float)arg2;
- (void)SetFlashEffectSlow;
- (void)SetFlashEffectFastWithRotate;
- (void)SetFlashEffectFast;
- (void)RemoveFlashEffect;
- (void)SetFlashEffectDuration:(float)arg1 Start:(float)arg2 End:(float)arg3;
- (double)height;
- (double)width;
- (double)y;
- (double)x;
- (double)bottom;
- (double)right;
- (double)top;
- (double)left;
@end

