//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class EAGLContext, NSMutableData, NSString, Sequence, Texture2D, UIButton;

@interface AdjustTestView : UIView
{
    EAGLContext *context;
    unsigned int defaultFramebuffer;
    unsigned int colorRenderbuffer;
    unsigned int elementArrayBuffer;
    Texture2D *texture[10];
    unsigned int btnPress;
    unsigned int btnPressOld;
    NSMutableData *bgmData;
    double baseTime;
    unsigned int state;
    _Bool paused;
    float adjustTime;
    _Bool isPad;
    _Bool isRetina;
    int markerState[16];
    UIButton *panelView[4];
    NSString *_currentMarker;
    Sequence *_sequence;
}

+ (Class)layerClass;
@property(retain, nonatomic) Sequence *sequence; // @synthesize sequence=_sequence;
@property(readonly) NSString *currentMarker; // @synthesize currentMarker=_currentMarker;
- (void).cxx_destruct;
- (void)dealloc;
- (void)btnTouchesEnd:(id)arg1;
- (void)btnTouchesBegan:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)destroyFramebuffer;
- (void)draw;
- (void)drawBtn:(struct CGPoint)arg1 btnState:(int)arg2;
- (void)reset;
- (void)setAdjust:(int)arg1;
- (void)resumePreview;
- (void)suspendPreview;
- (void)pausePreview;
- (void)startPreview;
- (void)releaseTex;
- (void)loadMarkerTex:(id)arg1;
- (_Bool)createFramebuffer;
- (id)initWithFrame:(struct CGRect)arg1;

@end

