//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIAlertController, UIAlertView;

@interface AlertViewManager : NSObject
{
    UIAlertController *alertController;
    UIAlertView *alertView;
    id alDelegate;
    int alertTag;
    int alertType;
    NSString *alertText;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)alertTextFieldTextDidChangeNotification:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertControllerEvent:(int)arg1;
- (void)changeDelegate:(id)arg1;
- (void)showAlert;
- (void)showUpdateAlert;
- (void)makeAlert:(int)arg1 delegate:(id)arg2 tag:(int)arg3 title:(id)arg4 msg:(id)arg5 cancel:(id)arg6 btnText:(id)arg7 show:(_Bool)arg8;
- (void)makeAlert:(int)arg1 delegate:(id)arg2 tag:(int)arg3 title:(id)arg4 msg:(id)arg5 cancel:(id)arg6 btnText:(id)arg7 show:(_Bool)arg8 viewController:(id)arg9;
- (void)closeAlert;
- (void)setAlert:(id)arg1 tag:(int)arg2 show:(_Bool)arg3;
- (void)setAlert:(id)arg1;
- (id)init;

@end

