//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ApplilinkWebAPI : NSObject
{
    int retryCount;
}

+ (void)setSessionStatus:(_Bool)arg1;
+ (void)calcelSessionConnection;
+ (void)setSessionConnectionWait:(_Bool)arg1;
+ (void)retryCancel;
+ (id)responseFromContentsServer:(id)arg1 request:(id)arg2 data:(id)arg3 finishedBlock:(CDUnknownBlockType)arg4 failedBlock:(CDUnknownBlockType)arg5;
+ (id)requestSynchronousWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3 cachePolicy:(id)arg4 error:(id *)arg5;
+ (void)requestAsynchronousWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3 userInfo:(id)arg4 tag:(long long)arg5 cachePolicy:(id)arg6 timeout:(float)arg7 retry:(_Bool)arg8 finishedBlock:(CDUnknownBlockType)arg9 failedBlock:(CDUnknownBlockType)arg10;
- (void)dealloc;
- (_Bool)canUseNetworkRetry;
- (id)requestSynchronousWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3 cachePolicy:(id)arg4 error:(id *)arg5;
- (id)responseFromContentsServer:(id)arg1 request:(id)arg2 data:(id)arg3 finishedBlock:(CDUnknownBlockType)arg4 failedBlock:(CDUnknownBlockType)arg5;
- (void)requestAsynchronousWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3 userInfo:(id)arg4 tag:(long long)arg5 cachePolicy:(id)arg6 timeout:(float)arg7 retry:(_Bool)arg8 finishedBlock:(CDUnknownBlockType)arg9 failedBlock:(CDUnknownBlockType)arg10;
- (id)requestForPostWithURL:(id)arg1 parameters:(id)arg2;
- (id)requestForGetWithURL:(id)arg1 parameters:(id)arg2;
- (id)requestWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3 timeout:(float)arg4 cachePolicy:(id)arg5;
- (id)commonParameters;
- (id)init;

@end

