//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, NSURLRequest;

@protocol ApplilinkURLConnectionDelegate <NSObject>

@optional
- (_Bool)redirectStartLoad:(NSURLRequest *)arg1;
- (void)finishLoadWithResponse:(NSString *)arg1;
- (void)failLoadWithError:(NSError *)arg1;
@end

