//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;
@protocol ArtworkLoaderDelegate;

@interface ArtworkLoader : NSObject
{
    NSString *filePath;
    struct CGSize _size;
    _Bool big_artwork;
    unsigned int _tuneID;
    id <ArtworkLoaderDelegate> _delegate;
    UIImage *_image;
}

@property(readonly, nonatomic) unsigned int tuneID; // @synthesize tuneID=_tuneID;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) __weak id <ArtworkLoaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)loadArtwork;
- (id)shrinkImage:(id)arg1;
- (id)initWithPath:(id)arg1 tuneID:(unsigned int)arg2 size:(struct CGSize)arg3 bigArtwork:(_Bool)arg4;

@end

