//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface BalloonView : UIView
{
    UIColor *_balloonColor;
    UIColor *_borderColor;
    double _borderRadius;
    double _borderWidth;
    double _arrowPosision;
    unsigned long long _arrowDirection;
    struct CGSize _arrowSize;
    struct UIEdgeInsets _contentEdgeInsets;
}

@property(nonatomic) struct UIEdgeInsets contentEdgeInsets; // @synthesize contentEdgeInsets=_contentEdgeInsets;
@property(nonatomic) unsigned long long arrowDirection; // @synthesize arrowDirection=_arrowDirection;
@property(nonatomic) struct CGSize arrowSize; // @synthesize arrowSize=_arrowSize;
@property(nonatomic) double arrowPosision; // @synthesize arrowPosision=_arrowPosision;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) double borderRadius; // @synthesize borderRadius=_borderRadius;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain, nonatomic) UIColor *balloonColor; // @synthesize balloonColor=_balloonColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) struct CGRect contentRect;
- (id)initWithFrame:(struct CGRect)arg1;

@end

