//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURL;

@interface CampaignItemInfo : NSObject
{
    int unlockType;
    NSArray *termsTable;
    _Bool _bServerUnlock;
    _Bool _alreadyDownload;
    _Bool _bUnlock;
    int _campaignID;
    int _itemType;
    int _itemID;
    int _buttonType;
    int _hideType;
    NSString *_name;
    NSString *_itemDescription;
    NSString *_unlockDescription;
    NSString *_bannerURL;
    NSString *_itemImageURL;
    NSURL *_linkURL;
    NSString *_lisenceText;
    NSURL *_sampleURL;
}

@property(readonly, nonatomic) NSURL *sampleURL; // @synthesize sampleURL=_sampleURL;
@property(readonly, nonatomic) NSString *lisenceText; // @synthesize lisenceText=_lisenceText;
@property(readonly, nonatomic) NSURL *linkURL; // @synthesize linkURL=_linkURL;
@property(readonly, nonatomic) int hideType; // @synthesize hideType=_hideType;
@property(readonly, nonatomic) int buttonType; // @synthesize buttonType=_buttonType;
@property(readonly, nonatomic) _Bool bUnlock; // @synthesize bUnlock=_bUnlock;
@property(readonly, nonatomic) _Bool alreadyDownload; // @synthesize alreadyDownload=_alreadyDownload;
@property(readonly, nonatomic) int itemID; // @synthesize itemID=_itemID;
@property(readonly, nonatomic) int itemType; // @synthesize itemType=_itemType;
@property(readonly, nonatomic) _Bool bServerUnlock; // @synthesize bServerUnlock=_bServerUnlock;
@property(readonly, nonatomic) NSString *itemImageURL; // @synthesize itemImageURL=_itemImageURL;
@property(readonly, nonatomic) NSString *bannerURL; // @synthesize bannerURL=_bannerURL;
@property(readonly, nonatomic) NSString *unlockDescription; // @synthesize unlockDescription=_unlockDescription;
@property(readonly, nonatomic) NSString *itemDescription; // @synthesize itemDescription=_itemDescription;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) int campaignID; // @synthesize campaignID=_campaignID;
- (void).cxx_destruct;
- (_Bool)hasItem:(int)arg1 itemID:(int)arg2;
- (_Bool)checkNewUnlock;
- (void)replaceServerUnlock:(_Bool)arg1;
- (_Bool)checkExistPackList:(id)arg1 packID:(int)arg2;
- (_Bool)termCheck;
- (id)initWithDictionary:(id)arg1;

@end

