//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

#pragma mark Typedef'd Structures

typedef struct {
    int state;
    unsigned int move;
    unsigned int currentSector;
    unsigned int endSector;
} CDStruct_0f097b75;

typedef struct {
    int nMiss;
    int nPoor;
    int nGood;
    int nGreat;
    int nPerfect;
    int curCombo;
    int maxCombo;
    int tension;
    int point;
    int bonusPoint;
    int totalPoint;
    char musicBarResult[30];
} CDStruct_c6ce2fc0;

typedef struct {
    short _field1;
    short _field2;
    unsigned int _field3;
    unsigned int _field4;
    short _field5;
    unsigned int _field6;
} CDStruct_009559ee;

typedef struct {
    CDStruct_2c43369c center;
    struct {
        double latitudeDelta;
        double longitudeDelta;
    } span;
} CDStruct_feeb6407;

// Ambiguous groups
typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

typedef struct {
    double latitude;
    double longitude;
} CDStruct_2c43369c;

