//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class ChallengeTextInputView, CopyableUiLabel, NSString, UIButton, UIImageView;

@interface ChallengeNameSettingView : UIView <UITextViewDelegate>
{
    ChallengeTextInputView *inputView;
    UIImageView *bgView;
    UIButton *closeBtn;
    CopyableUiLabel *myID;
    _Bool enableBackBtn;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)alertSelect:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)closeSettingMenu:(id)arg1;
- (void)commitText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 backEnable:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

