//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface ChallengeResourceManager : NSObject
{
    NSMutableArray *_arrayResource;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableArray *arrayResource; // @synthesize arrayResource=_arrayResource;
- (void).cxx_destruct;
- (void)setIgnoreSave:(id)arg1;
- (void)deletePanelResourceData:(int)arg1;
- (void)savePanelResourceData:(id)arg1 info:(id)arg2;
- (id)getPanelResourceData:(id)arg1;
- (_Bool)addPanelResourceInfo:(id)arg1;
- (void)saveResourceList;
- (void)loadResourceList;
- (id)init;

@end

