//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ChallengeTextInputView, CopyableUiLabel, NSString, UIButton, UIImageView, UILabel;

@interface ChallengeRivalSearchView : UIView
{
    ChallengeTextInputView *inputView;
    NSString *targetID;
    NSString *targetName;
    struct CGRect listRect;
    UIView *searchBox;
    UIView *rivalView;
    UIImageView *bgView;
    UIButton *closeBtn;
    CopyableUiLabel *myID;
    UIImageView *addMessage;
    UIView *rivalAddView;
    UIImageView *addBgView;
    UIButton *addBtn;
    UIButton *cancelBtn;
    UIButton *endBtn;
    UILabel *rivalID;
    UILabel *rivalName;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)closeSettingMenu:(id)arg1;
- (void)tapClose:(id)arg1;
- (void)selectRivalCancel:(id)arg1;
- (void)selectRivalAdd:(id)arg1;
- (void)alertSelect:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)commitText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

