//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImage, UIImageView, UILabel;

@interface ChallengeStatusView : UIView
{
    UIImageView *bgView;
    UIImage *numberTable[10];
    UIImageView *playCoinImage[3];
    UIImageView *playCoinLimitImage[3];
    UIImageView *playCoinSlash;
    UIImageView *cubeImage[5];
    UILabel *coinRestTime;
    UIButton *buyCube;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)alertSelect:(id)arg1;
- (void)tapBuyCube:(id)arg1;
- (void)timerUpdate;
- (void)updateDisplayStatus;
- (void)setNumberImage:(int)arg1 num:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

