//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ChallengePrevRankingListView, ChallengeRankingListView, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, UIButton, UIImageView, UILabel;

@interface ChallengePrevRankingView : UIView
{
    ChallengePrevRankingListView *lineupListView;
    ChallengeRankingListView *rankingListView;
    int scratchID;
    NSArray *lineupList;
    NSMutableDictionary *lineupImg;
    int selectLineupIndex;
    UIImageView *titleView;
    UILabel *titleLabel;
    struct CGRect listRect;
    UIButton *closeBtn;
    NSMutableArray *imageDLTasks;
    NSDictionary *currentDownload;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)closeLineupView;
- (void)showLineupList;
- (void)imageDownload;
- (_Bool)checkArtworkDownload;
- (void)alertSelect:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)closeList:(id)arg1;
- (void)selectListButton:(id)arg1;
- (void)closeRanking;
- (void)selectListCell:(id)arg1;
- (void)tapClose:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

