//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface ChallengeLoginMessageView : UIView
{
    UIView *bgCtrlView;
    UIImageView *bgView;
    UILabel *loginMessage;
    UILabel *loginMessage2;
    UIButton *closeBtn;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)closeMessage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 scratchNum:(int)arg2;

@end

