//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UITextField;

@interface ChallengeTextInputView : UIView <UITextFieldDelegate>
{
    UITextField *_nameBox;
    UIButton *_changeBtn;
    id _aDelegate;
    NSString *_inputText;
}

@property(readonly, nonatomic) NSString *inputText; // @synthesize inputText=_inputText;
@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
@property(retain, nonatomic) UIButton *changeBtn; // @synthesize changeBtn=_changeBtn;
@property(retain, nonatomic) UITextField *nameBox; // @synthesize nameBox=_nameBox;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)checkBlankString:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)isPictText:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)backUpFieldText;
- (void)commitName:(id)arg1;
- (void)setDefaultText:(id)arg1;
- (void)resetView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

