//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UIImageView, UILabel;

@interface ChallengeLineupViewCell : UITableViewCell
{
    UIImageView *bgImage;
    UIImageView *artworkImage;
    UILabel *nameLabel;
    UIButton *storeBtn;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)tapStoreMove;
- (void)setLineupCell:(id)arg1 name:(id)arg2 bgImg:(id)arg3 storeType:(int)arg4;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

