//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UIImageView, UILabel;

@interface CubePurchaseListViewCell : UITableViewCell
{
    UIButton *bgImage;
    UILabel *priceText;
    UILabel *descriptText;
    UIImageView *labelImg;
    UIImageView *numImg[5];
    id _aDelegate;
    UIButton *_addBtn;
}

@property(readonly, nonatomic) UIButton *addBtn; // @synthesize addBtn=_addBtn;
@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)setBgImage:(id)arg1 info:(id)arg2 cache:(id)arg3 aDelegate:(id)arg4;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 tag:(int)arg3;

@end

