//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ApplilinkURLConnectionDelegate-Protocol.h"

@interface DestinationCore : NSObject <ApplilinkURLConnectionDelegate>
{
}

- (_Bool)redirectStartLoad:(id)arg1;
- (void)finishLoadWithResponse:(id)arg1;
- (void)failLoadWithError:(id)arg1;
- (void)destinationRegistWithCountryCode:(id)arg1 url:(id)arg2 delegate:(id)arg3;

@end

