//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableData, NSURLConnection, NSURLRequest;

@interface Downloader : NSObject
{
    NSURLRequest *request;
    NSURLConnection *connection;
    NSMutableData *data;
    long long dl_size;
    id delegate;
    int _tag;
}

@property(nonatomic) int tag; // @synthesize tag=_tag;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getDataInJSON;
- (id)getData;
- (float)currentProgress;
- (unsigned long long)currentSize;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)cancel;
- (void)startDownloading;
- (id)initWithURL:(id)arg1 postData:(id)arg2 delegate:(id)arg3;
- (id)initWithURL:(id)arg1 delegate:(id)arg2;

@end

