//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "EditFileListViewController.h"

@class NSString, UILabel, UITableViewCell;

@interface EditFileListViewDeleteController : EditFileListViewController
{
    NSString *selectName;
    int fileCnt;
    int blankCnt;
    _Bool waitEnter;
    int slotLim;
    UITableViewCell *menuCell[2];
    int menuIndex[2];
    UILabel *sectionLabel[3];
    _Bool _isFirst;
    _Bool _isShared;
    int _tuneID;
    EditFileListViewDeleteController *_parentCtrl;
}

@property(retain, nonatomic) EditFileListViewDeleteController *parentCtrl; // @synthesize parentCtrl=_parentCtrl;
@property(nonatomic) int tuneID; // @synthesize tuneID=_tuneID;
@property(nonatomic) _Bool isShared; // @synthesize isShared=_isShared;
@property(nonatomic) _Bool isFirst; // @synthesize isFirst=_isFirst;
- (void).cxx_destruct;
- (void)reloadTable;
- (void)setFileList:(id)arg1;
- (void)setTargetFileName:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)getNewFileCell:(id)arg1 row:(int)arg2;
- (id)initWithSize:(struct CGSize)arg1;

@end

