//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView;

@interface EditorInfoCell : UITableViewCell
{
    UIImageView *_lockView;
}

@property(retain, nonatomic) UIImageView *lockView; // @synthesize lockView=_lockView;
- (void).cxx_destruct;
- (void)setUserTag:(int)arg1;
- (id)init;

@end

