//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface EditRendererConf : NSObject
{
    unsigned int _diff;
    unsigned int _level;
    unsigned int _tuneID;
    NSString *_markerID;
}

@property(nonatomic) unsigned int tuneID; // @synthesize tuneID=_tuneID;
@property(nonatomic) unsigned int level; // @synthesize level=_level;
@property(nonatomic) unsigned int diff; // @synthesize diff=_diff;
@property(nonatomic) NSString *markerID; // @synthesize markerID=_markerID;

@end

