//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, UIAlertView, jubeatLabAccess;

@interface EditorIDManager : NSObject
{
    NSURL *requestURL;
    jubeatLabAccess *idDownloader;
    UIAlertView *connectStoreAlert;
    id delegate;
}

+ (void)replaceKeyChain:(id)arg1;
+ (void)setKeyChain:(id)arg1 passwd:(id)arg2;
+ (id)createAddQueryG:(id)arg1;
+ (void)printKeychain;
+ (id)getKeyString:(id)arg1;
+ (void)deleteKeychain;
+ (void)deleteKeychainString:(id)arg1;
+ (_Bool)isExistEditorID;
+ (id)getEditorPassKey;
+ (id)getEditorIDKey;
+ (id)getKeyQuery:(id)arg1;
- (void).cxx_destruct;
- (void)jubeatLabAccessFinished:(id)arg1;
- (id)createAddQuery:(id)arg1;
- (void)jubeatLabAccessError:(id)arg1;
- (void)jubeatLabAccessProceed:(id)arg1;
- (void)cancel;
- (id)initWithDelegate:(id)arg1;

@end

