//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol EditFileListViewDelegate <NSObject>

@optional
- (void)editFileListViewDeleteFile:(NSString *)arg1;
- (void)editFileListViewSelectDownload;
- (void)editFileListViewSelectEdit;
- (void)editFileListViewSelectNewFile;
- (void)editFileListViewCancel;
- (void)editFileListViewSelectItem:(int)arg1;
@end

