//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableData, NSMutableDictionary;

@interface EditDataManager : NSObject
{
    NSMutableArray *sequenceTable;
    NSMutableDictionary *editorInfo;
    NSMutableDictionary *editSimpleData;
    NSMutableData *writeData;
    NSMutableDictionary *scoreData;
    unsigned int version;
    char musicBarTable[60];
    _Bool _bEnableCopy;
    _Bool _bIsDownload;
}

+ (id)sharedManager;
@property(nonatomic) _Bool bIsDownload; // @synthesize bIsDownload=_bIsDownload;
@property(readonly, nonatomic) _Bool bEnableCopy; // @synthesize bEnableCopy=_bEnableCopy;
- (void).cxx_destruct;
- (id)getCurrentCustomData;
- (int)getEditSlotLimit;
- (int)getMusicNum;
- (id)getMusicIDList;
- (void)scoreUpdate:(int)arg1 fullCombo:(_Bool)arg2 tuneID:(int)arg3;
- (_Bool)checkScoreHash;
- (id)getScoreHash:(int)arg1;
- (_Bool)IsExistEditFile:(int)arg1;
- (void)setLastEditFileName:(int)arg1 fileName:(id)arg2;
- (id)getLastEditFilePath:(int)arg1;
- (id)getLastEditFileName:(int)arg1;
- (void)setSequenceTable:(id)arg1;
- (id)getSequenceTable;
- (void)resetEditorInfo;
- (void)clearEditData;
- (void)setEditSimpleData:(id)arg1;
- (id)getEditSimpleData;
- (void)setEditorInfo:(id)arg1;
- (id)getEditorInfo;
- (void)setScoreData:(id)arg1;
- (id)getScoreData;
- (void)disableEdit;
- (_Bool)isEnableEdit;
- (id)getFileInfoList:(unsigned int)arg1;
- (_Bool)encodeBinary;
- (_Bool)decodeBinary;
- (id)pickUpSequenceTable:(char *)arg1;
- (id)pickUpEditSimpleData:(char *)arg1;
- (id)pickUpEditorInfo:(char *)arg1;
- (id)pickUpScoreData:(char *)arg1;
- (void)scoreDataReset;
- (_Bool)validateHash:(id)arg1;
- (unsigned int)getCharArrayValue:(char *)arg1 byte:(int)arg2;
- (void)setCharArray:(char *)arg1 setData:(unsigned int)arg2 byte:(int)arg3;
- (id)pickUpEditorInfoFromData:(id)arg1;
- (_Bool)localSaveDLFile:(id)arg1 serial:(id)arg2 usrTag:(int)arg3;
- (_Bool)checkDownloadFile:(id)arg1;
- (_Bool)checkDownLoad:(char *)arg1;
- (id)createDLString:(char *)arg1 isDL:(_Bool)arg2;
- (id)exeBFDec:(id)arg1;
- (id)exeBFEnc:(id)arg1;
- (id)exeLoadBFDec:(id)arg1;
- (id)exeSaveBFEnc:(id)arg1;
- (_Bool)createEditDataWithNSData:(id)arg1;
- (_Bool)saveJCF:(id)arg1;
- (_Bool)loadJCF:(id)arg1;
- (_Bool)deleteJCF:(id)arg1;
- (id)createJCFName;
- (id)getDirectoryPath:(int)arg1;
- (_Bool)addIgnoreBackUpAttribute:(id)arg1;
- (void)deleteCustomSequenceDirectory:(id)arg1;
- (id)getCustomSequenceDirectoryList;
- (id)init;

@end

