//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "EditNoteRenderer.h"

@class AVAudioPlayer, NSData, Texture2D;

@interface EditNoteRendererPad : EditNoteRenderer
{
    unsigned int frame;
    unsigned int subStateChangeFrame;
    unsigned int startMarkFrame;
    float lastHakuPhase;
    float bounceEnergy;
    unsigned int effSlot;
    float baseAlpha;
    float modeCnt;
    int conflictDot;
    NSData *clapSe;
    int clapSector;
    float dotBySec;
    float baseScale;
    float pinchScaleBak;
    Texture2D *_texFront;
    Texture2D *_texChip;
    Texture2D *_texDebugFont;
    AVAudioPlayer *_sePlayerGo;
}

@property(retain, nonatomic) AVAudioPlayer *sePlayerGo; // @synthesize sePlayerGo=_sePlayerGo;
@property(retain, nonatomic) Texture2D *texDebugFont; // @synthesize texDebugFont=_texDebugFont;
@property(retain, nonatomic) Texture2D *texChip; // @synthesize texChip=_texChip;
@property(retain, nonatomic) Texture2D *texFront; // @synthesize texFront=_texFront;
- (void).cxx_destruct;
- (struct CGRect)getTimeLineRect;
- (void)dealloc;
- (void)drawDebugText:(const char *)arg1 pos:(struct CGPoint)arg2 alpha:(float)arg3;
- (void)draw;
- (void)saveBaseScale;
- (void)setDbs:(float)arg1;
- (unsigned int)endButtonID;
- (double)buttonAreaOffset;
- (void)renderFinish;
- (void)renderFullcombo:(int)arg1 isResult:(_Bool)arg2;
- (void)renderPreStart;
- (void)renderButtons;
- (void)renderButtonLight:(int)arg1 atPoint:(struct CGPoint)arg2;
- (void)renderUpper;
- (void)renderUpperBG:(float)arg1;
- (void)renderTuneInfo:(struct CGPoint)arg1 artworkSize:(double)arg2 alpha:(double)arg3;
- (void)renderSequenceChip:(float)arg1;
- (void)renderSequenceParts:(int)arg1 event:(const CDStruct_009559ee *)arg2 basePos:(float)arg3 uniType:(int)arg4 alpha:(float)arg5;
- (void)renderPastLine:(float)arg1;
- (void)renderSelectArea:(float)arg1;
- (void)renderMeasureNum:(int)arg1 posX:(float)arg2 alpha:(float)arg3;
- (void)renderBaseLine:(float)arg1 lineType:(int)arg2 alpha:(float)arg3;
- (void)renderNoteChip:(float)arg1 keyIndex:(int)arg2 uniType:(int)arg3 alpha:(float)arg4;
- (struct CGRect)getAreaSelectEnd;
- (struct CGRect)getAreaSelectStart;
- (int)sector2pos:(int)arg1;
- (int)pos2sector:(int)arg1;
- (int)dot2sector:(int)arg1;
- (void)renderMusicBar:(struct CGPoint)arg1 timeline:(_Bool)arg2 alpha:(double)arg3;
- (void)renderShutter:(_Bool)arg1;
- (void)renderBG;
- (void)renderMarker;
- (void)drawClip:(int)arg1 drawPosition:(struct CGPoint)arg2 drawArea:(struct CGRect)arg3 alpha:(float)arg4;
- (void)resetCurrentTime;
- (void)endResult;
- (void)startPlay;
- (void)setState:(unsigned int)arg1;
- (void)releaseTexture;
- (void)loadTexure:(id)arg1 artwork:(id)arg2 index:(id)arg3;
- (id)init;

@end

