//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "EditFileListViewDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class CADisplayLink, EAGLView, EditButtonViewController, EditModalView, EditNoteRenderer, EditSequence, EditSystemMenuview, NSArray, NSData, NSMutableDictionary, NSString, SePlayer, TuneInfo, UIButton, UIImageView, UIPopoverController, UIView;

@interface EditViewController : UIViewController <UIPopoverControllerDelegate, EditFileListViewDelegate>
{
    _Bool isPad;
    double music_time;
    double music_duration;
    double sequence_duration;
    int loadCounter;
    _Bool isMusicPlaying;
    float buttonTouchWidth;
    unsigned int buttonDown;
    unsigned int buttonUp;
    unsigned int buttonPress;
    unsigned int buttonPressOld;
    unsigned int draw_count;
    double past_time;
    float fps;
    struct CGRect mbarRect;
    int edit_mode;
    int edit_type;
    _Bool bSeekMusicBar;
    float seekDefaultPos;
    unsigned int timeLineSector;
    _Bool bSeekTimeLine;
    _Bool bEnableSeekTimeLine;
    unsigned int timeLineSeekSector;
    float targetTime;
    int divMeasureType;
    _Bool bEnableControll;
    _Bool bLongPress;
    int startIndex;
    int endIndex;
    _Bool bEnablePaste;
    int pasteSector;
    int areaStartDefaultSec;
    int areaEndDefaultSec;
    int areaSelectTouchDelay;
    int areaDefaultWidth;
    _Bool bExistCopyData;
    NSArray *arraySwipeRecognizer;
    _Bool bEnableUndoBtn;
    _Bool bEnablePanel;
    _Bool bClapReset;
    unsigned int clapID;
    int clapSector;
    _Bool bEnableClap;
    _Bool bEnableGesture;
    UIPopoverController *pTemplateListView;
    EditSystemMenuview *pFileListView;
    struct CGPoint touchPointBack;
    int selectTemplateNum;
    NSMutableDictionary *templateInfo[4];
    NSMutableDictionary *newEditorInfo;
    _Bool isFirstPlaying;
    SePlayer *sePlayer;
    EditModalView *pEditModalView;
    EditButtonViewController *btnList;
    _Bool bLoadTemplate;
    _Bool ignorePress;
    float adjustTime;
    unsigned int _currentDiff;
    TuneInfo *_currentTune;
    NSString *_jcfName;
    NSString *_currentMarker;
    NSData *_musicData;
    EAGLView *_glView;
    EditNoteRenderer *_mainGameRenderer;
    CADisplayLink *_displayLink;
    EditSequence *_sequence;
    UIButton *_btnPause;
    UIButton *_btnMode;
    UIButton *_btnSysMenu;
    UIButton *_btnClap;
    UIImageView *_clapBtnView;
    UIButton *_btnRewind;
    UIButton *_btnHelp;
    UIButton *_btnSelGrid;
    UIButton *_btnAreaCpy;
    UIButton *_btnAreaDel;
    UIButton *_btnAreaPst;
    UIButton *_btnUndo;
    UIButton *_btnRedo;
    NSArray *_editData;
    NSMutableDictionary *_editorInfo;
    NSMutableDictionary *_editSimpleData;
    UIView *_timeLineView;
}

@property(retain, nonatomic) UIView *timeLineView; // @synthesize timeLineView=_timeLineView;
@property(retain, nonatomic) NSMutableDictionary *editSimpleData; // @synthesize editSimpleData=_editSimpleData;
@property(retain, nonatomic) NSMutableDictionary *editorInfo; // @synthesize editorInfo=_editorInfo;
@property(retain, nonatomic) NSArray *editData; // @synthesize editData=_editData;
@property(retain, nonatomic) UIButton *btnRedo; // @synthesize btnRedo=_btnRedo;
@property(retain, nonatomic) UIButton *btnUndo; // @synthesize btnUndo=_btnUndo;
@property(retain, nonatomic) UIButton *btnAreaPst; // @synthesize btnAreaPst=_btnAreaPst;
@property(retain, nonatomic) UIButton *btnAreaDel; // @synthesize btnAreaDel=_btnAreaDel;
@property(retain, nonatomic) UIButton *btnAreaCpy; // @synthesize btnAreaCpy=_btnAreaCpy;
@property(retain, nonatomic) UIButton *btnSelGrid; // @synthesize btnSelGrid=_btnSelGrid;
@property(retain, nonatomic) UIButton *btnHelp; // @synthesize btnHelp=_btnHelp;
@property(retain, nonatomic) UIButton *btnRewind; // @synthesize btnRewind=_btnRewind;
@property(retain, nonatomic) UIImageView *clapBtnView; // @synthesize clapBtnView=_clapBtnView;
@property(retain, nonatomic) UIButton *btnClap; // @synthesize btnClap=_btnClap;
@property(retain, nonatomic) UIButton *btnSysMenu; // @synthesize btnSysMenu=_btnSysMenu;
@property(retain, nonatomic) UIButton *btnMode; // @synthesize btnMode=_btnMode;
@property(retain, nonatomic) UIButton *btnPause; // @synthesize btnPause=_btnPause;
@property(retain, nonatomic) EditSequence *sequence; // @synthesize sequence=_sequence;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) EditNoteRenderer *mainGameRenderer; // @synthesize mainGameRenderer=_mainGameRenderer;
@property(retain, nonatomic) EAGLView *glView; // @synthesize glView=_glView;
@property(retain, nonatomic) NSData *musicData; // @synthesize musicData=_musicData;
@property(nonatomic) NSString *currentMarker; // @synthesize currentMarker=_currentMarker;
@property(nonatomic) unsigned int currentDiff; // @synthesize currentDiff=_currentDiff;
@property(retain, nonatomic) NSString *jcfName; // @synthesize jcfName=_jcfName;
@property(retain, nonatomic) TuneInfo *currentTune; // @synthesize currentTune=_currentTune;
- (void).cxx_destruct;
- (float)reverseAdjustTime:(float)arg1;
- (float)adjustTime:(float)arg1;
- (void)editModalViewDelegateSaveEditFile;
- (void)editModalViewClose:(id)arg1;
- (void)alertSelect:(id)arg1;
- (void)editBtnSelect:(id)arg1 tag:(id)arg2;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)editFileListViewDecideItem:(int)arg1;
- (void)editFileListViewCancel;
- (void)selectSave;
- (void)selectExit;
- (void)selectLoadSlot:(id)arg1;
- (void)templateRelease;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)terminate;
- (void)resume;
- (void)suspend;
- (void)end;
- (void)endInPauseView;
- (void)resumeInPauseView;
- (void)dpGesture:(id)arg1;
- (void)tapGesture:(id)arg1;
- (void)longPressGesture:(id)arg1;
- (void)resetGesture;
- (void)resetLongPress;
- (void)resetPaste;
- (void)handleSwipe:(id)arg1;
- (void)createTimeLineView;
- (void)pushRewind:(id)arg1;
- (void)pushHelp:(id)arg1;
- (void)pushClap:(id)arg1;
- (void)pushAreaPaste2:(id)arg1;
- (void)pushAreaPaste:(id)arg1;
- (void)pushAreaDelete:(id)arg1;
- (void)pushAreaCopy:(id)arg1;
- (void)ReleaseSelectArea;
- (void)longPressEnable:(_Bool)arg1;
- (void)selectGridType:(int)arg1;
- (void)pushBtnGridChange:(id)arg1;
- (void)pushbtnSysMenu:(id)arg1;
- (void)pushBtnRedo:(id)arg1;
- (void)pushBtnUndo:(id)arg1;
- (void)pinchGesture:(id)arg1;
- (void)longPressBtnMode:(id)arg1;
- (void)pushBtnMode:(id)arg1;
- (void)pushBtnDelete:(id)arg1;
- (void)pushBtnAdd:(id)arg1;
- (void)changeModeImage:(id)arg1;
- (void)deletePasteBtn;
- (void)pushBtnPause:(id)arg1;
- (void)startGame;
- (void)exeClap;
- (void)loop:(id)arg1;
- (void)controllMusic;
- (void)stopMusic;
- (void)deleteNote;
- (void)addNote:(_Bool)arg1;
- (void)finishMusic:(id)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (void)saveScore;
- (void)releaseResources;
- (void)loadResources;
- (void)loadView;
- (void)setGridButton:(id)arg1 type:(int)arg2 pos:(struct CGPoint)arg3;
- (id)init;
- (void)resetEditMember;
- (void)saveNotesData;
- (void)autoSave:(_Bool)arg1;
- (void)importNotesData:(id)arg1;
- (void)loadNotesData;
- (id)getDirectoryPath:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

