//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UILabel, UITableView, UIView;
@protocol EditFileListViewDelegate;

@interface EditFileListViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource>
{
    UILabel *labelMessage;
    UITableView *tableFiles;
    UIView *shadowView;
    id <EditFileListViewDelegate> _delegate;
    NSMutableArray *_fileList;
}

+ (Class)layerClass;
@property(retain, nonatomic) NSMutableArray *fileList; // @synthesize fileList=_fileList;
@property(nonatomic) __weak id <EditFileListViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)initWithSize:(struct CGSize)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

