//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString;

@interface EditButtonViewController : UIViewController
{
    id delegate;
    NSString *myName;
}

- (void).cxx_destruct;
- (void)pushBtn:(id)arg1;
- (id)initWithButtonArray:(id)arg1 selNum:(int)arg2 delegate:(id)arg3 ctrlName:(id)arg4;

@end

