//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Texture2D;

@interface EffectBgKnit : NSObject
{
    int type_;
    struct CGPoint drawPos_;
    int frame_;
    Texture2D *pDrawTex_;
    int totalFrame_;
    int width_;
    int wmin_;
    int wmax_;
    int move_;
}

- (void).cxx_destruct;
- (_Bool)renderEffect;
- (void)init:(id)arg1 effType:(int)arg2 startPos:(struct CGPoint)arg3 wmin:(int)arg4 wmax:(int)arg5 move:(int)arg6;
- (float)expand:(int)arg1 totalFrame:(int)arg2 max:(float)arg3;

@end

