//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface frameTableCell : UITableViewCell
{
    UIImageView *icon;
    UILabel *itemLabel;
    UILabel *pointLabel;
    UIImageView *lockIcon;
}

- (void).cxx_destruct;
- (void)setInfo:(id)arg1;
- (id)initWithWidth:(int)arg1;

@end

