//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface FrameLockView : UIView
{
    UIView *bgView;
    UIImageView *lockIcon;
    UILabel *lockText;
    struct CGRect parentFrame;
}

- (void).cxx_destruct;
- (void)setLockTextDisp:(_Bool)arg1;
- (void)setUnlockNumber:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1 unlockNumber:(int)arg2;

@end

