//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol GamePauseViewDelegate;

@interface GamePauseView : UIView
{
    UIView *frameView;
    UIButton *btnResume;
    UIButton *btnRestart;
    UIButton *btnEnd;
    id <GamePauseViewDelegate> _delegate;
}

@property(nonatomic) __weak id <GamePauseViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)pushBtnEnd:(id)arg1;
- (void)pushBtnRestart:(id)arg1;
- (void)pushBtnResume:(id)arg1;
- (void)showInView:(id)arg1 animated:(_Bool)arg2;
- (id)soundName:(id)arg1;
- (id)init;

@end

