//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "GamePauseViewDelegate-Protocol.h"
#import "SharePlayManagerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class CADisplayLink, Downloader, EAGLView, EditorIDManager, EvaluateJcfView, GamePauseView, MainGameRenderer, NSData, NSString, RendererConf, ResultItemChance, SearchPackIDView, Sequence, SharePlayManager, TuneInfo, UIButton, UIImage, UIImageView, UIView, jubeatLabAccess;

@interface GameViewController : UIViewController <UIPopoverControllerDelegate, GamePauseViewDelegate, SharePlayManagerDelegate>
{
    _Bool isPad;
    _Bool isSession;
    _Bool scoreSaved;
    _Bool isCustom;
    _Bool isDownload;
    _Bool hasMusic;
    double music_time;
    _Bool isMusicPlaying;
    float buttonTouchWidth;
    unsigned int buttonDown;
    unsigned int buttonUp;
    unsigned int buttonPress;
    unsigned int buttonPressOld;
    unsigned int draw_count;
    double past_time;
    float fps;
    int oldBestScore;
    SearchPackIDView *packSearchView;
    UIView *coverView;
    EvaluateJcfView *evaluateView;
    jubeatLabAccess *playCountAccess;
    _Bool bGoodJobPress;
    jubeatLabAccess *goodJobCommit;
    RendererConf *confBak;
    UIImage *indexWBak;
    UIImage *indexBBak;
    _Bool bIsOpenSocialSend;
    Downloader *scoreUploader;
    EditorIDManager *idManager;
    float adjustTime;
    _Bool bRestartFlag;
    float displayScale;
    ResultItemChance *itemChanceRender;
    _Bool bItemChance;
    int chanceItemType;
    int chanceItemNum;
    unsigned int _currentDiff;
    TuneInfo *_currentTune;
    NSString *_currentMarker;
    SharePlayManager *_shareManager;
    NSData *_musicData;
    EAGLView *_glView;
    MainGameRenderer *_mainGameRenderer;
    CADisplayLink *_displayLink;
    Sequence *_sequence;
    UIButton *_btnPause;
    UIImageView *_btnStoreMove;
    UIImageView *_btnGoodJob;
    UIImageView *_goodJobTxt;
    UIImageView *_twitterBtn;
    GamePauseView *_pauseView;
}

@property(retain, nonatomic) GamePauseView *pauseView; // @synthesize pauseView=_pauseView;
@property(retain, nonatomic) UIImageView *twitterBtn; // @synthesize twitterBtn=_twitterBtn;
@property(retain, nonatomic) UIImageView *goodJobTxt; // @synthesize goodJobTxt=_goodJobTxt;
@property(retain, nonatomic) UIImageView *btnGoodJob; // @synthesize btnGoodJob=_btnGoodJob;
@property(retain, nonatomic) UIImageView *btnStoreMove; // @synthesize btnStoreMove=_btnStoreMove;
@property(retain, nonatomic) UIButton *btnPause; // @synthesize btnPause=_btnPause;
@property(retain, nonatomic) Sequence *sequence; // @synthesize sequence=_sequence;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) MainGameRenderer *mainGameRenderer; // @synthesize mainGameRenderer=_mainGameRenderer;
@property(retain, nonatomic) EAGLView *glView; // @synthesize glView=_glView;
@property(retain, nonatomic) NSData *musicData; // @synthesize musicData=_musicData;
@property(retain, nonatomic) SharePlayManager *shareManager; // @synthesize shareManager=_shareManager;
@property(nonatomic) NSString *currentMarker; // @synthesize currentMarker=_currentMarker;
@property(nonatomic) unsigned int currentDiff; // @synthesize currentDiff=_currentDiff;
@property(retain, nonatomic) TuneInfo *currentTune; // @synthesize currentTune=_currentTune;
- (void).cxx_destruct;
- (void)panelChanceClose;
- (void)alertSelect:(id)arg1;
- (void)sendChallengeScore;
- (void)releaseSearchPackView;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)successIDDownload:(id)arg1;
- (void)errorIDDownload:(id)arg1 msgStr:(id)arg2;
- (void)packIDSearchCancel:(id)arg1;
- (void)packIDSearchEnd:(id)arg1;
- (void)createSearchBtn;
- (void)sendTwitter:(id)arg1 mesStr:(id)arg2;
- (void)createTwitterBtn;
- (void)pushBtnGoodJob;
- (void)createGoodJobBtn;
- (void)dealloc;
- (void)jubeatLabAccessFinished:(id)arg1;
- (void)jubeatLabAccessError:(id)arg1;
- (void)requestAddPlayCount;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)terminate;
- (void)resume;
- (void)suspend;
- (void)sharePlayManager:(id)arg1 receiveFinalScore:(int)arg2 bonus:(int)arg3 fullCombo:(_Bool)arg4;
- (void)sharePlayManager:(id)arg1 receiveScore:(int)arg2;
- (void)sharePlayManagerMusicStartTimeOut:(id)arg1;
- (void)sharePlayManager:(id)arg1 startMusicTime:(float)arg2;
- (void)sharePlayManagerAllClientLoaded:(id)arg1;
- (void)sharePlayManagerFailWithError:(id)arg1;
- (void)sharePlayManager:(id)arg1 disconnectClient:(id)arg2;
- (void)sharePlayManagerDisconnect:(id)arg1;
- (void)closeEvaluate:(id)arg1;
- (void)removeEvaluate;
- (void)sessionDisconnect:(_Bool)arg1;
- (void)end;
- (void)endInPauseView;
- (void)resumeInPauseView;
- (void)restartInPauseView;
- (void)pushBtnPause:(id)arg1;
- (void)restartGame;
- (void)startGame;
- (void)loop:(id)arg1;
- (void)finishMusic:(id)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (void)saveScore;
- (void)releaseResources;
- (void)loadResources;
- (void)loadView;
- (id)soundName:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

