//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Texture2D;

@interface HoldMarkerRender : NSObject
{
    Texture2D *drawTex;
    _Bool isPad;
    int gameAreaDelay;
}

- (void).cxx_destruct;
- (void)renderHoldMarker:(CDStruct_0f097b75 *)arg1;
- (void)renderHoldMarker:(CDStruct_0f097b75)arg1 end:(int)arg2;
- (void)renderHoldLine:(struct CGPoint)arg1 start:(struct CGPoint)arg2 vector:(int)arg3 trans:(BOOL)arg4 alpha:(float)arg5 frame:(int)arg6 addLength:(int)arg7;
- (id)init:(id)arg1 isPad:(_Bool)arg2 gameAreaDelay:(int)arg3;

@end

