//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface HostClass : NSObject
{
    NSData *_musicData;
    _Bool _dataLoaded;
    int _score;
    int _finalBonus;
    _Bool _fullcombo;
    _Bool _finished;
}

@property(nonatomic) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic) _Bool fullcombo; // @synthesize fullcombo=_fullcombo;
@property(nonatomic) int finalBonus; // @synthesize finalBonus=_finalBonus;
@property(nonatomic) int score; // @synthesize score=_score;
@property(nonatomic) _Bool dataLoaded; // @synthesize dataLoaded=_dataLoaded;
@property(retain, nonatomic) NSData *musicData; // @synthesize musicData=_musicData;
- (void).cxx_destruct;

@end

