//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import "UIWebViewDelegate-Protocol.h"

@class JcfDownloadPageViewController, NSString, NSURLRequest, UIWebView;

@interface JcfDownloadPageNavController : UINavigationController <UIWebViewDelegate>
{
    NSURLRequest *requestURL;
    unsigned int sequenceID;
    _Bool bSuccess;
    id delegate;
    UIWebView *downloadPage;
    JcfDownloadPageViewController *ctrl;
    unsigned int loadMid;
    NSString *loadSeqID;
    NSString *loadURL;
}

- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)pushClose:(id)arg1;
- (id)initWithURL:(id)arg1 delegate:(id)arg2;
- (id)initWithSequenceID:(id)arg1 delegate:(id)arg2;
- (id)initWithMusicID:(unsigned int)arg1 delegate:(id)arg2;
- (void)initNavigationBar;
- (id)createCustomSequenceURL:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

