//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JcfDownloader, NSString, NSURL, StoreButton, UIActivityIndicatorView, UILabel;

@interface JcfDownloadView : UIView
{
    UIView *coverBoard;
    UILabel *labelMessage;
    UIView *shadowView;
    StoreButton *btnCancel;
    StoreButton *btnOK;
    StoreButton *btnEnd;
    UIActivityIndicatorView *indicatorView;
    NSURL *requestURL;
    JcfDownloader *jcfDownloader;
    unsigned int sequenceID;
    _Bool bEnableSocialFrameWork;
    NSString *packID;
    int musicID;
    UILabel *textLabel;
    id delegate;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (int)getDownloadMusicID;
- (void)finishedSequenceDownload:(id)arg1 tuneID:(id)arg2;
- (void)finishedSequenceNotExistPack:(id)arg1 packID:(id)arg2;
- (void)finishedSequenceOverCap:(id)arg1;
- (void)errorSequenceDownload:(id)arg1 msgStr:(id)arg2;
- (void)downloadEnd;
- (void)startDownload;
- (void)pushMoveStore:(id)arg1;
- (void)pushCancel:(id)arg1;
- (id)initWithID:(id)arg1 delegate:(id)arg2;
- (void)createStoreBtn:(id)arg1;

@end

