//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class EditorIDManager, NSString, NSURL, jubeatLabAccess;

@interface JcfDownloader : NSObject
{
    NSURL *requestURL;
    jubeatLabAccess *seqDownloader;
    jubeatLabAccess *packInfoDownloader;
    unsigned int packID;
    NSString *customID;
    id delegate;
    EditorIDManager *eidMan;
}

- (void).cxx_destruct;
- (void)errorIDDownload:(id)arg1 msgStr:(id)arg2;
- (void)successIDDownload:(id)arg1;
- (void)jubeatLabAccessFinished:(id)arg1;
- (_Bool)isExistJbtFile:(unsigned int)arg1;
- (void)downloadFailedDelegate;
- (void)jubeatLabAccessError:(id)arg1;
- (void)jubeatLabAccessProceed:(id)arg1;
- (void)downloadStart;
- (id)initWithCustomID:(id)arg1 delegate:(id)arg2;
- (id)createCustomSequenceURL:(unsigned int)arg1;

@end

