//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class EditorIDManager, NSData, NSURL, UIAlertView, jubeatLabAccess;

@interface JcfUploader : NSObject
{
    NSURL *requestURL;
    jubeatLabAccess *seqUploader;
    _Bool bSuccess;
    id delegate;
    _Bool bEnableSocialFrameWork;
    EditorIDManager *eidMan;
    UIAlertView *eidAlert;
    NSData *uploadData;
}

- (void).cxx_destruct;
- (void)errorIDDownload:(id)arg1 msgStr:(id)arg2;
- (void)successIDDownload:(id)arg1;
- (void)jubeatLabAccessFinished:(id)arg1;
- (void)jubeatLabAccessError:(id)arg1;
- (void)jubeatLabAccessProceed:(id)arg1;
- (void)sendErrorDelegate:(id)arg1;
- (void)uploadStart;
- (void)start;
- (id)initWithData:(id)arg1 delegate:(id)arg2;
- (id)getKeyString:(id)arg1;

@end

