//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIApplicationDelegate-Protocol.h"

@class NSMutableArray, NSString, NSURL, RootViewController, UIColor, UIWindow;

@interface JubeatAppDelegate : NSObject <UIApplicationDelegate>
{
    UIWindow *mainWindow;
    _Bool _gameCenterAvailable;
    _Bool _isRandom;
    _Bool _isMarkerLegal;
    _Bool _isExtend;
    _Bool _isHold;
    _Bool _bChallengeOpen;
    _Bool _bChallengeMode;
    _Bool _bEnableReward;
    _Bool _bSendPushID;
    unsigned int _currentTheme;
    unsigned int _challengeMusicID;
    int _challengeDifficulty;
    int _totalPurchaseAmount;
    int _hasNewRecommendNum;
    RootViewController *_rootViewCtrl;
    NSString *_userAgent;
    unsigned long long _deviceType;
    NSString *_jcfDownloadID;
    NSURL *_notificationURL;
    NSString *_notificationTime;
    NSString *_storePackID;
    NSString *_storeCampaignID;
    NSString *_searchString;
    NSMutableArray *_markerList;
    UIColor *_knitWaveBgColor;
    UIColor *_knitWaveLineColor;
    UIColor *_knitWaveColor;
    NSMutableArray *_pushNotificationList;
    NSString *_deviceToken;
}

+ (id)clientInfo;
+ (id)deviceName;
+ (id)appVersion;
+ (id)appCachesDirectory;
+ (id)appDocumentsDirectory;
+ (id)appLibraryDirectory;
+ (id)appDelegate;
+ (void)initialize;
@property(readonly, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(nonatomic) _Bool bSendPushID; // @synthesize bSendPushID=_bSendPushID;
@property(readonly, nonatomic) _Bool bEnableReward; // @synthesize bEnableReward=_bEnableReward;
@property(nonatomic) int hasNewRecommendNum; // @synthesize hasNewRecommendNum=_hasNewRecommendNum;
@property(readonly, nonatomic) NSMutableArray *pushNotificationList; // @synthesize pushNotificationList=_pushNotificationList;
@property(readonly, nonatomic) int totalPurchaseAmount; // @synthesize totalPurchaseAmount=_totalPurchaseAmount;
@property(readonly, nonatomic) int challengeDifficulty; // @synthesize challengeDifficulty=_challengeDifficulty;
@property(readonly, nonatomic) unsigned int challengeMusicID; // @synthesize challengeMusicID=_challengeMusicID;
@property(readonly, nonatomic) _Bool bChallengeMode; // @synthesize bChallengeMode=_bChallengeMode;
@property(readonly, nonatomic) _Bool bChallengeOpen; // @synthesize bChallengeOpen=_bChallengeOpen;
@property(readonly, nonatomic) UIColor *knitWaveColor; // @synthesize knitWaveColor=_knitWaveColor;
@property(readonly, nonatomic) UIColor *knitWaveLineColor; // @synthesize knitWaveLineColor=_knitWaveLineColor;
@property(readonly, nonatomic) UIColor *knitWaveBgColor; // @synthesize knitWaveBgColor=_knitWaveBgColor;
@property(readonly, nonatomic) NSMutableArray *markerList; // @synthesize markerList=_markerList;
@property(readonly, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(readonly, nonatomic) NSString *storeCampaignID; // @synthesize storeCampaignID=_storeCampaignID;
@property(readonly, nonatomic) NSString *storePackID; // @synthesize storePackID=_storePackID;
@property(readonly, nonatomic) _Bool isHold; // @synthesize isHold=_isHold;
@property(readonly, nonatomic) _Bool isExtend; // @synthesize isExtend=_isExtend;
@property(readonly, nonatomic) _Bool isMarkerLegal; // @synthesize isMarkerLegal=_isMarkerLegal;
@property(readonly, nonatomic) _Bool isRandom; // @synthesize isRandom=_isRandom;
@property(readonly, nonatomic) NSString *notificationTime; // @synthesize notificationTime=_notificationTime;
@property(readonly, nonatomic) NSURL *notificationURL; // @synthesize notificationURL=_notificationURL;
@property(readonly, nonatomic) NSString *jcfDownloadID; // @synthesize jcfDownloadID=_jcfDownloadID;
@property(readonly, nonatomic) unsigned int currentTheme; // @synthesize currentTheme=_currentTheme;
@property(readonly, nonatomic) unsigned long long deviceType; // @synthesize deviceType=_deviceType;
@property(readonly, nonatomic) _Bool gameCenterAvailable; // @synthesize gameCenterAvailable=_gameCenterAvailable;
@property(readonly, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(readonly, nonatomic) RootViewController *rootViewCtrl; // @synthesize rootViewCtrl=_rootViewCtrl;
- (void).cxx_destruct;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (id)popNotification;
- (_Bool)pushActiveCheck:(long long)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)loadNotification;
- (void)saveNotification;
- (id)getNotificationFilePath;
- (void)refreshUserAgent;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2;
- (_Bool)digitStringCheck:(id)arg1;
- (void)setKnitColor:(id)arg1;
- (void)rewardEnable;
- (void)setTotalAmount:(int)arg1;
- (void)setChallengeMusic:(unsigned int)arg1 diff:(int)arg2;
- (void)setChallengeMode:(_Bool)arg1;
- (void)moveChallengeOpenFlag;
- (void)dropChallengeOpenFlag;
- (id)getCurrentLicenseMessage;
- (id)getCurrentLicenseDate;
- (void)markerDownloadComplete;
- (void)setSearchString:(id)arg1;
- (void)setHoldFlag:(_Bool)arg1;
- (void)setExtendFlag:(_Bool)arg1;
- (void)setRandomFlag:(_Bool)arg1;
- (void)setNotificationPageURL:(id)arg1 updateTime:(id)arg2;
- (void)setCampaignID:(id)arg1;
- (void)resetCampaignID;
- (void)setDownloadPackID:(id)arg1;
- (void)resetDownloadPackID;
- (void)resetDownLoadIndex;
- (id)musicListKey;
- (void)enableCopiousMarkers;
- (void)changeTheme:(unsigned int)arg1;
- (id)totalScoreLeaderboardCategory;
- (void)loginGameCenter;
- (void)disableGameCenter;
- (id)gameCenterName;
@property(readonly, nonatomic) _Bool isPadRetina;
@property(readonly, nonatomic) _Bool is4inchAspect;
@property(readonly, nonatomic) _Bool isPhoneRetina;
@property(readonly, nonatomic) _Bool isPad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

