//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSFileHandle;

@interface KUnzip : NSObject
{
    void *zipfile;
    unsigned char buffer[65536];
    NSFileHandle *_fileHandle;
    NSData *_data;
    unsigned long long _dataCurrentPos;
    struct _NSRange _dataRange;
}

@property(readonly, nonatomic) struct _NSRange dataRange; // @synthesize dataRange=_dataRange;
@property(nonatomic) unsigned long long dataCurrentPos; // @synthesize dataCurrentPos=_dataCurrentPos;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
- (void).cxx_destruct;
- (void)dealloc;
- (id)uncompress:(id)arg1;
- (id)fileList;
- (unsigned long long)uncompressedSize:(id)arg1;
- (_Bool)fileExists:(id)arg1;
- (id)initWithData:(id)arg1 range:(struct _NSRange)arg2;
- (id)initWithPath:(id)arg1 tail:(unsigned long long)arg2;
- (id)initWithPath:(id)arg1;

@end

