//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class Downloader, NSTimer, UIImageView;

@interface LogoViewController : UIViewController
{
    unsigned int state;
    _Bool closing;
    UIImageView *konamiLogoView;
    UIImageView *bemaniLogoView;
    NSTimer *endTimer;
    Downloader *knitBgDownloader;
}

- (void).cxx_destruct;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)handleTap:(id)arg1;
- (void)end:(id)arg1;
- (void)start;
- (void)fireAnimation;
- (void)loadView;
- (id)init;

@end

