//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MainGameRenderer.h"

@class AVAudioPlayer, NSMutableArray, Texture2D;

@interface MainGameRendererPadRpl : MainGameRenderer
{
    unsigned int frame;
    unsigned int subStateChangeFrame;
    unsigned int startMarkFrame;
    float lastHakuPhase;
    float bounceEnergy;
    Texture2D *texReady0;
    Texture2D *texReady1;
    Texture2D *texFront;
    Texture2D *texMarker;
    Texture2D *texHoldMarker;
    Texture2D *texCombo;
    Texture2D *texResult;
    Texture2D *texDebugFont;
    AVAudioPlayer *sePlayerGo;
    NSMutableArray *arrayBgRip;
    NSMutableArray *arrayUpperBgRip;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)drawDebugText:(const char *)arg1 pos:(struct CGPoint)arg2 alpha:(float)arg3;
- (void)draw;
- (void)renderResult;
- (struct CGPoint)storeMoveBtnPosition;
- (unsigned int)storeMoveButtonID;
- (struct CGPoint)twitterBtnPosition;
- (unsigned int)twitterSendButtonID;
- (struct CGPoint)goodJobPosition;
- (unsigned int)goodJobButtonID;
- (unsigned int)evaluateButtonID;
- (unsigned int)endButtonID;
- (double)gameAreaOffset;
- (double)buttonAreaOffset;
- (_Bool)renderFailed:(unsigned int)arg1;
- (_Bool)renderCleared:(unsigned int)arg1;
- (void)renderRating:(unsigned int)arg1;
- (_Bool)renderExcellent:(unsigned int)arg1;
- (void)renderFinish;
- (void)renderFullcombo:(int)arg1;
- (void)renderReadyGo;
- (double)durationOfReadyGo;
- (void)renderPreStart;
- (void)renderButtons;
- (void)renderUpper;
- (void)renderUpperBG:(_Bool)arg1;
- (void)renderTuneInfo:(struct CGPoint)arg1 artworkSize:(double)arg2 alpha:(double)arg3;
- (void)renderMusicBar:(struct CGPoint)arg1 timeline:(_Bool)arg2 alpha:(double)arg3;
- (void)renderPartnerScore:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 scale:(double)arg3 alpha:(double)arg4;
- (void)renderScore:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 alpha:(double)arg3;
- (void)renderUpdatedScore:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 alpha:(double)arg3;
- (void)renderCombo:(unsigned int)arg1 alpha:(float)arg2;
- (void)renderShutter:(_Bool)arg1;
- (void)renderBG;
- (void)renderMarker;
- (void)renderStartMark:(float)arg1;
- (void)endResult;
- (void)startPlay;
- (void)setState:(unsigned int)arg1;
- (void)releaseTexture;
- (void)loadResultTex:(short)arg1;
- (void)loadTexure:(id)arg1 artwork:(id)arg2 index:(id)arg3;
- (id)init;

@end

