//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MainGameRenderer.h"

@class AVAudioPlayer, NSMutableArray, Texture2D;

@interface MainGameRendererPhoneRpl : MainGameRenderer
{
    _Bool isRetina;
    _Bool is4Inch;
    unsigned int frame;
    unsigned int subStateChangeFrame;
    unsigned int startMarkFrame;
    float lastHakuPhase;
    float bounceEnergy;
    Texture2D *_texReady0;
    Texture2D *_texReady1;
    Texture2D *_texFront;
    Texture2D *_texMarker;
    Texture2D *_texHoldMarker;
    Texture2D *_texCombo;
    Texture2D *_texDebugFont;
    AVAudioPlayer *_sePlayerGo;
    NSMutableArray *_arrayBgRip;
    NSMutableArray *_arrayUpperBgRip;
}

@property(retain, nonatomic) NSMutableArray *arrayUpperBgRip; // @synthesize arrayUpperBgRip=_arrayUpperBgRip;
@property(retain, nonatomic) NSMutableArray *arrayBgRip; // @synthesize arrayBgRip=_arrayBgRip;
@property(retain, nonatomic) AVAudioPlayer *sePlayerGo; // @synthesize sePlayerGo=_sePlayerGo;
@property(retain, nonatomic) Texture2D *texDebugFont; // @synthesize texDebugFont=_texDebugFont;
@property(retain, nonatomic) Texture2D *texCombo; // @synthesize texCombo=_texCombo;
@property(retain, nonatomic) Texture2D *texHoldMarker; // @synthesize texHoldMarker=_texHoldMarker;
@property(retain, nonatomic) Texture2D *texMarker; // @synthesize texMarker=_texMarker;
@property(retain, nonatomic) Texture2D *texFront; // @synthesize texFront=_texFront;
@property(retain, nonatomic) Texture2D *texReady1; // @synthesize texReady1=_texReady1;
@property(retain, nonatomic) Texture2D *texReady0; // @synthesize texReady0=_texReady0;
- (void).cxx_destruct;
- (void)dealloc;
- (void)drawDebugText:(const char *)arg1 pos:(struct CGPoint)arg2 alpha:(float)arg3;
- (void)draw;
- (void)renderResult;
- (struct CGPoint)storeMoveBtnPosition;
- (unsigned int)storeMoveButtonID;
- (struct CGPoint)twitterBtnPosition;
- (unsigned int)twitterSendButtonID;
- (struct CGPoint)goodJobPosition;
- (unsigned int)goodJobButtonID;
- (unsigned int)evaluateButtonID;
- (unsigned int)endButtonID;
- (double)gameAreaOffset;
- (double)buttonAreaOffset;
- (_Bool)renderFailed:(unsigned int)arg1;
- (_Bool)renderCleared:(unsigned int)arg1;
- (void)renderRating:(unsigned int)arg1;
- (_Bool)renderExcellent:(unsigned int)arg1;
- (void)renderFinish;
- (void)renderFullcombo:(int)arg1;
- (void)renderReadyGo;
- (double)durationOfReadyGo;
- (void)renderPreStart;
- (void)renderButtons;
- (void)renderUpper;
- (void)renderUpperBG:(_Bool)arg1;
- (void)renderTuneInfo:(struct CGPoint)arg1 artworkSize:(double)arg2 alpha:(double)arg3;
- (void)renderMusicBar:(struct CGPoint)arg1 timeline:(_Bool)arg2 alpha:(double)arg3;
- (void)renderPartnerScore:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 scale:(double)arg3 alpha:(double)arg4;
- (void)renderScore:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 alpha:(double)arg3;
- (void)renderUpdatedScore:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 alpha:(double)arg3;
- (void)renderCombo:(unsigned int)arg1 alpha:(float)arg2;
- (void)renderShutter:(_Bool)arg1;
- (void)renderBG;
- (void)renderMarker;
- (void)renderStartMark:(float)arg1;
- (void)endResult;
- (void)startPlay;
- (void)setState:(unsigned int)arg1;
- (void)releaseTexture;
- (void)loadResultTex:(short)arg1;
- (void)loadTexure:(id)arg1 artwork:(id)arg2 index:(id)arg3;
- (id)init;

@end

