//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MainGameRenderer.h"

@class Texture2D;

@interface MainGameRendererPhone : MainGameRenderer
{
    _Bool isRetina;
    _Bool is4Inch;
    unsigned int frame;
    unsigned int subStateChangeFrame;
    Texture2D *texFront;
    Texture2D *texMarker;
    Texture2D *texHoldMarker;
    Texture2D *texCombo;
    Texture2D *texReady;
    Texture2D *texRating;
    Texture2D *texClear0;
    Texture2D *texClear1;
    Texture2D *texClear2;
    Texture2D *texDebugFont;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)drawDebugText:(const char *)arg1 pos:(struct CGPoint)arg2 alpha:(float)arg3;
- (void)draw;
- (void)renderResult;
- (struct CGPoint)storeMoveBtnPosition;
- (unsigned int)storeMoveButtonID;
- (struct CGPoint)twitterBtnPosition;
- (unsigned int)twitterSendButtonID;
- (struct CGPoint)goodJobPosition;
- (unsigned int)goodJobButtonID;
- (unsigned int)evaluateButtonID;
- (unsigned int)endButtonID;
- (double)gameAreaOffset;
- (double)buttonAreaOffset;
- (_Bool)renderFailed:(unsigned int)arg1 centerY:(double)arg2;
- (_Bool)renderCleared:(unsigned int)arg1 centerY:(double)arg2;
- (void)renderFinish;
- (void)renderStartMark;
- (void)renderReadyGo;
- (double)durationOfReadyGo;
- (void)renderCircle:(struct CGPoint)arg1 size:(double)arg2 alpha:(double)arg3;
- (void)renderPreStart;
- (void)renderButtons:(double)arg1;
- (void)renderUpper;
- (void)renderUpperBG:(double)arg1;
- (void)renderTuneInfo:(struct CGPoint)arg1 artworkSize:(double)arg2 alpha:(double)arg3;
- (void)renderMusicBar:(struct CGPoint)arg1 timeline:(_Bool)arg2 alpha:(double)arg3;
- (void)renderBonus:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 alpha:(double)arg3;
- (void)renderScore:(unsigned int)arg1 partnerScore:(unsigned int)arg2 atPoint:(struct CGPoint)arg3 scaleH:(double)arg4 alpha:(double)arg5;
- (void)renderUpdatedScore:(unsigned int)arg1 atPoint:(struct CGPoint)arg2 alpha:(double)arg3 scale:(double)arg4 boardY:(float)arg5;
- (void)renderCombo:(unsigned int)arg1;
- (void)renderBG;
- (void)renderMarker;
- (void)endResult;
- (void)startPlay;
- (void)setState:(unsigned int)arg1;
- (void)releaseTexture;
- (void)loadRatingTex:(short)arg1;
- (void)loadTexure:(id)arg1 artwork:(id)arg2 index:(id)arg3;
- (id)init;

@end

