//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class Downloader, MarkerDownloadManager, NSMutableArray, StoreDialogView;

@interface MarkerDownloadView : UIView
{
    StoreDialogView *dialogView;
    UIView *coverView;
    NSMutableArray *dlMarkerList;
    _Bool bEnableMarker;
    _Bool bListLegal;
    Downloader *listDownloader;
    MarkerDownloadManager *dlManager;
    int downloadListSize;
    int downloadedSize;
    _Bool isShowDialog;
    id _delegate;
    UIView *_parentView;
}

@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)downloadManagerFailed:(id)arg1;
- (void)downloadManagerCompleted:(id)arg1;
- (void)downloadManagerProceed:(id)arg1;
- (void)storeDialogCancel:(id)arg1;
- (void)hideModalDialog;
- (void)showModalDialog;
- (void)alertSelect:(id)arg1;
- (void)showListSkipAlert;
- (void)showDownloadRetryAlert;
- (void)listDownloadFailed;
- (void)downloaderFinished:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)createMarkerDownloadList;
- (void)markerDownload;
- (void)markerDownloadCancel;
- (void)markerDownloadEnd;
- (void)downloadMarkerList;
- (void)show;
- (id)init;

@end

