//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, SessionDownloader, StoreButton, UILabel, UITextView;

@interface MessageTextView : UIView
{
    SessionDownloader *messageDownloader;
    id delegate;
    StoreButton *btnClose;
    UITextView *licenseView;
    UILabel *labelMessage;
    NSString *titleString;
    float fScale;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (void)pushAgree:(id)arg1;
- (void)createMessageBoard:(id)arg1;
- (void)displayMessage:(id)arg1;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)sendErrorDelegate:(id)arg1;
- (id)init:(id)arg1 title:(id)arg2 message:(id)arg3;
- (id)init:(id)arg1 title:(id)arg2 url:(id)arg3 send:(id)arg4;

@end

