//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "EditFileListViewDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class EditFileListViewDeleteController, EditModalView, JcfDownloadPageNavController, JcfManageNavController, MusicSelectViewController, NSData, NSString, SearchPackIDView, TuneInfo, UIButton, UIImageView, UILabel, UIPopoverController, UIProgressView, UIScrollView;

@interface MusicDetailView : UIView <UIScrollViewDelegate, UITextFieldDelegate, UINavigationControllerDelegate, EditFileListViewDelegate, UIPopoverControllerDelegate>
{
    _Bool _isShared;
    _Bool _isFirstSelect;
    _Bool _isEditInfoOpen;
    BOOL _levelBas;
    BOOL _levelAdv;
    BOOL _levelExt;
    _Bool _fullComboBas;
    _Bool _fullComboAdv;
    _Bool _fullComboExt;
    _Bool _isPad;
    _Bool _isRetina;
    _Bool _isStarted;
    _Bool _isSharedStartable;
    BOOL _extendLevelBas;
    BOOL _extendLevelAdv;
    BOOL _extendLevelExt;
    _Bool _extendFullComboBas;
    _Bool _extendFullComboAdv;
    _Bool _extendFullComboExt;
    int _editPage;
    int _scoreBas;
    int _scoreAdv;
    int _scoreExt;
    int _extendScoreBas;
    int _extendScoreAdv;
    int _extendScoreExt;
    TuneInfo *_info;
    UIView *_coverView;
    UIImageView *_artworkView;
    UIImageView *_reflectionArtworkView;
    UIImageView *_tuneNameView;
    UIButton *_buttonStartPlay;
    UIButton *_buttonHostSharePlay;
    UILabel *_labelShareMessage;
    UIProgressView *_shareDataProgress;
    UIButton *_buttonLink;
    UIImageView *_randView;
    UIButton *_btnRecommendTwitter;
    UIButton *_btnRecommendFacebook;
    UIScrollView *_scrollView;
    EditFileListViewDeleteController *_pFileListView;
    UIPopoverController *_pLoadList;
    EditModalView *_pEditModalView;
    JcfDownloadPageNavController *_jcfDownloadPage;
    JcfManageNavController *_jcfMan;
    NSString *_customIndex;
    NSData *_mbarBas;
    NSData *_mbarAdv;
    NSData *_mbarExt;
    TuneInfo *_extendInfo;
    NSData *_extendMbarBas;
    NSData *_extendMbarAdv;
    NSData *_extendMbarExt;
    MusicSelectViewController *_controller;
    SearchPackIDView *_searchPackView;
    NSString *_socialType;
    UIView *_topcover;
}

@property(retain, nonatomic) UIView *topcover; // @synthesize topcover=_topcover;
@property(nonatomic) NSString *socialType; // @synthesize socialType=_socialType;
@property(retain, nonatomic) SearchPackIDView *searchPackView; // @synthesize searchPackView=_searchPackView;
@property(nonatomic) __weak MusicSelectViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSData *extendMbarExt; // @synthesize extendMbarExt=_extendMbarExt;
@property(retain, nonatomic) NSData *extendMbarAdv; // @synthesize extendMbarAdv=_extendMbarAdv;
@property(retain, nonatomic) NSData *extendMbarBas; // @synthesize extendMbarBas=_extendMbarBas;
@property(nonatomic) _Bool extendFullComboExt; // @synthesize extendFullComboExt=_extendFullComboExt;
@property(nonatomic) _Bool extendFullComboAdv; // @synthesize extendFullComboAdv=_extendFullComboAdv;
@property(nonatomic) _Bool extendFullComboBas; // @synthesize extendFullComboBas=_extendFullComboBas;
@property(nonatomic) int extendScoreExt; // @synthesize extendScoreExt=_extendScoreExt;
@property(nonatomic) int extendScoreAdv; // @synthesize extendScoreAdv=_extendScoreAdv;
@property(nonatomic) int extendScoreBas; // @synthesize extendScoreBas=_extendScoreBas;
@property(nonatomic) BOOL extendLevelExt; // @synthesize extendLevelExt=_extendLevelExt;
@property(nonatomic) BOOL extendLevelAdv; // @synthesize extendLevelAdv=_extendLevelAdv;
@property(nonatomic) BOOL extendLevelBas; // @synthesize extendLevelBas=_extendLevelBas;
@property(retain, nonatomic) TuneInfo *extendInfo; // @synthesize extendInfo=_extendInfo;
@property(nonatomic) _Bool isSharedStartable; // @synthesize isSharedStartable=_isSharedStartable;
@property(nonatomic) _Bool isStarted; // @synthesize isStarted=_isStarted;
@property(nonatomic) _Bool isRetina; // @synthesize isRetina=_isRetina;
@property(nonatomic) _Bool isPad; // @synthesize isPad=_isPad;
@property(retain, nonatomic) NSData *mbarExt; // @synthesize mbarExt=_mbarExt;
@property(retain, nonatomic) NSData *mbarAdv; // @synthesize mbarAdv=_mbarAdv;
@property(retain, nonatomic) NSData *mbarBas; // @synthesize mbarBas=_mbarBas;
@property(nonatomic) _Bool fullComboExt; // @synthesize fullComboExt=_fullComboExt;
@property(nonatomic) _Bool fullComboAdv; // @synthesize fullComboAdv=_fullComboAdv;
@property(nonatomic) _Bool fullComboBas; // @synthesize fullComboBas=_fullComboBas;
@property(nonatomic) int scoreExt; // @synthesize scoreExt=_scoreExt;
@property(nonatomic) int scoreAdv; // @synthesize scoreAdv=_scoreAdv;
@property(nonatomic) int scoreBas; // @synthesize scoreBas=_scoreBas;
@property(nonatomic) BOOL levelExt; // @synthesize levelExt=_levelExt;
@property(nonatomic) BOOL levelAdv; // @synthesize levelAdv=_levelAdv;
@property(nonatomic) BOOL levelBas; // @synthesize levelBas=_levelBas;
@property(nonatomic) _Bool isEditInfoOpen; // @synthesize isEditInfoOpen=_isEditInfoOpen;
@property(retain, nonatomic) NSString *customIndex; // @synthesize customIndex=_customIndex;
@property(retain, nonatomic) JcfManageNavController *jcfMan; // @synthesize jcfMan=_jcfMan;
@property(retain, nonatomic) JcfDownloadPageNavController *jcfDownloadPage; // @synthesize jcfDownloadPage=_jcfDownloadPage;
@property(nonatomic) int editPage; // @synthesize editPage=_editPage;
@property(retain, nonatomic) EditModalView *pEditModalView; // @synthesize pEditModalView=_pEditModalView;
@property(nonatomic) _Bool isFirstSelect; // @synthesize isFirstSelect=_isFirstSelect;
@property(retain, nonatomic) UIPopoverController *pLoadList; // @synthesize pLoadList=_pLoadList;
@property(retain, nonatomic) EditFileListViewDeleteController *pFileListView; // @synthesize pFileListView=_pFileListView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool isShared; // @synthesize isShared=_isShared;
@property(retain, nonatomic) UIButton *btnRecommendFacebook; // @synthesize btnRecommendFacebook=_btnRecommendFacebook;
@property(retain, nonatomic) UIButton *btnRecommendTwitter; // @synthesize btnRecommendTwitter=_btnRecommendTwitter;
@property(retain, nonatomic) UIImageView *randView; // @synthesize randView=_randView;
@property(retain, nonatomic) UIButton *buttonLink; // @synthesize buttonLink=_buttonLink;
@property(retain, nonatomic) UIProgressView *shareDataProgress; // @synthesize shareDataProgress=_shareDataProgress;
@property(retain, nonatomic) UILabel *labelShareMessage; // @synthesize labelShareMessage=_labelShareMessage;
@property(retain, nonatomic) UIButton *buttonHostSharePlay; // @synthesize buttonHostSharePlay=_buttonHostSharePlay;
@property(retain, nonatomic) UIButton *buttonStartPlay; // @synthesize buttonStartPlay=_buttonStartPlay;
@property(retain, nonatomic) UIImageView *tuneNameView; // @synthesize tuneNameView=_tuneNameView;
@property(retain, nonatomic) UIImageView *reflectionArtworkView; // @synthesize reflectionArtworkView=_reflectionArtworkView;
@property(retain, nonatomic) UIImageView *artworkView; // @synthesize artworkView=_artworkView;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) TuneInfo *info; // @synthesize info=_info;
- (void).cxx_destruct;
- (void)refreshInfo;
- (struct CGPoint)getDifficultyPos:(int)arg1;
- (void)changeExtendMode;
- (void)lpGesture:(id)arg1;
- (void)refreshStartButton;
- (void)dtpGesture:(id)arg1;
- (void)setStartButtonEnable;
- (void)moveStore:(id)arg1 packID:(id)arg2;
- (void)downloadEnd:(id)arg1;
- (_Bool)checkEnableEdit;
- (_Bool)checkEnableUpload;
- (_Bool)checkEnableInfoChange;
- (void)editModalViewDelegateSaveEditFile;
- (void)saveEditFile;
- (void)loadEditFile;
- (id)infoDictForShare;
- (void)close;
- (void)closePopWindow;
- (void)putExtendScore:(id)arg1;
- (void)putScore:(id)arg1;
- (void)resetScore;
- (void)sendTwitter:(id)arg1;
- (void)socialSend:(id)arg1 sendText:(id)arg2;
- (void)searchViewDealloc;
- (id)getRecommendString;
- (void)packIDSearchCancel:(id)arg1;
- (void)packIDSearchEnd:(id)arg1;
- (void)pushRecommend:(id)arg1;
- (void)pushLink:(id)arg1;
- (void)activateAnim:(_Bool)arg1;
- (void)showDataProgress:(_Bool)arg1 animated:(_Bool)arg2;
- (void)hostShareCancelled;
- (void)show:(_Bool)arg1;
- (void)loadContentFromPath:(id)arg1 orData:(id)arg2;
- (void)loadContentFromDictionary:(id)arg1;
- (void)clearInfo;
- (void)setExtendInfo:(id)arg1 score:(id)arg2;
- (void)setInfo:(id)arg1 score:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

