//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ArtworkLoaderDelegate-Protocol.h"
#import "NSCacheDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSCache, NSMutableArray, NSMutableDictionary, NSOperationQueue, NSString, UIButton, UICollectionView, UICollectionViewFlowLayout, UIGestureRecognizer, UILabel, UISlider;
@protocol MusicListViewDelegate;

@interface MusicListView : UIView <UIScrollViewDelegate, NSCacheDelegate, ArtworkLoaderDelegate, UICollectionViewDelegate, UICollectionViewDataSource>
{
    UICollectionViewFlowLayout *flowLayout;
    NSMutableArray *flowLayoutTable;
    UICollectionView *listView;
    id mvDelegate;
    UIButton *scaleUp;
    UIButton *scaleDown;
    int drawColumnType;
    int backColumnType;
    int musicNumInPage;
    _Bool bScaleAnimation;
    UILabel *labelPage;
    UIButton *btnPageRight;
    UIButton *btnPageLeft;
    UIGestureRecognizer *pageSliderCancel;
    UISlider *pageSlider;
    UIView *viewNoMusicMessage;
    UILabel *labelNoMusicMessage;
    int currentPage;
    _Bool pageChanging;
    struct CGPoint newPageOffset;
    NSCache *artworkCache;
    NSMutableDictionary *dictLoader;
    NSOperationQueue *operationQueue;
    _Bool isPad;
    _Bool is4Inch;
    int marginX;
    int marginY;
    id <MusicListViewDelegate> _delegate;
}

@property(nonatomic) __weak id <MusicListViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)refreshRatingChip;
- (void)refreshTextColor;
- (void)sliderEnd:(id)arg1;
- (void)sliderChange:(id)arg1;
- (void)sliderValueChange;
- (void)showPageSelector:(id)arg1;
- (void)pageSliderHidden:(id)arg1;
- (void)btnTouchesCancel:(id)arg1;
- (void)btnTouchesBegan:(id)arg1;
- (void)pushScaleUp:(id)arg1;
- (void)pushScaleDown:(id)arg1;
- (void)changeLayout:(int)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (void)dealloc;
- (id)getMusicView:(int)arg1;
- (void)addDownloadMark:(int)arg1;
- (void)pushPageArrow:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updatePageDisplay;
- (int)getCurrentPage;
- (int)numPage;
- (int)musicInPage:(int)arg1;
- (int)currentViewsPerPage;
- (void)releaseArtworks;
- (void)cache:(id)arg1 willEvictObject:(id)arg2;
- (void)imageDataLoaded:(id)arg1;
- (void)updateViews;
- (_Bool)layoutPage:(int)arg1 center:(int)arg2;
- (void)alignPage:(int)arg1;
- (void)setMusicViewDelegate:(id)arg1;
- (void)removeMusicView:(id)arg1;
- (void)reloadPageContainsMusicForIndex:(unsigned long long)arg1 playlistIndex:(long long)arg2;
- (void)loadInfoForView:(id)arg1 page:(unsigned long long)arg2 index:(unsigned long long)arg3;
- (void)loadArtworkForInfo:(id)arg1 forImageView:(id)arg2 concurrent:(_Bool)arg3;
- (void)loadArtworkForInfo:(id)arg1;
- (void)clearAllPage;
- (double)artworkSize;
- (void)hideAllPlaylistAction;
- (struct CGPoint)centerOfMusicViewInPage:(unsigned long long)arg1 forIndex:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

