//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MusicDetailView.h"

@class CABasicAnimation, JcfUpLoadView, UIButton, UIImage, UIImageView, UILabel, UIView;

@interface MusicDetailViewOrg : MusicDetailView
{
    UIButton *btnDiff[4];
    UIImageView *lightView[4][2];
    UIImageView *diffTextView[4];
    UIImageView *levelTextView[4];
    UIImageView *levelNumView[4];
    UIImage *levelNumImg[5][10];
    UIImage *levelTextImg[5];
    CABasicAnimation *lightBlinkAnim;
    UIImageView *highscoreBoardView;
    UIImageView *ratingView;
    UIImageView *comboView;
    UIImageView *highscoreNumView[7];
    UIImage *highscoreNumImg[10];
    UIImage *ratingImg[9];
    UIImage *fullcomboImg;
    UIImageView *mbarBarView;
    UIImageView *mbarDotView[120];
    UIImage *mbarBarImg[4];
    UIImage *mbarDotImg[4][8];
    char mbarDots[3][60];
    UILabel *editTxt[3];
    UIButton *infoBtn;
    UIButton *uploadBtn;
    UIButton *editBtn;
    UIButton *detailScrollButton[2];
    UIImageView *scrollLamp;
    UIImageView *diffBtnLamp;
    JcfUpLoadView *upLoadView;
    UIView *topcover;
    UIImageView *userTagIcon;
    char extendMbarDots[3][60];
    UIImageView *holdMark[3];
    UIImageView *extendMark[3];
    UIImageView *extendOnMark[3];
    _Bool bRandomBak;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (struct CGPoint)getDifficultyPos:(int)arg1;
- (void)changeExtendMode;
- (id)getSingleImage;
- (id)getStartImage;
- (void)uploadEnd:(id)arg1;
- (void)removeUploadView;
- (void)downloadEnd:(id)arg1;
- (void)customWebViewClose:(id)arg1 seqIndex:(id)arg2;
- (void)dealloc;
- (void)finishedSequenceOverCap:(id)arg1;
- (void)finishedSequenceDownload:(id)arg1;
- (void)errorSequenceDownload:(id)arg1;
- (void)editFileListViewCancel:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)selectEditFile:(id)arg1;
- (void)editFileListViewDeleteFile:(id)arg1;
- (void)editFileListViewSelectItem:(int)arg1;
- (void)editFileListViewSelectNewFile;
- (void)editPopoverOpen;
- (void)loadListRelease;
- (void)pushInfoEdit:(id)arg1;
- (_Bool)checkDownloadFile;
- (void)editModalViewClose:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)refreshStartButton;
- (void)pushButtonShare:(id)arg1;
- (void)editStart;
- (void)editFileListViewSelectEdit;
- (void)pushButtonEdit:(id)arg1;
- (void)pushButtonUpload:(id)arg1;
- (void)uploadStart;
- (void)editFileListViewSelectDownload;
- (void)pushButtonStartPlay:(id)arg1;
- (void)activateAnim:(_Bool)arg1;
- (void)showDataProgress:(_Bool)arg1 animated:(_Bool)arg2;
- (void)hostShareCancelled;
- (void)show:(_Bool)arg1;
- (void)setStartButtonEnable;
- (void)setEnableButton:(_Bool)arg1;
- (void)resetTextField:(int)arg1 isFirst:(_Bool)arg2;
- (void)editMusicBar;
- (void)setMusicBarDot:(char *)arg1 mbarRes:(char *)arg2;
- (void)scrollChange:(id)arg1;
- (void)changeDifficulty:(int)arg1;
- (void)setScoreBoard:(int)arg1 fullcombo:(_Bool)arg2;
- (void)selectDiff:(id)arg1;
- (void)clearInfo;
- (void)changeExtend:(int)arg1;
- (void)setExtendInfo:(id)arg1 score:(id)arg2;
- (void)infoChange:(int)arg1;
- (void)setInfo:(id)arg1 score:(id)arg2;
- (void)loadExtendMusicBar:(id)arg1;
- (void)loadContentFromPath:(id)arg1 orData:(id)arg2;
- (void)loadContentFromDictionary:(id)arg1;
- (void)loadImages;
- (id)diffButton:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

