//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, TuneInfo, UIButton, UIImageView, UILabel;
@protocol MusicViewDelegate;

@interface MusicView : UIView
{
    _Bool isPad;
    _Bool isPhoneRetina;
    _Bool is4Inch;
    double artwork_size;
    double imageSize;
    double currentScale;
    int defaultWidth;
    NSMutableArray *rankBgArray;
    NSMutableArray *rankImgArray;
    NSMutableArray *rankFcArray;
    NSMutableArray *adRankBgArray;
    NSMutableArray *adRankImgArray;
    NSMutableArray *adRankFcArray;
    NSMutableArray *adRankBgChipArray;
    UIImageView *_imgView;
    UIButton *_btnPlaylistAction;
    TuneInfo *_tuneInfo;
    UIImageView *_rankBgBas;
    UIImageView *_rankBgAdv;
    UIImageView *_rankBgExt;
    id <MusicViewDelegate> _delegate;
    NSMutableArray *_rankBgChipArray;
    UIImageView *_adRankBgBas;
    UIImageView *_adRankBgAdv;
    UIImageView *_adRankBgExt;
    UILabel *_nameLabel;
    UILabel *_artistNameLabel;
    UIImageView *_rankImgBas;
    UIImageView *_rankImgAdv;
    UIImageView *_rankImgExt;
    UIImageView *_rankFcBas;
    UIImageView *_rankFcAdv;
    UIImageView *_rankFcExt;
    UIImageView *_jcfIcon;
    TuneInfo *_extendTuneInfo;
    UIImageView *_rankBgOrgBas;
    UIImageView *_rankBgOrgAdv;
    UIImageView *_rankBgOrgExt;
    UIImageView *_rankBgHldBas;
    UIImageView *_rankBgHldAdv;
    UIImageView *_rankBgHldExt;
    UIImageView *_adRankImgBas;
    UIImageView *_adRankImgAdv;
    UIImageView *_adRankImgExt;
    UIImageView *_adRankFcBas;
    UIImageView *_adRankFcAdv;
    UIImageView *_adRankFcExt;
    UIButton *_btnBgmSelect;
}

@property(retain, nonatomic) UIButton *btnBgmSelect; // @synthesize btnBgmSelect=_btnBgmSelect;
@property(retain, nonatomic) UIImageView *adRankFcExt; // @synthesize adRankFcExt=_adRankFcExt;
@property(retain, nonatomic) UIImageView *adRankFcAdv; // @synthesize adRankFcAdv=_adRankFcAdv;
@property(retain, nonatomic) UIImageView *adRankFcBas; // @synthesize adRankFcBas=_adRankFcBas;
@property(retain, nonatomic) UIImageView *adRankImgExt; // @synthesize adRankImgExt=_adRankImgExt;
@property(retain, nonatomic) UIImageView *adRankImgAdv; // @synthesize adRankImgAdv=_adRankImgAdv;
@property(retain, nonatomic) UIImageView *adRankImgBas; // @synthesize adRankImgBas=_adRankImgBas;
@property(retain, nonatomic) UIImageView *rankBgHldExt; // @synthesize rankBgHldExt=_rankBgHldExt;
@property(retain, nonatomic) UIImageView *rankBgHldAdv; // @synthesize rankBgHldAdv=_rankBgHldAdv;
@property(retain, nonatomic) UIImageView *rankBgHldBas; // @synthesize rankBgHldBas=_rankBgHldBas;
@property(retain, nonatomic) UIImageView *rankBgOrgExt; // @synthesize rankBgOrgExt=_rankBgOrgExt;
@property(retain, nonatomic) UIImageView *rankBgOrgAdv; // @synthesize rankBgOrgAdv=_rankBgOrgAdv;
@property(retain, nonatomic) UIImageView *rankBgOrgBas; // @synthesize rankBgOrgBas=_rankBgOrgBas;
@property(retain, nonatomic) TuneInfo *extendTuneInfo; // @synthesize extendTuneInfo=_extendTuneInfo;
@property(retain, nonatomic) UIImageView *jcfIcon; // @synthesize jcfIcon=_jcfIcon;
@property(retain, nonatomic) UIImageView *rankFcExt; // @synthesize rankFcExt=_rankFcExt;
@property(retain, nonatomic) UIImageView *rankFcAdv; // @synthesize rankFcAdv=_rankFcAdv;
@property(retain, nonatomic) UIImageView *rankFcBas; // @synthesize rankFcBas=_rankFcBas;
@property(retain, nonatomic) UIImageView *rankImgExt; // @synthesize rankImgExt=_rankImgExt;
@property(retain, nonatomic) UIImageView *rankImgAdv; // @synthesize rankImgAdv=_rankImgAdv;
@property(retain, nonatomic) UIImageView *rankImgBas; // @synthesize rankImgBas=_rankImgBas;
@property(retain, nonatomic) UILabel *artistNameLabel; // @synthesize artistNameLabel=_artistNameLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *adRankBgExt; // @synthesize adRankBgExt=_adRankBgExt;
@property(retain, nonatomic) UIImageView *adRankBgAdv; // @synthesize adRankBgAdv=_adRankBgAdv;
@property(retain, nonatomic) UIImageView *adRankBgBas; // @synthesize adRankBgBas=_adRankBgBas;
@property(retain, nonatomic) NSMutableArray *rankBgChipArray; // @synthesize rankBgChipArray=_rankBgChipArray;
@property(nonatomic) __weak id <MusicViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *rankBgExt; // @synthesize rankBgExt=_rankBgExt;
@property(retain, nonatomic) UIImageView *rankBgAdv; // @synthesize rankBgAdv=_rankBgAdv;
@property(retain, nonatomic) UIImageView *rankBgBas; // @synthesize rankBgBas=_rankBgBas;
@property(retain, nonatomic) TuneInfo *tuneInfo; // @synthesize tuneInfo=_tuneInfo;
@property(retain, nonatomic) UIButton *btnPlaylistAction; // @synthesize btnPlaylistAction=_btnPlaylistAction;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
- (void).cxx_destruct;
- (void)removeDownloadNotice;
- (void)addDownloadNotice;
- (void)tapBgmSelect:(id)arg1;
- (void)tapPlaylistAction:(id)arg1;
- (void)handlePress:(id)arg1;
- (id)bgmImagePrefix;
- (void)handleTap:(id)arg1;
- (void)hidePlaylistActionButton;
- (void)setScore:(id)arg1;
- (void)showNameAndArtist:(_Bool)arg1;
- (void)clearInfo;
- (void)setInfo:(id)arg1;
- (void)switchLabel:(int)arg1;
- (void)fadeoutLabel;
- (void)scaleChange:(int)arg1;
- (void)setRatingChipHidden:(int)arg1;
- (void)setExtendScore:(id)arg1;
- (void)setExtendInfo:(id)arg1;
- (void)refreshTextColor;
- (void)setInfo:(id)arg1 bArtistNameDisp:(_Bool)arg2;
- (struct CGPoint)centerArtworkImg;
- (id)initWithFrame:(struct CGRect)arg1 artworkSize:(double)arg2 colType:(int)arg3 labelDisp:(_Bool)arg4;
- (id)getTextColor;

@end

