//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString;

@protocol PurchaseManagerDelegate <NSObject>

@optional
- (void)restoreNothing;
- (void)restoreFailed:(NSError *)arg1;
- (void)restoreSucceeded;
- (void)purchaseFailed:(NSString *)arg1 error:(NSError *)arg2;
- (void)purchaseSucceeded:(NSString *)arg1;
@end

