//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class BalloonView, NSDictionary, NSTimer, UIButton, UILabel;

@interface PushNotificationView : UIView
{
    BalloonView *bgView;
    NSDictionary *currentNotice;
    NSTimer *dispTimer;
    _Bool bActive;
    UILabel *notiLabel;
    UIButton *linkBtn;
    id aDelegate;
}

- (void).cxx_destruct;
- (_Bool)isActive;
- (void)tapNotification:(id)arg1;
- (void)stopNotification;
- (void)startNotification;
- (void)onDrawTimer:(id)arg1;
- (void)popNotification;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

@end

