//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RotatableNavigationController.h"

@class RankingViewController;

@interface RankingNavController : RotatableNavigationController
{
    RankingViewController *rankingViewCtrl;
    id _rankingDelegate;
}

@property(nonatomic) __weak id rankingDelegate; // @synthesize rankingDelegate=_rankingDelegate;
- (void).cxx_destruct;
- (void)viewDidUnload;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)pushClose:(id)arg1;
- (void)loadView;
- (id)init;

@end

