//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ApplilinkViewDelegate-Protocol.h"
#import "ShadeViewDelegate-Protocol.h"

@class ApplilinkParameters, ShadeView, UIActivityIndicatorView, UIView;

@interface RecommendFullScreenController : UIViewController <ShadeViewDelegate, ApplilinkViewDelegate>
{
    _Bool _isVisible;
    UIView *_baseView;
    ShadeView *_shadeView;
    UIActivityIndicatorView *_indicator;
    ApplilinkParameters *_applilinkParams;
    id _applilinkDelegate;
    id _applilinkFullViewDelegate;
}

@property(nonatomic) __weak id applilinkFullViewDelegate; // @synthesize applilinkFullViewDelegate=_applilinkFullViewDelegate;
@property(nonatomic) __weak id applilinkDelegate; // @synthesize applilinkDelegate=_applilinkDelegate;
@property(copy, nonatomic) ApplilinkParameters *applilinkParams; // @synthesize applilinkParams=_applilinkParams;
@property(retain, nonatomic) UIActivityIndicatorView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) ShadeView *shadeView; // @synthesize shadeView=_shadeView;
@property(retain, nonatomic) UIView *baseView; // @synthesize baseView=_baseView;
@property(nonatomic) _Bool isVisible; // @synthesize isVisible=_isVisible;
- (void).cxx_destruct;
- (void)dealloc;
- (void)releaseInterstitialView;
- (void)closeShadeView;
- (void)failLinkNoticeWithError:(id)arg1;
- (void)failOpenNoticeWithError:(id)arg1;
- (void)closeNotice;
- (void)openedNotice;
- (void)appListFailLinkWithError:(id)arg1;
- (void)appListFailLoadWithError:(id)arg1;
- (void)appListDidDisappear;
- (void)appListDidAppear;
- (void)webViewDidStartLoad;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)rotateWebViewWithDuration:(double)arg1;
- (void)setViewSize;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)openAdViewWithAdModel:(int)arg1 adLocation:(id)arg2 verticalAlign:(int)arg3 applilinkParams:(id)arg4 delegate:(id)arg5 closeDelegate:(id)arg6;
- (void)didReceiveMemoryWarning;
- (void)loadView;
- (id)init;

@end

