//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RecommendAdCache : NSObject
{
}

+ (id)getHtmlAdDataWithAdModel:(int)arg1 adLocation:(id)arg2;
+ (void)setHtmlAdDataWithAdModel:(int)arg1 adLocation:(id)arg2 bannerList:(id)arg3;
+ (void)clearAdDisplayCount;
+ (void)setAdDisplayCountTotalWithAdId:(id)arg1;
+ (void)setAdDisplayCountDailyWithAdId:(id)arg1;
+ (void)setAdDisplayCountWithAdId:(id)arg1;
+ (void)setTargetUrl:(id)arg1 adType:(int)arg2 adModel:(int)arg3 adLocation:(id)arg4;
+ (id)convertHtmlWithAdType:(int)arg1 verticalAlign:(int)arg2 bannerList:(id)arg3;
+ (id)createHtmlWithAdModel:(int)arg1 adLocation:(id)arg2 verticalAlign:(int)arg3;
+ (void)saveTemplateData:(id)arg1 path:(id)arg2 file:(id)arg3;
+ (id)getTemplateFile:(id)arg1;
+ (void)getTemplateFiles;
+ (id)getBannerCachePath;
+ (id)getContentsPath;
+ (_Bool)existFile:(id)arg1;
+ (void)saveData:(id)arg1 file:(id)arg2;
+ (id)getDataWithUrl:(id)arg1;
+ (int)getBannerWithUrl:(id)arg1;
+ (void)getBannerDataWithList:(id)arg1 max:(int)arg2;
+ (void)allClearCacheBannerImage;
+ (void)clearCacheBannerImage;
+ (void)delateFolder;
+ (void)createFolder;
+ (void)clearAllAdDataInfoExpire;
+ (id)getAllAdDataInfoExpire;
+ (void)clearAllAdData;
+ (void)getAllAdDataWithCallBack:(CDUnknownBlockType)arg1;
+ (void)getAllAdStatus;

@end

