//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RewardWebViewController.h"

#import "UIWebViewDelegate-Protocol.h"

@interface RecommendWebViewController : RewardWebViewController <UIWebViewDelegate>
{
}

- (void)dealloc;
- (void)removeFromSuperview;
- (int)redirectWithRequest:(id)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

