//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class EAGLView, Texture2D;

@interface ResultItemChance : NSObject
{
    _Bool bPlaySe;
    Texture2D *texEffect;
    int animationFrame;
    struct CGSize screenSize;
    struct CGPoint screenCenter;
    int effectSize;
    float displayScale;
    _Bool effectVisible[32];
    int effectType[32];
    int effectPos[32][2];
    int effectTime[32];
    int effectEndTime[32];
    float effectColor[32][3];
    id _aDelegate;
    EAGLView *_eaglView;
}

@property(retain, nonatomic) EAGLView *eaglView; // @synthesize eaglView=_eaglView;
@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)restartAnimation;
- (void)renderEffect;
- (void)renderEffectParts:(int)arg1 posX:(int)arg2 posY:(int)arg3 color:(id)arg4;
- (void)renderEffectParts:(int)arg1 posX:(int)arg2 posY:(int)arg3 alpha:(float)arg4;
- (_Bool)enableSkip;
- (_Bool)draw;
- (void)setInfo:(int)arg1 itemNum:(int)arg2 size:(struct CGSize)arg3 center:(struct CGPoint)arg4 scale:(float)arg5;
- (void)releaseTexture;
- (void)loadTexure;

@end

