//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RewardWebAPI : NSObject
{
}

+ (void)setTemporaryCacheWithKey:(id)arg1 value:(id)arg2 expiration:(long long)arg3;
+ (void)setSignatureWithParameters:(id)arg1;
+ (void)bannerInfoWithBlock:(CDUnknownBlockType)arg1;
+ (void)postAppliInstallReportWithAppliList:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (void)getPreInfoWithCallback:(CDUnknownBlockType)arg1;
+ (void)allInstallFlgWithCallback:(CDUnknownBlockType)arg1;
+ (void)appliIdListWithType:(int)arg1 callback:(CDUnknownBlockType)arg2;
+ (void)appListWithCampaignId:(id)arg1 inCompany:(id)arg2 offset:(id)arg3 limit:(id)arg4 callback:(CDUnknownBlockType)arg5;
+ (void)startLoginWithUserId:(id)arg1 withPriority:(int)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)checkLoginWithBlock:(CDUnknownBlockType)arg1;
+ (void)postApplicationInstallWithPriority:(int)arg1 callback:(CDUnknownBlockType)arg2;

@end

