//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SdkViewDelegate-Protocol.h"

@class ApplilinkParameters, RewardWebViewController;
@protocol ApplilinkViewDelegate;

@interface RewardCore : NSObject <SdkViewDelegate>
{
    _Bool _isNavigationBarHidden;
    int _initializeFlg;
    RewardWebViewController *_rewardViewController;
    id <ApplilinkViewDelegate> _applilinkDelegate;
    ApplilinkParameters *_applilinkParams;
}

+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) ApplilinkParameters *applilinkParams; // @synthesize applilinkParams=_applilinkParams;
@property(nonatomic) __weak id <ApplilinkViewDelegate> applilinkDelegate; // @synthesize applilinkDelegate=_applilinkDelegate;
@property(retain, nonatomic) RewardWebViewController *rewardViewController; // @synthesize rewardViewController=_rewardViewController;
@property(nonatomic) _Bool isNavigationBarHidden; // @synthesize isNavigationBarHidden=_isNavigationBarHidden;
@property(nonatomic) int initializeFlg; // @synthesize initializeFlg=_initializeFlg;
- (void).cxx_destruct;
- (void)dealloc;
- (void)clearSession;
- (void)clearAdStatus;
- (_Bool)canUseBannerCache;
- (void)openCancelWithError:(id)arg1;
- (void)failLinkNoticeWithError:(id)arg1;
- (void)failOpenNoticeWithError:(id)arg1;
- (void)closeNotice;
- (void)openedNotice;
- (void)startedNotice;
- (void)appListFailLinkWithError:(id)arg1 delegate:(id)arg2;
- (void)appListFailLoadWithError:(id)arg1 delegate:(id)arg2;
- (void)appListDidDisappear:(id)arg1;
- (void)appListDidAppear:(id)arg1;
- (void)appListDidStart:(id)arg1;
- (id)getTemporaryCacheWithKey:(id)arg1;
- (void)setTemporaryCacheWithKey:(id)arg1 value:(id)arg2 expiration:(long long)arg3;
- (void)setNavigationBarHidden:(_Bool)arg1;
- (int)redirectWithRequest:(id)arg1;
- (void)rotateAdScreenWithInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)closeAdScreen;
- (void)openAdScreenWithParentView:(id)arg1 adLocation:(id)arg2 requestCode:(id)arg3 delegate:(id)arg4;
- (void)getAppListStatusWithBlock:(CDUnknownBlockType)arg1;
- (void)getInstalledAppWithCallback:(CDUnknownBlockType)arg1;
- (void)postInstalledAppWithCallback:(CDUnknownBlockType)arg1;
- (void)getAdDisplayStatusWithCallback:(CDUnknownBlockType)arg1;
- (void)allInstallFlgWithCallback:(CDUnknownBlockType)arg1;
- (_Bool)createCFUdidWithError:(id *)arg1;
- (_Bool)createUdidWithBlock:(CDUnknownBlockType)arg1;
- (void)startWithBlock:(CDUnknownBlockType)arg1;
- (void)startSessionWithBlock:(CDUnknownBlockType)arg1;
- (void)startWithCallback:(CDUnknownBlockType)arg1;
- (int)campaignFlg;
- (void)clearInitialize;
- (id)init;

@end

