//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class EditViewController, GameViewController, LogoViewController, MusicSelectViewController, NSString, StoreViewController, TitleViewController, UIView;

@interface RootViewController : UIViewController
{
    double durationIn;
    double durationOut;
    UIView *fadeView;
    LogoViewController *logoViewCtrl;
    TitleViewController *titleViewCtrl;
    GameViewController *gameViewCtrl;
    MusicSelectViewController *musicSelectViewCtrl;
    StoreViewController *storeViewCtrl;
    NSString *currentSceneID;
    NSString *suspendedAnimID;
    EditViewController *editViewCtrl;
    _Bool _isActive;
}

@property(readonly, nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)appWillTerminate:(id)arg1;
- (void)appDidBecomeActive:(id)arg1;
- (void)appWillResignActive:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)pushNotificate;
- (_Bool)autoMovePackDownload;
- (_Bool)autoMoveChallenge;
- (_Bool)downloadCustomSequence;
- (void)fadeinAnimStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)fadeoutAnimStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)returnFromEdit;
- (void)startEditNote:(id)arg1 musicData:(id)arg2 jcfName:(id)arg3;
- (void)returnToMusicSelect;
- (void)musicRestart;
- (void)startMainGame:(id)arg1 shareManager:(id)arg2 musicData:(id)arg3;
- (void)endStoreAnimStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)reloadMarkers;
- (void)changeThemeAndGoTitle;
- (void)endStore;
- (void)openStoreAnimStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)openStore:(id)arg1;
- (void)endTitle;
- (void)endLogo;
- (void)startLogo;
- (void)fade:(id)arg1 durationIn:(double)arg2 durationOut:(double)arg3;
- (void)loadView;
- (id)init;

@end

