//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator;

@interface ScoreRecordManager : NSObject
{
    NSManagedObjectContext *_managedObjectContext;
    NSManagedObjectModel *_managedObjectModel;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator;
@property(readonly, nonatomic) NSManagedObjectModel *managedObjectModel;
@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext;
- (void)saveRecords;

@end

