//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSDate, NSNumber;

@interface ScoreRecord : NSManagedObject
{
}

+ (long long)totalScore;
+ (_Bool)checkScore:(id)arg1;
+ (id)hashScore:(id)arg1;
+ (void)hashScoreforTune:(int)arg1 bas:(int)arg2 adv:(int)arg3 ext:(int)arg4 hash:(char *)arg5;
+ (void)reset:(id)arg1;
+ (id)createRecordWithTuneID:(unsigned int)arg1;
+ (id)recordsForTuneIDs:(id)arg1;
+ (id)recordForTuneID:(unsigned int)arg1;

// Remaining properties
@property(retain, nonatomic) NSData *chksco; // @dynamic chksco;
@property(retain, nonatomic) NSNumber *fcAdv; // @dynamic fcAdv;
@property(retain, nonatomic) NSNumber *fcBas; // @dynamic fcBas;
@property(retain, nonatomic) NSNumber *fcExt; // @dynamic fcExt;
@property(retain, nonatomic) NSDate *lastPlayDate; // @dynamic lastPlayDate;
@property(retain, nonatomic) NSData *mbAdv; // @dynamic mbAdv;
@property(retain, nonatomic) NSData *mbBas; // @dynamic mbBas;
@property(retain, nonatomic) NSData *mbExt; // @dynamic mbExt;
@property(retain, nonatomic) NSNumber *playCount; // @dynamic playCount;
@property(retain, nonatomic) NSNumber *scoAdv; // @dynamic scoAdv;
@property(retain, nonatomic) NSNumber *scoBas; // @dynamic scoBas;
@property(retain, nonatomic) NSNumber *scoExt; // @dynamic scoExt;
@property(retain, nonatomic) NSNumber *tuneID; // @dynamic tuneID;

@end

