//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface ScratchCompleteView : UIView
{
    UIView *bgView;
    UIImageView *artworkView;
    UIImageView *artworkBg;
    UIImageView *completeView;
    UILabel *musicName;
    UILabel *artistName;
    UIView *touchView;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)closeView;
- (void)animationStart;
- (id)initWithFrame:(struct CGRect)arg1 musicInfo:(id)arg2;

@end

