//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ScratchMessageView, ScratchView, UIImageView;

@interface ScratchBoardView : UIView
{
    UIImageView *bgImageView;
    UIImageView *svbg[16];
    ScratchView *sv[16];
    ScratchMessageView *smv;
    id _aDelegate;
}

@property(nonatomic) __weak id aDelegate; // @synthesize aDelegate=_aDelegate;
- (void).cxx_destruct;
- (void)timerUpdate;
- (void)refreshScratchTable;
- (void)refreshScratchCount;
- (void)setDelegate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

