//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SePlayer : NSObject
{
    unsigned int soundBuffer;
    unsigned int soundSource;
    struct ALCdevice_struct *soundDevice;
    void *soundData;
    struct ALCcontext_struct *soundContext;
}

- (void)terminate;
- (void)sePlay;
- (id)initWithPath:(id)arg1;

@end

