//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MCPeerID, NSDate;

@interface SessionClass : NSObject
{
    float _delayTime;
    float _pingTryCnt;
    float _receiveTime;
    int _score;
    int _finalBonus;
    _Bool _fullcombo;
    _Bool _finished;
    _Bool _settledSync;
    _Bool _dataReceived;
    _Bool _readyToLoad;
    _Bool _dataLoaded;
    MCPeerID *_peerID;
    NSDate *_receiveStartTime;
}

@property(nonatomic) _Bool dataLoaded; // @synthesize dataLoaded=_dataLoaded;
@property(nonatomic) _Bool readyToLoad; // @synthesize readyToLoad=_readyToLoad;
@property(nonatomic) _Bool dataReceived; // @synthesize dataReceived=_dataReceived;
@property(nonatomic) _Bool settledSync; // @synthesize settledSync=_settledSync;
@property(nonatomic) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic) _Bool fullcombo; // @synthesize fullcombo=_fullcombo;
@property(nonatomic) int finalBonus; // @synthesize finalBonus=_finalBonus;
@property(nonatomic) int score; // @synthesize score=_score;
@property(nonatomic) float receiveTime; // @synthesize receiveTime=_receiveTime;
@property(nonatomic) float pingTryCnt; // @synthesize pingTryCnt=_pingTryCnt;
@property(nonatomic) float delayTime; // @synthesize delayTime=_delayTime;
@property(retain, nonatomic) NSDate *receiveStartTime; // @synthesize receiveStartTime=_receiveStartTime;
@property(retain, nonatomic) MCPeerID *peerID; // @synthesize peerID=_peerID;
- (void).cxx_destruct;
- (id)init;

@end

