//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Downloader.h"

@class NSData, NSString, NSURL, NSURLRequest;

@interface SessionDownloader : Downloader
{
    NSURLRequest *tmpRequest;
    NSURL *requestURL;
    NSData *requestData;
    NSString *sendCnonce;
    NSString *receiveHash;
    int retryCnt;
    int _apiTag;
}

@property(nonatomic) int apiTag; // @synthesize apiTag=_apiTag;
- (void).cxx_destruct;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)getSessionRequest;
- (id)initWithURL:(id)arg1 postData:(id)arg2 delegate:(id)arg3;
- (id)initWithURL:(id)arg1 delegate:(id)arg2;
- (id)createPostRequest:(id)arg1 postData:(id)arg2;
- (id)dataHash:(id)arg1;
- (id)initWithURL:(id)arg1 postDictionary:(id)arg2 delegate:(id)arg3;

@end

