//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSArray, NSData, NSMutableData, NSString, NSURLConnection, UIActivityIndicatorView, UIBarButtonItem, UIButton, UILabel, UITextField;

@interface SettingsEAViewController : UIViewController <UITextFieldDelegate>
{
    UILabel *_messageLabel;
    UIBarButtonItem *_barBtnCancel;
    UILabel *_kidLabel;
    UILabel *_passLabel;
    UILabel *_otpLabel;
    UILabel *_otpMessage;
    UITextField *_kidField;
    UITextField *_passField;
    UITextField *_otpField;
    UIButton *_btnLogin;
    UIActivityIndicatorView *_indicatorLogin;
    UILabel *_labelInstruction;
    UIButton *_btnInstLink;
    NSArray *_arrayNewMarker;
    NSURLConnection *_conn;
    NSData *_requestData;
    NSArray *_eaCookies;
    NSMutableData *_responseData;
}

@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(retain, nonatomic) NSArray *eaCookies; // @synthesize eaCookies=_eaCookies;
@property(retain, nonatomic) NSData *requestData; // @synthesize requestData=_requestData;
@property(retain, nonatomic) NSURLConnection *conn; // @synthesize conn=_conn;
@property(retain, nonatomic) NSArray *arrayNewMarker; // @synthesize arrayNewMarker=_arrayNewMarker;
@property(retain, nonatomic) UIButton *btnInstLink; // @synthesize btnInstLink=_btnInstLink;
@property(retain, nonatomic) UILabel *labelInstruction; // @synthesize labelInstruction=_labelInstruction;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorLogin; // @synthesize indicatorLogin=_indicatorLogin;
@property(retain, nonatomic) UIButton *btnLogin; // @synthesize btnLogin=_btnLogin;
@property(retain, nonatomic) UITextField *otpField; // @synthesize otpField=_otpField;
@property(retain, nonatomic) UITextField *passField; // @synthesize passField=_passField;
@property(retain, nonatomic) UITextField *kidField; // @synthesize kidField=_kidField;
@property(retain, nonatomic) UILabel *otpMessage; // @synthesize otpMessage=_otpMessage;
@property(retain, nonatomic) UILabel *otpLabel; // @synthesize otpLabel=_otpLabel;
@property(retain, nonatomic) UILabel *passLabel; // @synthesize passLabel=_passLabel;
@property(retain, nonatomic) UILabel *kidLabel; // @synthesize kidLabel=_kidLabel;
@property(retain, nonatomic) UIBarButtonItem *barBtnCancel; // @synthesize barBtnCancel=_barBtnCancel;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)alertSelect:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)pushLogin:(id)arg1;
- (void)fieldChanged:(id)arg1;
- (void)tapLink:(id)arg1;
- (void)cancelInput:(id)arg1;
- (void)loadView;
- (void)showUnlockedMessage;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

