//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CLLocationManagerDelegate-Protocol.h"
#import "MKMapViewDelegate-Protocol.h"

@class CLLocationManager, Downloader, MKMapView, NSMutableDictionary, NSString, UIActivityIndicatorView, UIAlertView, UILabel;

@interface SettingsMapViewController : UIViewController <MKMapViewDelegate, CLLocationManagerDelegate>
{
    CDStruct_feeb6407 lastRegion;
    _Bool isObservingLocation;
    _Bool firstLocationObserved;
    UIAlertView *checkAlert;
    MKMapView *_mapView;
    UIActivityIndicatorView *_indicator;
    UILabel *_messageLabel;
    CLLocationManager *_locationManager;
    Downloader *_listDownloader;
    NSMutableDictionary *_dictSpot;
    NSString *_mapURL;
}

@property(retain, nonatomic) NSString *mapURL; // @synthesize mapURL=_mapURL;
@property(retain, nonatomic) NSMutableDictionary *dictSpot; // @synthesize dictSpot=_dictSpot;
@property(retain, nonatomic) Downloader *listDownloader; // @synthesize listDownloader=_listDownloader;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIActivityIndicatorView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (void).cxx_destruct;
- (void)mapClose;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)alertSelect:(id)arg1;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)pushCurrent:(id)arg1;
- (void)requestList:(CDStruct_feeb6407)arg1;
- (_Bool)currentLocationEnabled;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

