//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ApplilinkViewDelegate-Protocol.h"

@class EditorIDManager, NSString, UIActivityIndicatorView, UIView, UIWebView;

@interface SettingsRewardViewController : UIViewController <ApplilinkViewDelegate>
{
    UIView *bgView;
    UIWebView *rewardView;
    EditorIDManager *idManager;
    _Bool bRewardOpen;
    UIActivityIndicatorView *_indicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)successIDDownload:(id)arg1;
- (void)errorIDDownload:(id)arg1 msgStr:(id)arg2;
- (void)appListFailLoadWithError:(id)arg1;
- (void)appListDidDisappear;
- (void)appListDidAppear;
- (void)openRewardView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

