//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"

@class EditorIDManager, NSMutableArray, NSString, RewardCheck, SePlayer, UIActivityIndicatorView, UIButton, UIImageView, UIPageControl, UIScrollView;

@interface SettingsTwSelectViewController : UIViewController <UIScrollViewDelegate>
{
    UIImageView *frameImage;
    UIImageView *accImage;
    UIImageView *selFrameImgTable[4];
    UIImageView *selFrameLockImgTable[4];
    NSMutableArray *frameTable;
    UIScrollView *scrollView;
    UIPageControl *pageCtrl;
    NSMutableArray *frameImgTable;
    NSMutableArray *accImgTable;
    NSMutableArray *lockViewTable;
    UIButton *rewardBtn;
    NSMutableArray *scrlBtn;
    UIButton *scrlArrow[2];
    int windowWidth;
    float fScale;
    int itemPage;
    UIActivityIndicatorView *indicatorView;
    RewardCheck *rewardCheck;
    int rewardNum;
    SePlayer *bellSe;
    EditorIDManager *idManager;
}

- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)itemDispStart:(_Bool)arg1;
- (void)itemDisp:(_Bool)arg1;
- (void)errorIDDownload:(id)arg1 msgStr:(id)arg2;
- (void)successIDDownload:(id)arg1;
- (void)rewardCheckEnd:(id)arg1;
- (_Bool)isUnlockFrameWithSlot:(int)arg1;
- (_Bool)isUnlockFrame:(id)arg1;
- (void)scrollChange:(id)arg1;
- (void)pushBtnRewardCheck:(id)arg1;
- (void)pushBtnReward:(id)arg1;
- (void)refreshLockImage;
- (id)getSelectedFrame;
- (void)scrollCursorControll;
- (void)scrollBtnAlphaControll;
- (void)loadView;
- (id)init;
- (struct CGRect)makeRect:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

