//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MKAnnotation-Protocol.h"

@class NSString;

@interface SettingsMapItem : NSObject <MKAnnotation>
{
    CDStruct_2c43369c _coordinate;
    NSString *_title;
    NSString *_subtitle;
    unsigned long long _model;
}

@property(nonatomic) unsigned long long model; // @synthesize model=_model;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)setCoordinate:(CDStruct_c3b9c2ee)arg1;
@property(readonly, nonatomic) CDStruct_c3b9c2ee coordinate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

