//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RotatableNavigationController.h"

@class SettingsViewController;

@interface SettingsNavController : RotatableNavigationController
{
    id _settingsDelegate;
    SettingsViewController *_settingsViewCtrl;
}

@property(retain, nonatomic) SettingsViewController *settingsViewCtrl; // @synthesize settingsViewCtrl=_settingsViewCtrl;
@property(nonatomic) __weak id settingsDelegate; // @synthesize settingsDelegate=_settingsDelegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)disablesAutomaticKeyboardDismissal;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)settingClose;
- (void)pushClose:(id)arg1;
- (void)loadView;
- (id)init;

@end

