//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class AdjustTestView, CADisplayLink, UIButton, UIImageView, UILabel, UISlider;

@interface SettingsTimingAdjustViewController : UIViewController
{
    UISlider *adjustSlider;
    UILabel *adjustTxt;
    UILabel *valueTxt;
    UILabel *maxTxt;
    UILabel *minTxt;
    UIImageView *bgImg;
    AdjustTestView *testView;
    UIButton *prevBtn;
    _Bool prevPause;
    int delaySector;
    CADisplayLink *_displayLink;
}

@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
- (void).cxx_destruct;
- (id)soundName:(id)arg1;
- (void)loop:(id)arg1;
- (void)stopAnimation;
- (void)resumeAnimation;
- (void)pauseAnimation;
- (void)startAnimation;
- (void)finishMusic:(id)arg1;
- (void)appResume:(id)arg1;
- (void)appSuspended:(id)arg1;
- (void)switchPrev:(id)arg1;
- (void)refreshValue;
- (void)changeTiming:(id)arg1;
- (void)dealloc;
- (void)alertSelect:(id)arg1;
- (void)tapAutoSetting:(id)arg1;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)init;

@end

