//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class MCPeerID, NSData, NSDictionary;

@protocol SharePlayManagerDelegate

@optional
- (_Bool)sharePlayManager:(id)arg1 receiveMusicInfo:(NSDictionary *)arg2;
- (void)sharePlayManager:(id)arg1 receiveFinalScore:(int)arg2 bonus:(int)arg3 fullCombo:(_Bool)arg4;
- (void)sharePlayManager:(id)arg1 receiveScore:(int)arg2;
- (void)sharePlayManagerMusicStartTimeOut:(id)arg1;
- (void)sharePlayManager:(id)arg1 startMusicTime:(float)arg2;
- (void)sharePlayManager:(id)arg1 receiveProgress:(float)arg2;
- (_Bool)sharePlayManager:(id)arg1 musicDataReceived:(NSData *)arg2;
- (void)sharePlayManagerConnectFailed:(id)arg1;
- (void)sharePlayManagerConnectHost:(id)arg1;
- (void)sharePlayManagerHostSelectStart:(id)arg1;
- (void)sharePlayManager:(id)arg1 lostHostID:(MCPeerID *)arg2;
- (void)sharePlayManager:(id)arg1 findHostID:(MCPeerID *)arg2;
- (void)sharePlayManagerAllClientLoaded:(id)arg1;
- (void)sharePlayManagerAllClientReady:(id)arg1;
- (void)sharePlayManagerFailedSendMusicData:(id)arg1;
- (void)sharePlayManagerSuccessSendMusicData:(id)arg1;
- (void)sharePlayManager:(id)arg1 receiveExistMusicData:(_Bool)arg2;
- (void)sharePlayManagerConnectClient:(id)arg1;
- (void)sharePlayManager:(id)arg1 disconnectClient:(MCPeerID *)arg2;
- (void)sharePlayManagerDisconnect:(id)arg1;
@end

