//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, StoreButton, UILabel, UITableView;

@interface SocialSendSelectView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *listTable;
    UIView *coverBoard;
    UILabel *labelMessage;
    UIView *shadowView;
    StoreButton *btnOK;
    StoreButton *btnEnd;
    UILabel *textLabel;
    id delegate;
    NSArray *cellTitleTable;
    NSArray *socialTypeTable;
    NSString *mesString;
    int selectSlot;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)pushCancel:(id)arg1;
- (void)pushOK:(id)arg1;
- (id)initWithMessage:(id)arg1 delegate:(id)arg2;
- (void)createStoreBtn:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

