//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UILabel;

@interface StoreLoadingView : UIView
{
    UIActivityIndicatorView *accessingIndicator;
    UILabel *accessingLabel;
    UILabel *errorLabel;
}

- (void).cxx_destruct;
- (void)showError:(id)arg1;
- (void)stopLoading;
- (void)startLoading;
- (id)initWithFrame:(struct CGRect)arg1;

@end

