//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSCache, NSMutableArray, NSOperationQueue, NSString, NSTimer, NSURLSession, PagingScrollView, UIButton, UIImage, UIImageView, UILabel;
@protocol StorePromotionViewDelegate;

@interface StorePromotionView : UIView <UIScrollViewDelegate>
{
    unsigned long long currentIndex;
    NSTimer *bannerTimer;
    _Bool paused;
    NSMutableArray *arrayBannerView;
    PagingScrollView *scrollView;
    double pageWidth;
    double pageOffsetX;
    NSURLSession *session;
    UIView *shadowView;
    _Bool bEnableThumbnailPlay;
    _Bool bThumbnailPlaying;
    _Bool bIsSoundPlaying;
    NSString *currentThumbNail;
    NSString *reserveThumbNail;
    NSCache *thumbCache;
    NSOperationQueue *operationThumbQueue;
    NSMutableArray *downloadingThumbList;
    UILabel *musicNameLabel;
    UIImageView *bannerBgView;
    UIButton *sampleButton;
    UIImage *sampleButtonImageON;
    UIImage *sampleButtonImageOFF;
    id <StorePromotionViewDelegate> _delegate;
}

@property(nonatomic) __weak id <StorePromotionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stopThumbnail;
- (void)playThumbnail:(id)arg1 data:(id)arg2;
- (void)downloadImageSync:(id)arg1;
- (void)clearThumbnailCache;
- (id)getThumbnailData:(id)arg1;
- (void)thumbnailMute:(_Bool)arg1;
- (void)playBannerThumbnail:(int)arg1;
- (void)dealloc;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tapSampleBtn:(id)arg1;
- (void)bannerTapped:(id)arg1;
- (void)nextBanner;
- (void)stop;
- (void)resume;
- (void)pause;
- (void)start;
- (void)beginLoop;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setSampleButtonImage;
- (id)initWithFrame:(struct CGRect)arg1 promotions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

