//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface StoreDownloadTask : NSObject
{
    NSString *_sourceURL;
    NSString *_destPath;
}

@property(retain, nonatomic) NSString *destPath; // @synthesize destPath=_destPath;
@property(retain, nonatomic) NSString *sourceURL; // @synthesize sourceURL=_sourceURL;
- (void).cxx_destruct;
- (id)initWithURL:(id)arg1 path:(id)arg2;

@end

