//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface StorePackView : UIView
{
    UIImageView *bgView;
    UILabel *labelName;
    UILabel *labelComment;
    UILabel *labelPrice;
    UILabel *labelPurchased;
    UIImageView *newMarker;
    UIImageView *extendMarker;
    unsigned long long _index;
    UIImageView *_artworkView;
    id _delegate;
}

@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *artworkView; // @synthesize artworkView=_artworkView;
@property(readonly, nonatomic) unsigned long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (void)loadPackInfo:(id)arg1 index:(unsigned long long)arg2;
- (void)handleTap:(id)arg1;
- (void)setBgImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

