//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

#import "NSCacheDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSCache, NSMutableArray, NSOperationQueue, NSString, StorePackListGenre, UIImage, UIViewController;

@interface StorePackTableView : UITableView <UITableViewDataSource, UITableViewDelegate, NSCacheDelegate>
{
    UIImage *packBgImage0;
    UIImage *packBgImage1;
    UIImage *packBgImage0Add;
    UIImage *packBgImage1Add;
    UIImage *defaultArtwork;
    NSOperationQueue *operationQueue;
    NSCache *artworkCache;
    NSMutableArray *downloadingList;
    _Bool isLoadingMoreList;
    _Bool isPad;
    StorePackListGenre *_currentGenre;
    UIViewController *_viewController;
}

@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) StorePackListGenre *currentGenre; // @synthesize currentGenre=_currentGenre;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cache:(id)arg1 willEvictObject:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)selectLoadMoreCell:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)setupPackView:(id)arg1 index:(unsigned long long)arg2;
- (long long)numPackRows;
- (void)storePackViewSelected:(id)arg1;
- (void)downloadImageSync:(id)arg1;
- (void)clearArtworkCache;
- (void)stopLoadingMore:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

