//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface StoreMusicListManager : NSObject
{
    NSMutableArray *_arrayMusic;
    NSMutableArray *_arrayExtendMusic;
    NSArray *_arrayBuiltinMusic;
    NSMutableDictionary *_dictExtendMusic;
    NSMutableDictionary *_dictOriginalMusic;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *dictOriginalMusic; // @synthesize dictOriginalMusic=_dictOriginalMusic;
@property(retain, nonatomic) NSMutableDictionary *dictExtendMusic; // @synthesize dictExtendMusic=_dictExtendMusic;
@property(retain, nonatomic) NSArray *arrayBuiltinMusic; // @synthesize arrayBuiltinMusic=_arrayBuiltinMusic;
@property(retain, nonatomic) NSMutableArray *arrayExtendMusic; // @synthesize arrayExtendMusic=_arrayExtendMusic;
@property(retain, nonatomic) NSMutableArray *arrayMusic; // @synthesize arrayMusic=_arrayMusic;
- (void).cxx_destruct;
- (void)extendMusicID:(unsigned int)arg1 extendMID:(unsigned int)arg2;
- (void)extendMusicInfo:(unsigned int)arg1 holdFlg:(unsigned int)arg2 extendFlg:(unsigned int)arg3;
- (_Bool)addMusic:(id)arg1;
- (_Bool)checkChangedMusic:(id)arg1 info:(id)arg2;
- (void)loadMusicList;
- (void)saveMusicList;
- (id)extendInfoForID:(unsigned int)arg1;
- (id)linkURLForID:(unsigned int)arg1;
- (id)listMusicID;
- (id)originalMusicDictionary;
- (id)extendMusicDictionary;
- (id)extendMusic;
- (id)purchasedMusic;
- (id)builtinMusic;
- (_Bool)hasMusic:(int)arg1;
- (id)init;

@end

