//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ImageDownloaderDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class Downloader, NSMutableDictionary, NSString, SKStoreProductViewController, StoreDetailHeaderView, StoreLoadingView, StorePackInfo, UIImage, UITableView;

@interface StoreDetailViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, ImageDownloaderDelegate, SKStoreProductViewControllerDelegate>
{
    int rowSamplePlayed;
    _Bool isDownloadingSample;
    _Bool allowsRedownload;
    StoreDetailHeaderView *headerView;
    UITableView *detailTableView;
    StoreLoadingView *loadingView;
    Downloader *infoDownloader;
    Downloader *sampleDownloader;
    NSMutableDictionary *artworkDownloaders;
    UIImage *packBgImage0;
    UIImage *packBgImage1;
    SKStoreProductViewController *itunesViewCtrl;
    _Bool bDismissing;
    _Bool _bRestore;
    StorePackInfo *_packInfo;
    id _delegate;
    id _closeDelegate;
}

@property(nonatomic) _Bool bRestore; // @synthesize bRestore=_bRestore;
@property(nonatomic) __weak id closeDelegate; // @synthesize closeDelegate=_closeDelegate;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) StorePackInfo *packInfo; // @synthesize packInfo=_packInfo;
- (void).cxx_destruct;
- (void)detailClose;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)stopDownloadArtworks;
- (void)alertClose:(id)arg1;
- (void)alertSelect:(id)arg1;
- (void)imageDownloader:(id)arg1 didLoad:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)storeDetailViewOpenItunesWithURL:(id)arg1;
- (void)downloadExtendMusic:(id)arg1;
- (void)doPurchase:(id)arg1;
- (void)finishBgm:(id)arg1;
- (void)stopSample;
- (void)loadInfo;
- (void)showPackInfo;
- (void)updatePurchaseState;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

