//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class Downloader, NSArray, NSCache, NSMutableArray, NSOperationQueue, NSString, StoreDownloadManager, StoreViewController, UIImage, UITableView;

@interface StorePrivilegesViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    unsigned int working_index;
    _Bool isPad;
    StoreViewController *storeViewCtrl;
    UITableView *tableView;
    Downloader *infoDownloader;
    Downloader *musicInfoDownloader;
    int infoRandomKey;
    StoreDownloadManager *dlManager;
    NSMutableArray *downloadMusicList;
    NSArray *unlockMusicCheckList;
    _Bool firstDownloadFailed;
    NSCache *artworkCache;
    NSOperationQueue *operationQueue;
    NSMutableArray *downloadingList;
    UIImage *defaultArtwork;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)downloadImageSync:(id)arg1;
- (void)clearArtworkCache;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)setBadgeCnt:(int)arg1;
- (void)refreshUnlockBadge;
- (void)refreshUnlockTable;
- (void)refreshMusicList;
- (id)getArtwork:(id)arg1;
- (void)reloadUnlockList;
- (void)updateDownloadButton;
- (void)storeClose;
- (void)downloadManagerProceed:(id)arg1;
- (void)downloadManagerFailed:(id)arg1;
- (void)downloadManagerCompleted:(id)arg1;
- (void)storeDialogCancel:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)alertViewCancel:(id)arg1;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)displayUpdateAlert;
- (void)displayTerm:(id)arg1;
- (void)pushCellButton:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)downloadPrivilegesList;
- (void)loadView;
- (id)initWithParent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

