//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CampaignDetailViewController, CampaignItemDetailView, Downloader, NSArray, NSCache, NSMutableArray, NSOperationQueue, NSString, StoreDownloadManager, StoreLoadingView, StoreViewController, UITableView, UIView;

@interface StoreCampaignViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    long long startUpID;
    int working_index;
    _Bool isPad;
    StoreViewController *storeViewCtrl;
    UITableView *tableView;
    Downloader *infoDownloader;
    Downloader *musicInfoDownloader;
    Downloader *termsChecker;
    Downloader *itemURLDownloader;
    Downloader *markerDownloader;
    int infoRandomKey;
    StoreDownloadManager *dlManager;
    CampaignItemDetailView *itemDetailViewPad;
    UIView *coverViewPad;
    StoreLoadingView *loadingView;
    _Bool isOpenItemDetail;
    CampaignDetailViewController *itemDetailViewController;
    NSMutableArray *downloadMusicList;
    NSArray *unlockMusicCheckList;
    _Bool firstDownloadFailed;
    NSCache *artworkCache;
    NSOperationQueue *operationQueue;
    NSMutableArray *downloadingList;
    NSString *musicName;
}

- (void).cxx_destruct;
- (void)addOpenDetail:(long long)arg1;
- (void)initialCampaignID:(long long)arg1;
- (void)dealloc;
- (void)itemDeselect;
- (void)itemUpdate;
- (void)itemInfoDownload;
- (void)downloadImageSync:(id)arg1;
- (void)clearArtworkCache;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)setBadgeCnt:(int)arg1;
- (void)refreshUnlockBadge;
- (void)refreshUnlockTable;
- (void)refreshMusicList;
- (id)getArtwork:(id)arg1;
- (void)reloadUnlockList;
- (void)storeClose;
- (void)downloadManagerProceed:(id)arg1;
- (void)downloadManagerFailed:(id)arg1;
- (void)downloadManagerCompleted:(id)arg1;
- (void)downloadManagerStartTask:(id)arg1;
- (void)storeDialogCancel:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)alertSelect:(id)arg1;
- (void)displayUpdateAlert;
- (void)displayTerm:(id)arg1;
- (void)itemDownload;
- (void)moveExternalLink;
- (void)pushCellButton:(id)arg1;
- (void)selectItem:(int)arg1;
- (void)pushExternalLink:(id)arg1;
- (void)handleTapCoverView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)downloadCampaignList;
- (void)loadView;
- (id)initWithParent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

