//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface StorePackCell : UITableViewCell
{
    UIImageView *bgView;
    UILabel *labelName;
    UILabel *labelPrice;
    UILabel *labelPurchased;
    UIImageView *newMarker;
    UIImageView *extendMarker;
    UIImageView *_artworkView;
}

@property(readonly, nonatomic) UIImageView *artworkView; // @synthesize artworkView=_artworkView;
- (void).cxx_destruct;
- (void)setBgImage:(id)arg1;
- (void)loadPackInfo:(id)arg1;
@property(nonatomic) _Bool isPurchased;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

