//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface StoreMusicInfo : NSObject
{
    int _musicID;
    int _lvBas;
    int _lvAdv;
    int _lvExt;
    unsigned int _extendMusicID;
    unsigned int _holdFlag;
    unsigned int _extendFlag;
    NSString *_name;
    NSString *_artist;
    NSString *_itemURL;
    NSString *_artworkURL;
    NSString *_sampleURL;
    NSString *_itunesURL;
    NSString *_extendItemURL;
    StoreMusicInfo *_extendInfo;
}

@property(retain, nonatomic) StoreMusicInfo *extendInfo; // @synthesize extendInfo=_extendInfo;
@property(readonly, nonatomic) NSString *extendItemURL; // @synthesize extendItemURL=_extendItemURL;
@property(readonly, nonatomic) unsigned int extendFlag; // @synthesize extendFlag=_extendFlag;
@property(readonly, nonatomic) unsigned int holdFlag; // @synthesize holdFlag=_holdFlag;
@property(readonly, nonatomic) unsigned int extendMusicID; // @synthesize extendMusicID=_extendMusicID;
@property(retain, nonatomic) NSString *itunesURL; // @synthesize itunesURL=_itunesURL;
@property(retain, nonatomic) NSString *sampleURL; // @synthesize sampleURL=_sampleURL;
@property(retain, nonatomic) NSString *artworkURL; // @synthesize artworkURL=_artworkURL;
@property(retain, nonatomic) NSString *itemURL; // @synthesize itemURL=_itemURL;
@property(retain, nonatomic) NSString *artist; // @synthesize artist=_artist;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) int lvExt; // @synthesize lvExt=_lvExt;
@property(readonly, nonatomic) int lvAdv; // @synthesize lvAdv=_lvAdv;
@property(readonly, nonatomic) int lvBas; // @synthesize lvBas=_lvBas;
@property(readonly, nonatomic) int musicID; // @synthesize musicID=_musicID;
- (void).cxx_destruct;
- (id)getExtendInfo;
- (id)initWithDictionary:(id)arg1;

@end

