//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class Downloader, NSArray, NSURL, StoreButton, StoreImageView, StorePackInfo, UIActivityIndicatorView, UIButton, UILabel, UIViewController, UnselectableTextView;

@interface StorePackDetailView : UIView
{
    int samplePlaying;
    _Bool isInfoLoaded;
    _Bool allowsRedownload;
    NSArray *arrayMusicView;
    UIView *packView;
    StoreImageView *packArtworkView;
    UILabel *labelPackName;
    UILabel *labelComment;
    StoreButton *buttonPurchase;
    UnselectableTextView *copyrightView;
    UIButton *buttonLink;
    UIActivityIndicatorView *indicator;
    UILabel *labelLoading;
    NSURL *jumpURL;
    Downloader *infoDownloader;
    Downloader *sampleDownloader;
    UIButton *buttonExtendDownload;
    StorePackInfo *_packInfo;
    id _delegate;
    UIViewController *_viewController;
}

@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) StorePackInfo *packInfo; // @synthesize packInfo=_packInfo;
- (void).cxx_destruct;
- (void)dealloc;
- (void)detailClose;
- (void)alertClose:(id)arg1;
- (void)alertSelect:(id)arg1;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderError:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)finishBgm:(id)arg1;
- (void)handleSample:(id)arg1;
- (void)handleLink:(id)arg1;
- (void)downloadExtendMusic:(id)arg1;
- (void)doPurchase:(id)arg1;
- (void)loadRestoreInfo;
- (void)loadInfo;
- (void)showPackInfo;
- (void)updatePurchaseState;
- (void)stopSample;
- (void)cancelLoading;
- (void)removePackInfo;
- (id)initWithFrame:(struct CGRect)arg1;

@end

