//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Downloader, NSArray;

@interface StoreDownloadManager : NSObject
{
    _Bool isStarted;
    NSArray *tasks;
    Downloader *fileDownloader;
    id delegate;
    unsigned int _currentIndex;
}

@property(nonatomic) unsigned int currentIndex; // @synthesize currentIndex=_currentIndex;
- (void).cxx_destruct;
- (void)dealloc;
- (void)downloaderError:(id)arg1;
- (void)downloaderProceed:(id)arg1;
- (void)downloaderFinished:(id)arg1;
- (void)cancel;
- (void)start;
@property(readonly, nonatomic) unsigned int numTasks;
@property(readonly, nonatomic) float overallProgress;
@property(readonly, nonatomic) float currentProgress;
- (id)initWithTasks:(id)arg1 delegate:(id)arg2;
- (id)getTuneInfoFromUnzip:(id)arg1;

@end

