//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface StoreUtil : NSObject
{
}

+ (_Bool)existDownloadableExtendMusic:(id)arg1;
+ (_Bool)existMusicFile:(int)arg1;
+ (id)storeExtendListURL;
+ (id)storeUserPolicyURL;
+ (id)passedInfoListURL;
+ (id)startNewsURL;
+ (id)recommendPackURL:(unsigned int)arg1;
+ (id)filePathForMusicID:(unsigned int)arg1;
+ (_Bool)isValidURL:(id)arg1;
+ (id)affiliateParametersFromURL:(id)arg1;
+ (id)priceString:(id)arg1 withLocale:(id)arg2;
+ (int)packIDForProductID:(id)arg1;
+ (id)productIDForPackID:(int)arg1;
+ (id)checkStoreResponse:(id)arg1;
+ (id)markerListURL;
+ (id)knitColorURL;
+ (id)campaignItemURL;
+ (id)campaignSerialCheckURL;
+ (id)campaignListURL;
+ (id)privilegeMusicInfoURL:(unsigned int)arg1;
+ (id)privilegeListURL:(int)arg1;
+ (id)verifyReceiptConsumeURL;
+ (id)verifyReceiptNewURL;
+ (id)storeNewInfoURL;
+ (id)musicInfoURL:(unsigned int)arg1;
+ (id)restorePackInfoURL:(unsigned int)arg1;
+ (id)packInfoURL:(unsigned int)arg1;
+ (id)selectivePackListURL:(id)arg1;
+ (id)packListURL:(unsigned int)arg1 limit:(unsigned int)arg2 genre:(unsigned int)arg3;
+ (id)queryStringForDictionary:(id)arg1;

@end

