//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableArray, SVSegmentedThumb, UIColor, UIFont, UIImage;
@protocol SVSegmentedControlDelegate;

@interface SVSegmentedControl : UIControl
{
    _Bool animateToInitialSelection;
    _Bool crossFadeLabelsOnDrag;
    _Bool trackingThumb;
    _Bool moved;
    _Bool activated;
    CDUnknownBlockType selectedSegmentChangedHandler;
    CDUnknownBlockType changeHandler;
    unsigned long long selectedIndex;
    NSMutableArray *accessibilityElements;
    double cornerRadius;
    UIColor *tintColor;
    UIImage *backgroundImage;
    UIFont *font;
    UIColor *textColor;
    UIColor *textShadowColor;
    double segmentPadding;
    double height;
    NSMutableArray *titlesArray;
    SVSegmentedThumb *thumb;
    NSMutableArray *thumbRects;
    unsigned long long snapToIndex;
    double halfSize;
    double dragOffset;
    double segmentWidth;
    double thumbHeight;
    id <SVSegmentedControlDelegate> delegate;
    UIColor *shadowColor;
    struct CGSize textShadowOffset;
    struct CGSize shadowOffset;
    struct UIEdgeInsets titleEdgeInsets;
    struct UIEdgeInsets thumbEdgeInset;
}

@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset;
@property(retain, nonatomic) UIColor *shadowColor; // @synthesize shadowColor;
@property(nonatomic) struct UIEdgeInsets thumbEdgeInset; // @synthesize thumbEdgeInset;
@property(nonatomic) id <SVSegmentedControlDelegate> delegate; // @synthesize delegate;
@property(nonatomic) double thumbHeight; // @synthesize thumbHeight;
@property(nonatomic) double segmentWidth; // @synthesize segmentWidth;
@property(nonatomic) double dragOffset; // @synthesize dragOffset;
@property(nonatomic) double halfSize; // @synthesize halfSize;
@property(nonatomic) _Bool activated; // @synthesize activated;
@property(nonatomic) _Bool moved; // @synthesize moved;
@property(nonatomic) _Bool trackingThumb; // @synthesize trackingThumb;
@property(nonatomic) unsigned long long snapToIndex; // @synthesize snapToIndex;
@property(retain, nonatomic) NSMutableArray *thumbRects; // @synthesize thumbRects;
@property(retain, nonatomic) NSMutableArray *titlesArray; // @synthesize titlesArray;
@property(nonatomic) _Bool crossFadeLabelsOnDrag; // @synthesize crossFadeLabelsOnDrag;
@property(nonatomic) double height; // @synthesize height;
@property(nonatomic) struct UIEdgeInsets titleEdgeInsets; // @synthesize titleEdgeInsets;
@property(nonatomic) double segmentPadding; // @synthesize segmentPadding;
@property(nonatomic) struct CGSize textShadowOffset; // @synthesize textShadowOffset;
@property(retain, nonatomic) UIColor *textShadowColor; // @synthesize textShadowColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor;
@property(retain, nonatomic) UIFont *font; // @synthesize font;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;
@property(retain, nonatomic) NSMutableArray *accessibilityElements; // @synthesize accessibilityElements;
@property(nonatomic) _Bool animateToInitialSelection; // @synthesize animateToInitialSelection;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex;
@property(copy, nonatomic) CDUnknownBlockType changeHandler; // @synthesize changeHandler;
@property(copy, nonatomic) CDUnknownBlockType selectedSegmentChangedHandler; // @synthesize selectedSegmentChangedHandler;
- (void).cxx_destruct;
- (void)moveThumbToIndex:(unsigned long long)arg1 animate:(_Bool)arg2;
- (void)toggle;
- (void)activate;
- (void)updateTitles;
- (void)snap:(_Bool)arg1;
- (void)cancelTrackingWithEvent:(id)arg1;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (void)setupAccessibility;
- (void)setCenter:(struct CGPoint)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)willMoveToSuperview:(id)arg1;
@property(readonly, nonatomic) SVSegmentedThumb *thumb; // @synthesize thumb;
- (id)initWithSectionTitles:(id)arg1;

@end

