//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface Texture2D : NSObject
{
    unsigned long long pixelFormat;
    unsigned int _size;
    struct CGRect *spriteRect;
    int numSprite;
    struct {
        float _field1;
        float _field2;
        float _field3;
        float _field4;
        float _field5;
        unsigned char _field6;
        unsigned char _field7;
        unsigned char _field8;
        unsigned char _field9;
    } *vertices;
    unsigned int currentPolys;
    struct CGRect _clipRect;
    _Bool _isScale2x;
    unsigned int _name;
    unsigned long long _width;
    unsigned long long _height;
}

+ (struct CGRect)scaledRect:(struct CGRect)arg1 scale:(double)arg2 anchor:(struct CGPoint)arg3;
@property(readonly, nonatomic) unsigned long long height; // @synthesize height=_height;
@property(readonly, nonatomic) unsigned long long width; // @synthesize width=_width;
@property(readonly, nonatomic) unsigned int name; // @synthesize name=_name;
@property(nonatomic) _Bool isScale2x; // @synthesize isScale2x=_isScale2x;
- (void)dealloc;
- (void)setClipRect:(struct CGRect)arg1;
- (struct CGRect)spriteAtIndex:(unsigned int)arg1;
- (void)setSprites:(id)arg1;
- (void)resetDrawBuffer;
- (void)commitDraw;
- (void)drawSprite:(unsigned long long)arg1 inRect:(struct CGRect)arg2;
- (void)drawSprite:(unsigned long long)arg1 inRect:(struct CGRect)arg2 color:(id)arg3;
- (void)drawSprite:(unsigned long long)arg1 atPoint:(struct CGPoint)arg2;
- (void)drawSprite:(unsigned long long)arg1 inRect:(struct CGRect)arg2 transform:(BOOL)arg3 alpha:(float)arg4;
- (void)drawSprite:(unsigned long long)arg1 atPoint:(struct CGPoint)arg2 transform:(BOOL)arg3 alpha:(float)arg4;
- (void)drawSprite:(unsigned long long)arg1 atPoint:(struct CGPoint)arg2 scale:(float)arg3 rotate:(float)arg4 anchor:(struct CGPoint)arg5 transform:(BOOL)arg6 alpha:(float)arg7;
- (void)drawInRect:(struct CGRect)arg1 fromRegion:(struct CGRect)arg2 transform:(BOOL)arg3 alpha:(float)arg4;
- (void)drawInRect:(struct CGRect)arg1 fromRegion:(struct CGRect)arg2 transform:(BOOL)arg3 color:(id)arg4;
- (void)drawAtPoint:(struct CGPoint)arg1 scale:(double)arg2;
- (void)setSubImage:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)setSubImage:(id)arg1 inRect:(struct CGRect)arg2;
- (id)initWithImage:(id)arg1;
- (id)initWithData:(const void *)arg1 pixelFormat:(unsigned long long)arg2 pixelSize:(unsigned int)arg3;
- (id)initWithData:(const void *)arg1 pixelFormat:(unsigned long long)arg2 pixelSize:(unsigned int)arg3 width:(int)arg4 height:(int)arg5;
- (void)setData:(const void *)arg1 pixelFormat:(unsigned long long)arg2 pixelSize:(unsigned int)arg3;
- (void)setData:(const void *)arg1 pixelFormat:(unsigned long long)arg2 pixelSize:(unsigned int)arg3 width:(int)arg4 height:(int)arg5;
- (id)init;

@end

