//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TitleViewController.h"

@class EditorIDManager, LicenseAgreementView, MarkerDownloadView, NSArray, UIImageView, UITapGestureRecognizer, UIView;

@interface TitleViewControllerRpl : TitleViewController
{
    _Bool isPad;
    int kcState;
    int yHorizon;
    UIImageView *jubeatLogoView;
    UIImageView *touchView;
    UIImageView *copyrightView;
    NSArray *arrayRippleLayer;
    NSArray *arrayReflectedRippleLayer;
    NSArray *arraySwipeRecognizer;
    UITapGestureRecognizer *tapRecognizer;
    EditorIDManager *idManager;
    LicenseAgreementView *licenseAgree;
    UIView *coverView;
    MarkerDownloadView *markerView;
}

- (void).cxx_destruct;
- (void)successIDDownload:(id)arg1;
- (void)errorIDDownload:(id)arg1 msgStr:(id)arg2;
- (void)agreementFailed:(id)arg1;
- (void)agreementSuccess:(id)arg1;
- (void)agreementError:(id)arg1 msgStr:(id)arg2;
- (void)createPolicyView;
- (void)nextScene;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)markerCheckEnd;
- (void)viewDidUnload;
- (void)resume:(id)arg1;
- (void)suspend:(id)arg1;
- (void)handleSwipe:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)showLogo;
- (void)startBlinkPrompt;
- (void)startMarkerCheck;
- (void)blinkPrompt;
- (void)start;
- (void)loadView;
- (void)addRippleLayers;
- (id)init;

@end

