//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TitleViewController.h"

@class CADisplayLink, CMMotionManager, EAGLView, EditorIDManager, LicenseAgreementView, MarkerDownloadView, NSArray, NSMutableArray, SePlayer, Texture2D, UIImage, UIImageView, UITapGestureRecognizer, UIView, UpperBGKnit;

@interface TitleViewControllerKnt : TitleViewController
{
    _Bool isPad;
    _Bool is4Inch;
    int kcState;
    _Bool isWave;
    unsigned long long deviceType;
    struct CGPoint conciergePos;
    struct CGSize conciergeSize;
    struct CGPoint oldConPos;
    int conMoveFrame;
    int conShakeFrame;
    int conShakeUpFrame;
    int conStopFrame;
    float degOld;
    float degBak;
    float accelaOld;
    _Bool isPortrait;
    int tapCnt;
    int tapMax;
    CMMotionManager *motionManager;
    UIImageView *jubeatLogoView;
    UIImageView *touchView;
    UIImageView *copyrightView;
    NSArray *arraySwipeRecognizer;
    UITapGestureRecognizer *tapRecognizer;
    EAGLView *glView;
    NSMutableArray *texWaveAr;
    UpperBGKnit *upperBgKnt;
    CADisplayLink *displayLink;
    Texture2D *conTex;
    UIImage *replaceImage;
    SePlayer *sePlayer;
    EditorIDManager *idManager;
    LicenseAgreementView *licenseAgree;
    UIView *coverView;
    MarkerDownloadView *markerView;
    int conType;
}

- (void).cxx_destruct;
- (void)successIDDownload:(id)arg1;
- (void)errorIDDownload:(id)arg1 msgStr:(id)arg2;
- (void)agreementFailed:(id)arg1;
- (void)agreementSuccess:(id)arg1;
- (void)agreementError:(id)arg1 msgStr:(id)arg2;
- (void)createPolicyView;
- (void)nextScene;
- (void)becomeConcierge;
- (int)getConciergeType;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)markerCheckEnd;
- (void)renderConcierge;
- (void)viewDidUnload;
- (void)stopAnimation;
- (void)resume:(id)arg1;
- (void)suspend:(id)arg1;
- (void)handleSwipe:(id)arg1;
- (void)handleTap:(id)arg1;
- (struct CGRect)getConciergeRect;
- (void)showLogo;
- (void)startBlinkPrompt;
- (void)startMarkerCheck;
- (void)blinkPrompt;
- (void)loop:(id)arg1;
- (void)start;
- (void)loadView;
- (id)init;

@end

