//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface UpperBGKnit : NSObject
{
    UIColor *bgColor;
    UIColor *waveColor;
    UIColor *lineColor;
    struct CGRect drawArea;
    float wavePosY;
    int waveWidth[4];
    int wavePos[4];
    int waveSpeed[4];
    int pulseWaveHeight;
    float waveTable[4][2048];
    float addPulse[4][1024];
    float pulseTable[512];
    float pulseWidth;
    _Bool risePulse[4][4];
    int riseTimer[4][4];
    int waveTopY;
    int pushWaveHeight;
    _Bool isPad_;
    float deg_;
    float accela_;
    int accela_cnt_;
    _Bool plugFlag_;
    int plugTimer_;
    int plugExtendTimer_;
}

- (void).cxx_destruct;
- (void)plugWave:(float)arg1;
- (void)addAccelerated:(float)arg1;
- (void)setDeg:(float)arg1;
- (void)commitBg:(id)arg1;
- (void)riseUp:(int)arg1 riseColumn:(int)arg2;
- (void)renderUpperBg:(id)arg1 tension:(int)arg2 isResult:(_Bool)arg3;
- (void)pulseUpdate:(int)arg1 isResult:(_Bool)arg2;
- (void)initBg:(struct CGRect)arg1 waveBottom:(float)arg2 waveTop:(float)arg3 pulseHeight:(float)arg4 isPad:(_Bool)arg5;
- (id)init;

@end

