//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UpperBGRipple : NSObject
{
    struct CGPoint point;
    float x_spd;
    float y_spd;
    float weight;
    float y_gnd;
    float y_amp;
    float y_ctr;
    float mag;
    unsigned int y_period;
    unsigned int y_phase;
    unsigned long long sprite;
}

@property(readonly, nonatomic) float y_gnd; // @synthesize y_gnd;
- (long long)compZ:(id)arg1;
- (void)renderWithTexture:(id)arg1 yLimit:(float)arg2;
- (void)stepFall:(float)arg1 gravity:(float)arg2 bounce:(float)arg3;
- (void)triggerJump:(float)arg1;
- (id)initWithSprite:(unsigned long long)arg1 atPoint:(struct CGPoint)arg2 xSpeed:(float)arg3 yGround:(float)arg4 yAmp:(float)arg5 yCenter:(float)arg6 yPeriod:(unsigned int)arg7 yPhase:(unsigned int)arg8 mag:(float)arg9;

@end

